<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>16&nbsp; Jupyter – Missing Manual for Information Scientists</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/scripting.html" rel="next">
<link href="../chapters/virtual-environments.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a01bfd6df65136af83067365c1c6ba8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-eb8f170073725aebc42af3c4860b2e9c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9a01bfd6df65136af83067365c1c6ba8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../tools/chapter-meme/chapter-meme.css">
<link rel="stylesheet" href="../styles/layout.css">
</head>

<body class="nav-sidebar docked slimcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/package-management.html">Part III — Python Management</a></li><li class="breadcrumb-item"><a href="../chapters/jupyter.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Jupyter</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Missing Manual for Information Scientists</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/cuinfoscience/INFO-Missing-Manual" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=|url|" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Practice of Technical Work</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Asking Technical Questions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/documentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Technical Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/common-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Common Text Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-docs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reading Official Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Debugging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tracebacks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reading Python Tracebacks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/artifacts-have-politics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Artifacts Have Politics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Computing Environment</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/operating-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Operating System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/file-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Local File System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/terminal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Command Line</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/text-editors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Text Editors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/remote.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Remote Computing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Python Management</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/package-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Package Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/virtual-environments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Virtual Environments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/jupyter.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Jupyter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/scripting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Scripting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/regex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regular Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Code Style</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Working with Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-file-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data File Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tabular-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Tabular Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/pandas-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">pandas Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sql-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/http-apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">HTTP and Web APIs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V — Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-scholarship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">How to Read Scholarly Articles and Books</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/writing-manuscripts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">How to Write Scholarly Manuscripts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/writing-thesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">How to Write a Thesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/presenting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">How to Present</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">How to Use LaTeX</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI — Project Management</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/project-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/version-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Version Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/collaboration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Collaboration Mechanics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/automation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Automation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/secrets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Environment Variables and Secrets</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VII — Algorithmic Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ai-llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Using AI Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/llm-internals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">How Language Models Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ai-agents.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Working with AI Agent Frameworks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/evaluating-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Evaluating and Auditing AI Outputs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-ai-disclosure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Disclosure: Use of AI in Authoring</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="../graphics/memes/jupyter.png" class="chapter-meme img-fluid" alt="Who Killed Hannibal? Meme: Out-of-Order Cell Execution, My Jupyter Notebook, Why Would Python Do This?"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#why-read-this-chapter" id="toc-why-read-this-chapter" class="nav-link" data-scroll-target="#why-read-this-chapter">Why read this chapter</a></li>
  <li><a href="#running-theme-notebooks-are-documents-and-programs" id="toc-running-theme-notebooks-are-documents-and-programs" class="nav-link" data-scroll-target="#running-theme-notebooks-are-documents-and-programs">Running theme: notebooks are documents <em>and</em> programs</a></li>
  <li><a href="#what-jupyter-is-doing" id="toc-what-jupyter-is-doing" class="nav-link" data-scroll-target="#what-jupyter-is-doing"><span class="header-section-number">16.1</span> What Jupyter is doing</a></li>
  <li><a href="#launching-jupyter-the-right-way" id="toc-launching-jupyter-the-right-way" class="nav-link" data-scroll-target="#launching-jupyter-the-right-way"><span class="header-section-number">16.2</span> Launching Jupyter the right way</a>
  <ul class="collapse">
  <li><a href="#when-your-files-arent-there" id="toc-when-your-files-arent-there" class="nav-link" data-scroll-target="#when-your-files-arent-there">When your files aren’t there</a></li>
  </ul></li>
  <li><a href="#cells-and-running-them" id="toc-cells-and-running-them" class="nav-link" data-scroll-target="#cells-and-running-them"><span class="header-section-number">16.3</span> Cells and running them</a>
  <ul class="collapse">
  <li><a href="#cell-types" id="toc-cell-types" class="nav-link" data-scroll-target="#cell-types">Cell types</a></li>
  <li><a href="#running-cells-and-stopping-them" id="toc-running-cells-and-stopping-them" class="nav-link" data-scroll-target="#running-cells-and-stopping-them">Running cells, and stopping them</a></li>
  <li><a href="#organizing-cells" id="toc-organizing-cells" class="nav-link" data-scroll-target="#organizing-cells">Organizing cells</a></li>
  </ul></li>
  <li><a href="#keeping-notebooks-small" id="toc-keeping-notebooks-small" class="nav-link" data-scroll-target="#keeping-notebooks-small"><span class="header-section-number">16.4</span> Keeping notebooks small</a></li>
  <li><a href="#shell-commands-and-magics" id="toc-shell-commands-and-magics" class="nav-link" data-scroll-target="#shell-commands-and-magics"><span class="header-section-number">16.5</span> Shell commands and magics</a>
  <ul class="collapse">
  <li><a href="#bangs-and-magics" id="toc-bangs-and-magics" class="nav-link" data-scroll-target="#bangs-and-magics">Bangs and magics</a></li>
  <li><a href="#magics-worth-knowing" id="toc-magics-worth-knowing" class="nav-link" data-scroll-target="#magics-worth-knowing">Magics worth knowing</a></li>
  <li><a href="#using-the-shell-safely" id="toc-using-the-shell-safely" class="nav-link" data-scroll-target="#using-the-shell-safely">Using the shell safely</a></li>
  </ul></li>
  <li><a href="#writing-a-notebook-that-survives" id="toc-writing-a-notebook-that-survives" class="nav-link" data-scroll-target="#writing-a-notebook-that-survives"><span class="header-section-number">16.6</span> Writing a notebook that survives</a>
  <ul class="collapse">
  <li><a href="#give-it-a-predictable-structure" id="toc-give-it-a-predictable-structure" class="nav-link" data-scroll-target="#give-it-a-predictable-structure">Give it a predictable structure</a></li>
  <li><a href="#write-the-prose" id="toc-write-the-prose" class="nav-link" data-scroll-target="#write-the-prose">Write the prose</a></li>
  <li><a href="#keep-it-reproducible" id="toc-keep-it-reproducible" class="nav-link" data-scroll-target="#keep-it-reproducible">Keep it reproducible</a></li>
  <li><a href="#record-the-environment" id="toc-record-the-environment" class="nav-link" data-scroll-target="#record-the-environment">Record the environment</a></li>
  </ul></li>
  <li><a href="#notebook-pitfalls-and-how-to-prevent-them" id="toc-notebook-pitfalls-and-how-to-prevent-them" class="nav-link" data-scroll-target="#notebook-pitfalls-and-how-to-prevent-them"><span class="header-section-number">16.7</span> Notebook pitfalls and how to prevent them</a>
  <ul class="collapse">
  <li><a href="#out-of-order-execution" id="toc-out-of-order-execution" class="nav-link" data-scroll-target="#out-of-order-execution">Out-of-order execution</a></li>
  <li><a href="#wrong-kernel-wrong-environment" id="toc-wrong-kernel-wrong-environment" class="nav-link" data-scroll-target="#wrong-kernel-wrong-environment">Wrong kernel, wrong environment</a></li>
  <li><a href="#file-not-found" id="toc-file-not-found" class="nav-link" data-scroll-target="#file-not-found">File not found</a></li>
  <li><a href="#long-running-or-stuck-cells" id="toc-long-running-or-stuck-cells" class="nav-link" data-scroll-target="#long-running-or-stuck-cells">Long-running or stuck cells</a></li>
  </ul></li>
  <li><a href="#finding-whats-slow-measure-then-profile" id="toc-finding-whats-slow-measure-then-profile" class="nav-link" data-scroll-target="#finding-whats-slow-measure-then-profile"><span class="header-section-number">16.8</span> Finding what’s slow: measure, then profile</a>
  <ul class="collapse">
  <li><a href="#time-one-step-timeit" id="toc-time-one-step-timeit" class="nav-link" data-scroll-target="#time-one-step-timeit">Time one step: <code>%timeit</code></a></li>
  <li><a href="#find-where-the-time-goes-a-profiler" id="toc-find-where-the-time-goes-a-profiler" class="nav-link" data-scroll-target="#find-where-the-time-goes-a-profiler">Find where the time goes: a profiler</a></li>
  <li><a href="#fix-the-biggest-cost-then-measure-again" id="toc-fix-the-biggest-cost-then-measure-again" class="nav-link" data-scroll-target="#fix-the-biggest-cost-then-measure-again">Fix the biggest cost, then measure again</a></li>
  <li><a href="#the-usual-suspects-in-pandas" id="toc-the-usual-suspects-in-pandas" class="nav-link" data-scroll-target="#the-usual-suspects-in-pandas">The usual suspects in pandas</a></li>
  </ul></li>
  <li><a href="#when-to-move-from-notebooks-to-scripts-and-back" id="toc-when-to-move-from-notebooks-to-scripts-and-back" class="nav-link" data-scroll-target="#when-to-move-from-notebooks-to-scripts-and-back"><span class="header-section-number">16.9</span> When to move from notebooks to scripts (and back)</a></li>
  <li><a href="#notebooks-on-someone-elses-computer-colab-kaggle-and-codespaces" id="toc-notebooks-on-someone-elses-computer-colab-kaggle-and-codespaces" class="nav-link" data-scroll-target="#notebooks-on-someone-elses-computer-colab-kaggle-and-codespaces"><span class="header-section-number">16.10</span> Notebooks on someone else’s computer: Colab, Kaggle, and Codespaces</a>
  <ul class="collapse">
  <li><a href="#what-survives-when-you-leave" id="toc-what-survives-when-you-leave" class="nav-link" data-scroll-target="#what-survives-when-you-leave">What survives when you leave</a></li>
  <li><a href="#the-environment-isnt-yours" id="toc-the-environment-isnt-yours" class="nav-link" data-scroll-target="#the-environment-isnt-yours">The environment isn’t yours</a></li>
  <li><a href="#secrets-go-in-the-platforms-secrets-store" id="toc-secrets-go-in-the-platforms-secrets-store" class="nav-link" data-scroll-target="#secrets-go-in-the-platforms-secrets-store">Secrets go in the platform’s secrets store</a></li>
  <li><a href="#gpus-available-not-promised" id="toc-gpus-available-not-promised" class="nav-link" data-scroll-target="#gpus-available-not-promised">GPUs: available, not promised</a></li>
  <li><a href="#before-you-upload-data" id="toc-before-you-upload-data" class="nav-link" data-scroll-target="#before-you-upload-data">Before you upload data</a></li>
  </ul></li>
  <li><a href="#stakes-and-politics" id="toc-stakes-and-politics" class="nav-link" data-scroll-target="#stakes-and-politics"><span class="header-section-number">16.11</span> Stakes and politics</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples"><span class="header-section-number">16.12</span> Worked examples</a>
  <ul class="collapse">
  <li><a href="#launching-jupyter-in-the-right-place" id="toc-launching-jupyter-in-the-right-place" class="nav-link" data-scroll-target="#launching-jupyter-in-the-right-place">Launching Jupyter in the right place</a></li>
  <li><a href="#debugging-no-files" id="toc-debugging-no-files" class="nav-link" data-scroll-target="#debugging-no-files">Debugging “no files”</a></li>
  <li><a href="#making-a-notebook-reproducible" id="toc-making-a-notebook-reproducible" class="nav-link" data-scroll-target="#making-a-notebook-reproducible">Making a notebook reproducible</a></li>
  </ul></li>
  <li><a href="#templates" id="toc-templates" class="nav-link" data-scroll-target="#templates"><span class="header-section-number">16.13</span> Templates</a>
  <ul class="collapse">
  <li><a href="#template-a-notebook-header-block" id="toc-template-a-notebook-header-block" class="nav-link" data-scroll-target="#template-a-notebook-header-block">Template A: Notebook header block</a></li>
  <li><a href="#template-b-reproducibility-check-cell" id="toc-template-b-reproducibility-check-cell" class="nav-link" data-scroll-target="#template-b-reproducibility-check-cell">Template B: Reproducibility check cell</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">16.14</span> Exercises</a></li>
  <li><a href="#one-page-checklist" id="toc-one-page-checklist" class="nav-link" data-scroll-target="#one-page-checklist"><span class="header-section-number">16.15</span> One-page checklist</a></li>
  <li><a href="#quick-reference-common-launch-and-debugging-moves" id="toc-quick-reference-common-launch-and-debugging-moves" class="nav-link" data-scroll-target="#quick-reference-common-launch-and-debugging-moves"><span class="header-section-number">16.16</span> Quick reference: common launch and debugging moves</a></li>
  <li><a href="#quick-reference-ipython-conveniences" id="toc-quick-reference-ipython-conveniences" class="nav-link" data-scroll-target="#quick-reference-ipython-conveniences"><span class="header-section-number">16.17</span> Quick reference: IPython conveniences</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/edit/main/chapters/jupyter.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/package-management.html">Part III — Python Management</a></li><li class="breadcrumb-item"><a href="../chapters/jupyter.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Jupyter</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-jupyter" class="quarto-section-identifier"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Jupyter</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Prerequisites and see-also
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Prerequisites (read first if unfamiliar):</strong> <a href="package-management.html" class="quarto-xref"><span>Chapter 14</span></a>, <a href="virtual-environments.html" class="quarto-xref"><span>Chapter 15</span></a>.</p>
<p><strong>See also:</strong> <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a>, <a href="tracebacks.html" class="quarto-xref"><span>Chapter 7</span></a>, <a href="presenting.html" class="quarto-xref"><span>Chapter 28</span></a>.</p>
</div>
</div>
</div>
<section id="purpose" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="purpose">Purpose</h2>
<div class="chapter-meme-inline d-lg-none">
<p><img src="../graphics/memes/jupyter.png" class="img-fluid" alt="Who Killed Hannibal? Meme: Out-of-Order Cell Execution, My Jupyter Notebook, Why Would Python Do This?"></p>
</div>
<p>It’s the night before the assignment is due, and your notebook is finished. Every cell has output, the charts look right, and the conclusion is written. To be safe, you click <em>Restart Kernel and Run All Cells</em>, and the fourth cell stops with an error you’ve never seen. Nothing about the code changed. What changed is that, for the first time in days, the notebook ran from the top in the order it’s written on the page, instead of the order you happened to click through it.</p>
<p>If that has happened to you, you’re in very good company. <a href="https://en.wikipedia.org/wiki/Project_Jupyter">Jupyter notebooks</a> are wonderful for exploring data, because they put code, results, and your own explanation side by side, and you can try something, look, and try again. That same flexibility is where the trouble comes from: a notebook remembers everything you’ve run, in whatever order you ran it, so it can look finished while depending on steps nobody can see. Add a server started from the wrong folder, a kernel pointing at the wrong Python, and a file that grows every time you print a table, and you have most of the frustration students feel about Jupyter.</p>
<p>This chapter is about the habits that prevent those problems: launching Jupyter so it finds your files, understanding what the kernel remembers, using cells, magics, and shell commands well, writing a notebook someone else can rerun, finding out what makes one slow, and working on hosted platforms like Google Colab. It doesn’t teach Python or pandas (see <a href="pandas-basics.html" class="quarto-xref"><span>Chapter 22</span></a>), and it leaves the full story of scripts to <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a>, though it does explain when to move work from one to the other.</p>
</section>
<section id="why-read-this-chapter" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="why-read-this-chapter">Why read this chapter</h2>
<ul>
<li>You opened JupyterLab and saw your home folder or <code>Downloads</code> instead of your project, and you’re not sure where your files went.</li>
<li><code>pd.read_csv("data/raw/sales.csv")</code> says <code>FileNotFoundError</code> while the file sits right there in the file browser.</li>
<li>You ran <code>pip install pandas</code>, and the notebook still says <code>ModuleNotFoundError: No module named 'pandas'</code>.</li>
<li>Your notebook worked all evening, then <em>Restart Kernel and Run All Cells</em> stopped it with an error in the fourth cell.</li>
<li>You’ve seen <code>%timeit</code>, <code>!ls</code>, and <code>%%bash</code> in other people’s notebooks and want to know what the percent signs and exclamation marks do.</li>
<li>Your notebook file has grown to tens of megabytes, and nobody (including Git) can make sense of what changed in it.</li>
<li>A cell has been running for ten minutes, and you can’t tell whether it’s working, stuck, or just slow, or which part of your code is to blame.</li>
<li>Your course hands out Google Colab links, and a file you saved there yesterday is gone today.</li>
</ul>
</section>
<section id="running-theme-notebooks-are-documents-and-programs" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="running-theme-notebooks-are-documents-and-programs">Running theme: notebooks are documents <em>and</em> programs</h2>
<p>A good notebook reads like a report and runs like a program, from top to bottom, on someone else’s computer; most of this chapter is about keeping both of those true at once.</p>
</section>
<section id="what-jupyter-is-doing" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="what-jupyter-is-doing"><span class="header-section-number">16.1</span> What Jupyter is doing</h2>
<p>Most people learn Jupyter by clicking around, and that works fine until something breaks. Then it helps a lot to know what’s actually running, because every confusing Jupyter problem is really a question about one of three pieces.</p>
<p>First, the two names. <a href="https://jupyterlab.readthedocs.io/en/stable/user/interface.html"><strong>JupyterLab</strong></a> is the environment most courses use now: a file browser down the left, notebooks open as tabs, and terminals and text files alongside them. <strong>Jupyter Notebook</strong> is the original, simpler interface, with one notebook per browser tab and a separate page listing your files; its current version, <a href="https://jupyter-notebook.readthedocs.io/en/latest/notebook_7_features.html">Notebook 7</a>, borrows many of JupyterLab’s features. Both are the same idea, a <a href="https://en.wikipedia.org/wiki/Notebook_interface">notebook interface</a>, running on the same machinery, so everything below applies to either.</p>
<p>That machinery has three parts. The <strong>server</strong> is the program you start when you type <code>jupyter lab</code> in a terminal. It keeps running in that terminal window, listening at an address on your own computer (usually <code>http://localhost:8888</code>, where <code>localhost</code> means “this machine”). The <strong>browser tab</strong> is only a window onto the server: it’s where you edit cells and see results, but it doesn’t run anything itself. And the <a href="../chapters/appendix-glossary.html#term-kernel"><strong>kernel</strong></a> is a separate process that actually runs your code. For a Python notebook, it’s a Python interpreter; kernels exist for R, Julia, and dozens of other languages too. When you press Shift+Enter, the code travels down the chain and the result comes back up:</p>
<pre class="text"><code>You type in a cell  →  browser  →  Jupyter server  →  kernel  →  result back up the chain</code></pre>
<p>The kernel is the piece that surprises people, because <strong>it remembers everything</strong>. It works like the Python prompt you get by typing <code>python</code> in a terminal (a <a href="https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop">read–eval–print loop</a>, or <a href="../chapters/appendix-glossary.html#term-repl">REPL</a>): when a cell runs <code>df = pd.read_csv("data.csv")</code>, <code>df</code> lives in the kernel’s memory until the kernel restarts, whether or not that cell is still on the page. Run cells out of order, redefine a variable, or delete a cell after running it, and what’s on screen no longer matches what’s in memory. People call this <strong>hidden state</strong>, and it’s why “it works in my notebook” so often means “it works with whatever my kernel happens to remember right now.” The only way to be sure a notebook is correct is to restart the kernel and run every cell from the top, a habit that comes up again and again below.</p>
</section>
<section id="launching-jupyter-the-right-way" class="level2 page-columns page-full" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="launching-jupyter-the-right-way"><span class="header-section-number">16.2</span> Launching Jupyter the right way</h2>
<p>The most common Jupyter complaint, by a long way, is some version of “my files aren’t there.” It nearly always comes down to two facts nobody mentions when you install Jupyter. <strong>The folder you start Jupyter from becomes the top of its file browser:</strong> you can open anything inside that folder and nothing above it. And <strong>each notebook’s code runs in the folder where the notebook file is saved</strong> (its <a href="https://en.wikipedia.org/wiki/Working_directory">working directory</a>), which is where relative paths like <code>data/raw/sales.csv</code> are looked up.</p>
<p>The first fact tells you how to start. Open a terminal, go to your project’s folder, activate its environment (see <a href="virtual-environments.html" class="quarto-xref"><span>Chapter 15</span></a>), and only then start the server:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ~/Courses/INFO-3010/Project          <span class="co"># 1. go to the project root</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate                <span class="co"># 2. activate the project's environment</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="ex">jupyter</span> lab                              <span class="co"># 3. start the server</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>cd</code> decides what the file browser shows. Activating the environment means Jupyter runs with your project’s Python and packages rather than whatever Python happens to be first on your system. And <code>jupyter lab</code> (or <code>jupyter notebook</code>, for the classic interface) starts the server and opens a browser tab. The file browser should now show your project, as in <a href="#fig-jupyterlab-overview" class="quarto-xref">Figure&nbsp;<span>16.1</span></a>: <code>data/</code>, <code>notebooks/</code>, <code>src/</code>, and the README. If it shows something else, stop and start again from the right folder. JupyterLab’s guide to <a href="https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html">starting JupyterLab</a> covers the options.</p>
<div id="fig-jupyterlab-overview" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="Screenshot of JupyterLab. The file browser on the left is at the project root and lists the folders data, notebooks, and src, and a README.md file. The main area has one tab, explore.ipynb: a heading, Weekly sales; a code cell that imports pandas, reads ../data/raw/sales.csv, and calls df.head(); and the first five rows of the table. At the notebook's top right, the kernel indicator reads Python 3 (ipykernel); the status bar says Idle.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-jupyterlab-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="../graphics/jupyter/jupyterlab-overview.png" class="img-fluid figure-img column-page-inset-right" alt="Screenshot of JupyterLab. The file browser on the left is at the project root and lists the folders data, notebooks, and src, and a README.md file. The main area has one tab, explore.ipynb: a heading, Weekly sales; a code cell that imports pandas, reads ../data/raw/sales.csv, and calls df.head(); and the first five rows of the table. At the notebook's top right, the kernel indicator reads Python 3 (ipykernel); the status bar says Idle.">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-jupyterlab-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.1: JupyterLab 4.6 just after <code>jupyter lab</code>, in September 2026. The file browser on the left shows the project root, because that is where the server was started; the notebook opens as a tab in the centre; and the kernel indicator at the top right names the kernel the notebook runs on, <code>Python 3 (ipykernel)</code>.
</figcaption>
</figure>
</div>
<p>Now the second fact, which catches almost everyone. Starting from the project root does <em>not</em> make the project root your notebook’s working directory: JupyterLab starts each notebook’s kernel in the folder where the notebook is saved. The notebook in <a href="#fig-jupyterlab-overview" class="quarto-xref">Figure&nbsp;<span>16.1</span></a> lives in <code>notebooks/</code>, so its code runs in <code>notebooks/</code>, and that’s why it reads <code>../data/raw/sales.csv</code> (<code>..</code> means “the folder above”) rather than <code>data/raw/sales.csv</code>. You can see it for yourself with <a href="https://docs.python.org/3/library/os.html#os.getcwd"><code>os.getcwd()</code></a>, which prints where the kernel is working:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(os.getcwd())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>/Users/you/Courses/INFO-3010/Project/notebooks</code></pre>
<p>Run the same line in a terminal at the project root and you’ll get a different answer. That’s the first thing to check whenever a path misbehaves. The same goes for imports: <code>from src.cleaning import clean_sales</code> fails in a notebook saved in <code>notebooks/</code>, because Python looks for <code>src</code> in the notebook’s folder. Paths starting with <code>../</code> are fine for quick work, but they break when the notebook moves, and they don’t match the paths a script uses. <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a> shows the dependable fix for both: make your code an installable package (<code>python -m pip install -e .</code>), and build every path from one project-root anchor, so <code>from sales.paths import DATA_RAW</code> works the same in every notebook and script.</p>
<section id="when-your-files-arent-there" class="level3">
<h3 class="anchored" data-anchor-id="when-your-files-arent-there">When your files aren’t there</h3>
<p>When JupyterLab opens on the wrong files, the server is almost always running somewhere other than you think. There are three usual ways to get there: you started it from your home folder or <code>Downloads</code> instead of the project; you have two servers running, and the browser tab you’re looking at belongs to an old one; or you started it with the wrong environment active, so the files look right but the packages don’t.</p>
<p><strong>Stop the server.</strong> Go back to the terminal window where it’s running and press <code>Ctrl+C</code> twice (the first asks whether you’re sure; the second skips the question). Close the browser tab too, so you don’t wander back to it.</p>
<p><strong>Go to the right folder and check.</strong> <code>cd</code> into the project and run <code>pwd</code> to confirm where you are before going any further.</p>
<p><strong>Activate the environment and start again</strong> with <code>jupyter lab</code>. If you can’t start from the folder itself, <code>jupyter lab --notebook-dir=path/to/project</code> sets the file browser’s top folder explicitly.</p>
<p>If the wrong files still appear, look for a server you forgot about. <code>jupyter server list</code> shows every server running on your computer and the folder each one is serving:</p>
<pre class="text"><code>$ jupyter server list
Currently running servers:
http://localhost:8888/?token=... :: /Users/you/Downloads</code></pre>
<p>Stop the stray one from its own terminal window, or close that window. The <a href="https://jupyterlab.readthedocs.io/en/stable/user/files.html">file browser section</a> of JupyterLab’s guide explains what it can and can’t reach.</p>
</section>
</section>
<section id="cells-and-running-them" class="level2 page-columns page-full" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="cells-and-running-them"><span class="header-section-number">16.3</span> Cells and running them</h2>
<section id="cell-types" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="cell-types">Cell types</h3>
<p>Every cell has a type, and there are only three. A <strong>code cell</strong> holds Python (or whatever language the kernel speaks) and sends it to the kernel when you run it. Anything the code prints appears below the cell, and so does the value of the cell’s last line, which is why a cell ending in <code>df.head()</code> shows a table without any <code>print</code>. A <strong>Markdown cell</strong> holds prose written in <a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a>: running it turns <code># Heading</code> into a heading, <code>*this*</code> into italics, and <code>$x^2$</code> into typeset math. Markdown cells are what turn a notebook into a document, and <a href="#fig-jupyter-cell-types" class="quarto-xref">Figure&nbsp;<span>16.2</span></a> shows one of each. A <strong>raw cell</strong> is passed through untouched, for tools that convert notebooks into other formats; you’ll rarely need one, so leave them alone unless a tool asks for one.</p>
<div id="fig-jupyter-cell-types" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="Two notebook cells. The first is a code cell labelled [1]: import pandas as pd, then df = pd.read_csv, and df.head(). Under it, output [1] is a table with columns date, store, product, units, and price and rows 0 to 4, all dated 2026-09-01, from the Pearl St and University Hill stores. The second cell is rendered Markdown: a heading, What to check next, and a sentence that ends with the word revenue in bold and units * price in code.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-jupyter-cell-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../graphics/jupyter/jupyter-cell-types.png" class="img-fluid figure-img" alt="Two notebook cells. The first is a code cell labelled [1]: import pandas as pd, then df = pd.read_csv, and df.head(). Under it, output [1] is a table with columns date, store, product, units, and price and rows 0 to 4, all dated 2026-09-01, from the Pearl St and University Hill stores. The second cell is rendered Markdown: a heading, What to check next, and a sentence that ends with the word revenue in bold and units * price in code.">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-jupyter-cell-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.2: A code cell and a Markdown cell in JupyterLab 4.6, in September 2026. The code cell ran <code>df.head()</code>, and its output, the first five rows of the table, appears beneath it with the same <code>[1]</code> label. The Markdown cell below has been run too, so it shows a formatted heading and paragraph instead of its source.
</figcaption>
</figure>
</div>
<pre class="text"><code>[code cell]     → sent to kernel → produces output below the cell
[markdown cell] → rendered as HTML → produces formatted text below
[raw cell]      → passed through untouched (rarely needed)</code></pre>
<p>To change a cell’s type, use the dropdown in the notebook’s toolbar, or press <code>Esc</code> to leave the cell’s text (Jupyter calls this <em>command mode</em>) and then <code>Y</code> for code, <code>M</code> for Markdown, or <code>R</code> for raw. JupyterLab’s <a href="https://jupyterlab.readthedocs.io/en/stable/user/notebook.html">notebook guide</a> walks through the rest of the interface.</p>
</section>
<section id="running-cells-and-stopping-them" class="level3">
<h3 class="anchored" data-anchor-id="running-cells-and-stopping-them">Running cells, and stopping them</h3>
<p>There are three ways to run a cell, and each suits a different moment. <code>Shift + Enter</code> runs the cell and moves to the next one, which is what you want when you’re working down the notebook. <code>Ctrl + Enter</code> (<code>Cmd + Enter</code> on a Mac) runs it and stays put, for when you’re tweaking one cell over and over. <code>Alt + Enter</code> runs it and adds a fresh empty cell below. The <em>Run</em> menu can also run everything above the current cell, or the current cell and everything below it.</p>
<pre class="text"><code>Shift + Enter  → run and advance (default)
Ctrl + Enter   → run and stay (iteration)
Alt + Enter    → run and insert new cell below

Menu: Run → Run All Cells                    (from the top)
Menu: Run → Run All Above Selected Cell      (up to the current cell)
Menu: Kernel → Restart Kernel and Run All Cells  (the reproducibility check)</code></pre>
<p>When a cell runs too long, there are two levels of stopping it, and it’s worth knowing the difference before you need it. <strong>Interrupt</strong> (the square stop button, or <code>I</code>, <code>I</code> in command mode) cancels the cell that’s running and keeps the kernel, so every variable you built up is still there. <strong>Restart</strong> (the circular arrow, or <code>0</code>, <code>0</code> in command mode) throws the kernel away and starts a new one, empty. Always interrupt first; restart only if interrupting does nothing, and then run the cells you need again from the top.</p>
<p>The small number in square brackets beside each code cell, like <code>[7]</code>, is the most useful diagnostic on the screen. It’s the <strong>execution count</strong>: it goes up by one every time <em>any</em> cell runs, so it records the order things actually happened in. Down a notebook that was run from the top, the numbers climb in order, <code>[1] [2] [3] [4]</code>, and the outputs are what the code produces on a fresh run. If they read <code>[3] [1] [7] [2]</code>, the cells were run out of order, and the outputs may be a collage of states that never existed at the same moment. Before you trust a notebook, yours or anyone else’s, glance down the left edge and check that the numbers climb. (The same number shows up in tracebacks as <code>In[7]</code>, as <a href="tracebacks.html" class="quarto-xref"><span>Chapter 7</span></a> explains.)</p>
</section>
<section id="organizing-cells" class="level3">
<h3 class="anchored" data-anchor-id="organizing-cells">Organizing cells</h3>
<p>A notebook is a document, so its order should tell the story you’re telling. When a side experiment turns out to matter, move it into the main line; when a helper calculation clutters the flow, move it up or out. Drag cells in JupyterLab, or select one and press <code>Ctrl + Shift + Up</code> or <code>Down</code> to move it. Every command, with its keyboard shortcut if it has one, is also in the <a href="https://jupyterlab.readthedocs.io/en/stable/user/commands.html">command palette</a>.</p>
<p>As a notebook grows, <strong>Markdown headings</strong> do more for it than anything else. A Markdown cell reading <code>## Cleaning decisions</code> becomes a heading in the notebook and an entry in JupyterLab’s <a href="https://jupyterlab.readthedocs.io/en/stable/user/toc.html">table of contents</a> panel, so even five headings turn a hundred-cell scroll into something you can jump around in, and a reader can see its structure at a glance.</p>
<p>One ordering rule is worth treating as fixed: <strong>imports and setup go at the top</strong>. Start every notebook with its imports, a cell of paths and settings, and a quick check that the environment is right (the “smoke test” in <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a>), and put nothing before them. An import buried halfway down means anyone who runs from the top hits a <code>NameError</code> before reaching it.</p>
</section>
</section>
<section id="keeping-notebooks-small" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="keeping-notebooks-small"><span class="header-section-number">16.4</span> Keeping notebooks small</h2>
<p>A notebook file is <a href="https://en.wikipedia.org/wiki/JSON">JSON</a>, a text format, and every output is saved inside it along with the code. Print ten thousand rows and the text of ten thousand rows goes into the file; draw a plot and the image is stored in it as a long string of encoded text. Run that plotting cell twenty times while you tweak colors, keep the outputs of an old experiment, and a notebook can reach tens of megabytes. Then it’s slow to open, painful to scroll, and impossible to review: a Git diff of a big notebook is mostly pages of encoded images.</p>
<p><strong>Summarize instead of dumping.</strong> Don’t end a cell with <code>df</code> to see the whole table; end it with something that shows just enough:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Avoid: dumps the entire dataset into the notebook output</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Prefer: just enough to see what's there</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>df.head()</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>df.shape          <span class="co"># (rows, cols) — almost always what you want</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>df.describe()     <span class="co"># summary statistics</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The same goes for everything else: print <code>len(files)</code> and <code>files[:5]</code>, not a list of every file in a folder.</p>
<p><strong>Save what matters to files.</strong> A figure you’ll use in a report belongs in <code>figures/</code>, written with <a href="https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.savefig.html"><code>savefig</code></a>, and a cleaned dataset belongs in <code>data/processed/</code>. The notebook’s job is to <em>make</em> those files, not to <em>be</em> them:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Avoid: 4 MB PNG stored inside the notebook file</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Prefer: saved to a file, referenced from markdown</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ax.scatter(x, y)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>fig.savefig(<span class="st">"../figures/scatter-by-region.png"</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">"tight"</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>plt.close(fig)    <span class="co"># prevents the figure from also appearing in the cell output</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>A Markdown cell can then show the saved file (the path is relative to the notebook, so from <code>notebooks/</code> it starts with <code>../</code>):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="al">![Scatter by region.](../figures/scatter-by-region.png)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Clear outputs and rerun before you commit or share.</strong> <em>Edit → Clear Outputs of All Cells</em> empties every output, and <em>Kernel → Restart Kernel and Run All Cells</em> then fills them in again from a clean run. The file you commit is smaller, holds one copy of each plot instead of twenty, and shows exactly what the current code produces. From a terminal, <code>jupyter nbconvert --clear-output --inplace notebook.ipynb</code> does the clearing, and the nbstripout tool in Further reading can do it automatically every time you commit.</p>
</section>
<section id="shell-commands-and-magics" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="shell-commands-and-magics"><span class="header-section-number">16.5</span> Shell commands and magics</h2>
<p>Sooner or later you’ll want to do a bit of housekeeping without leaving the notebook: check that <code>data/raw/sales.csv</code> actually arrived before reading it, see what an earlier step wrote to <code>data/processed/</code>, download a file, or run a command-line tool like <code>git</code>. You could switch to a terminal, but running the check in the notebook keeps it next to the code that depends on it. Jupyter gives you two ways, and they look different on purpose. (Shell commands start in the notebook’s folder too, so the examples below assume a notebook saved at the project root; from <code>notebooks/</code>, the paths start with <code>../</code>.)</p>
<section id="bangs-and-magics" class="level3">
<h3 class="anchored" data-anchor-id="bangs-and-magics">Bangs and magics</h3>
<p>A line that starts with an exclamation mark, a <strong>bang</strong>, is handed to your computer’s shell, and whatever it prints appears below the cell. You can mix bang lines with Python in the same cell:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A mix of Python and shell in one cell</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>ls <span class="op">-</span>lh data<span class="op">/</span>raw<span class="op">/</span>           <span class="co"># shell: list the raw data folder</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/raw/sales.csv"</span>)   <span class="co"># Python: load it</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wc <span class="op">-</span>l data<span class="op">/</span>raw<span class="op">/</span>sales.csv   <span class="co"># shell: how many lines did we just read?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Magics</strong> start with <code>%</code> (for one line) or <code>%%</code> (for a whole cell), and they’re commands that IPython, the Python kernel, understands itself rather than passing to the shell. Line magics each do one job, such as <code>%cd</code> to change the working directory or <code>%env</code> to read an <a href="https://en.wikipedia.org/wiki/Environment_variable">environment variable</a>. Cell magics change what the whole cell does: <code>%%time</code> times it, and <code>%%bash</code> runs the whole cell as a Bash script, which is tidier than a <code>!</code> on every line when you need a loop:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>cd <span class="op">~/</span>Courses<span class="op">/</span>INFO<span class="op">-</span><span class="dv">3010</span><span class="op">/</span>Project    <span class="co"># change the kernel's working directory</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pwd                                 <span class="co"># print it</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>env API_URL                         <span class="co"># show the value of an env var</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="ex">%%bash</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Whole cell runs as a bash script; no ! prefixes needed</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> data/raw/<span class="pp">*</span>.csv<span class="kw">;</span> <span class="cf">do</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="bu">echo</span> <span class="st">"</span><span class="va">$f</span><span class="st">: </span><span class="va">$(</span><span class="fu">wc</span> <span class="at">-l</span> <span class="op">&lt;</span> <span class="st">"</span><span class="va">$f</span><span class="st">"</span><span class="va">)</span><span class="st"> lines"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>data/raw/sales.csv: 1201 lines
data/raw/survey.csv: 3 lines</code></pre>
<p>The difference matters when you share notebooks across operating systems. A bang line runs in whatever shell your computer has, so <code>!ls</code> works on a Mac or Linux and fails in Windows’ Command Prompt, and <a href="https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-bash"><code>%%bash</code></a> needs Bash installed. Magics that IPython implements itself, such as <code>%cd</code> and <code>%pwd</code>, behave the same everywhere, and <code>%ls</code> quietly runs <code>dir</code> on Windows. IPython’s guide to <a href="https://ipython.readthedocs.io/en/stable/interactive/reference.html#system-shell-access">system shell access</a> has the details.</p>
</section>
<section id="magics-worth-knowing" class="level3">
<h3 class="anchored" data-anchor-id="magics-worth-knowing">Magics worth knowing</h3>
<p>A handful of magics cover nearly everything you’ll need, and it’s worth knowing them by name so you recognize them in other people’s notebooks. The full list is in IPython’s <a href="https://ipython.readthedocs.io/en/stable/interactive/magics.html">built-in magics reference</a>, or type <code>%lsmagic</code> in a cell.</p>
<ul>
<li><strong><code>%pwd</code></strong> prints the kernel’s working directory: the first thing to run when you suspect a path problem.</li>
<li><strong><code>%cd &lt;path&gt;</code></strong> changes it. Use it sparingly: a notebook that moves itself around behaves differently depending on which cells you’ve run, and running <code>%cd ..</code> twice lands you one folder too high.</li>
<li><strong><code>%ls</code></strong> lists the current folder.</li>
<li><strong><code>%env VAR</code></strong> prints an environment variable, and <code>%env VAR=value</code> sets one for this kernel.</li>
<li><strong><code>%pip install &lt;package&gt;</code></strong> installs a package into the environment the kernel is running in, which is not always the one your terminal is using (see “Wrong kernel” below).</li>
<li><strong><code>%time statement</code></strong> runs one line and prints how long it took; <strong><code>%%time</code></strong> at the top of a cell times the whole cell.</li>
<li><strong><code>%timeit</code></strong> and <strong><code>%%timeit</code></strong> run a small piece of code many times and report the average, for comparing two ways of doing something (see “Finding what’s slow” below).</li>
<li><strong><code>%load_ext autoreload</code></strong> then <strong><code>%autoreload 2</code></strong> makes the kernel reload your own modules in <code>src/</code> when you edit them, so you don’t have to restart (<a href="https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html">autoreload docs</a>; <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a> shows the workflow).</li>
<li><strong><code>%matplotlib inline</code></strong> draws matplotlib plots inside the notebook. Current Jupyter does this by default, but you’ll still see the line at the top of many notebooks.</li>
</ul>
<p>Put together, a typical first cell looks like this:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A typical top-of-notebook setup using several magics</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>load_ext autoreload</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>autoreload <span class="dv">2</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sales.cleaning <span class="im">import</span> clean_sales    <span class="co"># your package, installed with python -m pip install -e .</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sales.paths <span class="im">import</span> DATA_RAW</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>time df <span class="op">=</span> pd.read_csv(DATA_RAW <span class="op">/</span> <span class="st">"sales.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>CPU times: user 3.55 ms, sys: 35.8 ms, total: 39.3 ms
Wall time: 39.6 ms</code></pre>
<p>(The <code>sales</code> package and its <code>paths</code> module are the layout <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a> builds.)</p>
</section>
<section id="using-the-shell-safely" class="level3">
<h3 class="anchored" data-anchor-id="using-the-shell-safely">Using the shell safely</h3>
<p>Shell commands in a notebook are easier to misuse than the same commands in a terminal. A notebook hides the context a terminal gives you (the prompt, the folder you’re in, the history scrolling above), and Run All will happily rerun a command you meant to run once. A few habits keep this safe.</p>
<p><strong>Look before you delete.</strong> <code>!rm data/processed/*.csv</code> in a cell is exactly as permanent as it is in a terminal, and easier to run by accident. Before any <code>rm</code>, <code>mv</code>, or <code>&gt;</code> redirect, run <code>!ls</code> with the same path or <a href="https://en.wikipedia.org/wiki/Glob_(programming)">glob pattern</a> to see exactly which files it will touch.</p>
<p><strong>Never use <code>sudo</code> in a notebook.</strong> If you find yourself wanting <code>!sudo apt install something</code>, switch to a terminal, install it there, and come back. A notebook is for analysis, not for changing your system.</p>
<p><strong>Never type a secret into a cell.</strong> The notebook file saves every cell’s contents, so an API token in a cell goes wherever the file goes: into Git, onto GitHub, into the email you attach it to. Keep secrets in environment variables or a <code>.env</code> file that Git ignores (see <a href="secrets.html" class="quarto-xref"><span>Chapter 34</span></a>), and refer to them by name:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BAD: token is now permanently recorded in the notebook file</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>curl <span class="op">-</span>H <span class="st">"Authorization: Bearer sk-abcdef1234"</span> https:<span class="op">//</span>api.example.com<span class="op">/</span>data</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># BETTER: token stays in the environment, never written to the notebook</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>curl <span class="op">-</span>H <span class="st">"Authorization: Bearer $API_TOKEN"</span> https:<span class="op">//</span>api.example.com<span class="op">/</span>data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One surprise in that second line: in a bang command, IPython replaces <code>$NAME</code> with a <em>Python</em> variable of that name if one exists, and only otherwise leaves it for the shell. If you’ve also written <code>API_TOKEN = "..."</code> in a cell, that value is what gets sent.</p>
<p><strong>Say what the command does.</strong> A Markdown cell above it reading “This downloads the October data into <code>data/raw/</code>” saves the next reader (often you) from puzzling over a <code>curl</code> line. And once you’ve written a command down, you have a record of it: that’s the real advantage over clicking through the same steps in a file manager every semester.</p>
</section>
</section>
<section id="writing-a-notebook-that-survives" class="level2" data-number="16.6">
<h2 data-number="16.6" class="anchored" data-anchor-id="writing-a-notebook-that-survives"><span class="header-section-number">16.6</span> Writing a notebook that survives</h2>
<section id="give-it-a-predictable-structure" class="level3">
<h3 class="anchored" data-anchor-id="give-it-a-predictable-structure">Give it a predictable structure</h3>
<p>A reader opening your notebook for the first time, including you in three weeks, should be able to tell from the first screen what it’s for, what it needs, and what it produces. The easiest way to guarantee that is to use the same skeleton every time:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># &lt;Title&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">One-paragraph</span><span class="ot"> purpose: what this notebook does and why it exists.</span><span class="dt">&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Setup</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Imports</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Paths and parameters</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Smoke test (cwd, python, key files)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data acquisition and provenance</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Where the data came from (URL, date, source)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>How it was downloaded</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cleaning and validation</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Filters applied (and why)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Validation checks (row counts, required columns, no nulls)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analysis</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>One subsection per question</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results and interpretation</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Plots, summary tables</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>One paragraph interpreting each</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Next steps / limitations</span></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>What you did not do</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Caveats the reader should know</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Each section earns its place. The <strong>purpose</strong> paragraph is often the difference between a notebook a collaborator understands and one they have to ask you about. <strong>Setup</strong> is where any failure to run on someone else’s computer will show up, and it shows up first, clearly, because this section runs first. <strong>Provenance</strong> answers “where did this data come from?”, a question with no good answer later if you didn’t write it down at the time. <strong>Validation</strong> catches the “wait, that shouldn’t be zero” moments while you can still fix them. <strong>Results</strong> is the story; without it, the notebook is a pile of calculations. Use the skeleton even for small notebooks: some sections will be two lines long, and the headings still orient the reader.</p>
</section>
<section id="write-the-prose" class="level3">
<h3 class="anchored" data-anchor-id="write-the-prose">Write the prose</h3>
<p>The feature that sets a notebook apart from a script is prose woven between the code, an idea much older than Jupyter called <a href="https://en.wikipedia.org/wiki/Literate_programming">literate programming</a>. A notebook only earns that feature if you write the prose: fifty code cells and no Markdown is a script with a confusing interface.</p>
<p>Use headings to break the notebook into sections, and before any cell that makes a decision (a filter, a join, a cutoff, a model choice), write a short paragraph saying <em>why</em> you did it this way and not another. Six months from now you won’t remember, and a fresh reader will want to know:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">## Filtering out cancelled orders</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>The raw data contains every order the system has seen, including</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>cancellations (which appear as a separate row with <span class="in">`status == "cancelled"`</span>).</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>For revenue analysis we want to exclude cancelled orders, because they</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>were refunded and no money actually changed hands. We keep them in</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="in">`data/raw/`</span> for completeness but drop them here.</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>active <span class="op">=</span> df[df[<span class="st">"status"</span>] <span class="op">!=</span> <span class="st">"cancelled"</span>]</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>Dropping cancellations removes about 4% of rows (12,104 of 302,811).</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Caption your plots and tables, too: a sentence before a figure saying what it shows, and ideally one after saying what to notice. A plot without a caption is decoration; with one, it’s evidence. The test of whether there’s enough prose is to imagine handing the notebook to someone who knows the subject but has never seen your data. If they could follow the argument without you sitting beside them, it’s enough.</p>
</section>
<section id="keep-it-reproducible" class="level3">
<h3 class="anchored" data-anchor-id="keep-it-reproducible">Keep it reproducible</h3>
<p>A reproducible notebook gives the same results every time it runs from a fresh kernel. That sounds obvious, and it’s surprisingly easy to drift away from, because the interface lets you run cells in any order, delete cells whose results you still depend on, and define things that never make it into any cell. A few habits keep the notebook honest.</p>
<p><strong>Run top to bottom, and prove it often.</strong> Never run a cell that depends on something further down, and every time you finish a real piece of work, not just before you hand it in, run <em>Kernel → Restart Kernel and Run All Cells</em>. If the notebook works interactively but fails after a restart, something it depends on exists only in the kernel’s memory, and it’s far better to find out now than on a grader’s computer (“Out-of-order execution” below shows what this looks like).</p>
<p><strong>Define everything in a cell that’s still there.</strong> A variable you typed into a cell and then deleted, like a quick <code>df2 = df.copy()</code>, lives on in this session and vanishes in the next. Every name the notebook uses should come from a cell that’s currently in it.</p>
<p><strong>Write a function instead of copying code.</strong> When the same block appears in two cells, the two copies will drift apart. Make it a function, in a cell near the top or in <code>src/</code>, and call it in both places.</p>
<p><strong>Keep paths inside the project.</strong> A notebook that reads <code>/Users/alex/Downloads/survey.csv</code> runs only on Alex’s laptop; one that reads <code>../data/raw/survey.csv</code>, or builds the path from a project-root anchor as <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a> shows, runs anywhere the project folder does. <a href="file-system.html" class="quarto-xref"><span>Chapter 10</span></a> explains relative and absolute paths in detail.</p>
<p><strong>Keep files in labeled folders:</strong> <code>data/raw/</code> for inputs, <code>data/processed/</code> for derived tables, <code>figures/</code> for plots, <code>reports/</code> for finished work. A notebook that writes everything to its own folder is hard to clean up and hard to check.</p>
</section>
<section id="record-the-environment" class="level3">
<h3 class="anchored" data-anchor-id="record-the-environment">Record the environment</h3>
<p>The code is only half of what determines a notebook’s results; the versions of Python and every package are the other half. pandas 3, for example, reads text columns as a new <code>str</code> type where pandas 2 used <code>object</code>, so the same notebook can print different results, or fail, depending on which version is installed. If you don’t record the versions, reproducing your results six months from now turns into archaeology. The minimum is to print the ones that matter near the top of the notebook:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys, platform</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd, numpy <span class="im">as</span> np</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"python:  "</span>, sys.version.split()[<span class="dv">0</span>])</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"platform:"</span>, platform.platform())</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"pandas:  "</span>, pd.__version__)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"numpy:   "</span>, np.__version__)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>python:   3.12.3
platform: Linux-6.18.44-fc-v37-x86_64-with-glibc2.39
pandas:   3.0.6
numpy:    2.5.3</code></pre>
<p>The fuller habit is an environment file in the project that pins every dependency (see <a href="virtual-environments.html" class="quarto-xref"><span>Chapter 15</span></a> and <a href="package-management.html" class="quarto-xref"><span>Chapter 14</span></a>): <code>environment.yml</code> for conda, or <code>requirements.txt</code> or <code>pyproject.toml</code> for pip. Commit it alongside the notebook, and add one line to the README saying how to recreate the environment from it. With the file and the code, anyone, including you on a new laptop, can get back to the same setup.</p>
</section>
</section>
<section id="notebook-pitfalls-and-how-to-prevent-them" class="level2" data-number="16.7">
<h2 data-number="16.7" class="anchored" data-anchor-id="notebook-pitfalls-and-how-to-prevent-them"><span class="header-section-number">16.7</span> Notebook pitfalls and how to prevent them</h2>
<section id="out-of-order-execution" class="level3">
<h3 class="anchored" data-anchor-id="out-of-order-execution">Out-of-order execution</h3>
<p>This is the classic notebook bug: everything works in your session and nothing works anywhere else. You ran the cells in whatever order you needed while exploring, got the answer, and closed the laptop. Next week, a run from the top fails, because one cell only ever worked thanks to a cell further down that you happened to have run first. It’s by far the most common reason a notebook “works on my machine” and nowhere else.</p>
<p>The execution counts give it away. Compare a healthy notebook with one that has a hidden-state bug:</p>
<pre class="text"><code># Cell execution counts in a healthy notebook
[1]  import pandas as pd
[2]  df = pd.read_csv("data/raw/sales.csv")
[3]  df["date"] = pd.to_datetime(df["date"])
[4]  df["month"] = df["date"].dt.month
[5]  df.groupby("month")["units"].sum()

# Cell execution counts in a notebook with a hidden-state bug
[1]  import pandas as pd
[2]  df = pd.read_csv("data/raw/sales.csv")
[5]  df["month"] = df["date"].dt.month     # needed the cell below it first
[4]  df["date"] = pd.to_datetime(df["date"])
[6]  df.groupby("month")["units"].sum()</code></pre>
<p>In the second notebook, the cell that converts dates sits <em>below</em> the cell that uses them, and it worked only because the dates cell ran first (count <code>[4]</code> before <code>[5]</code>). The missing <code>[3]</code> is a cell that ran and was later deleted, and whatever it did is still in memory. Restart and run all, and the third cell stops with <code>AttributeError: Can only use .dt accessor with datetimelike values</code>, because on a fresh run the dates are still text. The cure is the ritual from above: <em>Restart Kernel and Run All Cells</em> after every chunk of work, then fix the order while you still remember why it matters.</p>
</section>
<section id="wrong-kernel-wrong-environment" class="level3">
<h3 class="anchored" data-anchor-id="wrong-kernel-wrong-environment">Wrong kernel, wrong environment</h3>
<p>This one has a different symptom. You <code>pip install pandas</code> in a terminal, go back to the notebook, and <code>import pandas</code> still says <code>ModuleNotFoundError</code>. Or the import works but a function is missing, or a warning appears that never did before. It’s all the same problem: <strong>the kernel is running a different Python from the one you installed into.</strong> Jupyter can have many Python environments registered as kernels, and it’s easy to pick the wrong one, especially after creating a new environment or opening an old notebook.</p>
<p>Check, don’t guess. The kernel’s name is at the top right of the notebook (<code>Python 3 (ipykernel)</code> in <a href="#fig-jupyterlab-overview" class="quarto-xref">Figure&nbsp;<span>16.1</span></a>), and one line in a cell tells you which Python it really is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sys.executable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><a href="https://docs.python.org/3/library/sys.html#sys.executable"><code>sys.executable</code></a> should point into your project’s <code>.venv/</code>. If it doesn’t, click the kernel name (or use <em>Kernel → Change Kernel</em>) and pick the right one. If your environment isn’t in the list at all, register it once, with the environment activated in a terminal:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Register the project's venv as a named kernel</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> source .venv/bin/activate</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="ex">.venv</span><span class="kw">)</span> <span class="ex">$</span> python <span class="at">-m</span> pip install ipykernel</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="ex">.venv</span><span class="kw">)</span> <span class="ex">$</span> python <span class="at">-m</span> ipykernel install <span class="at">--user</span> <span class="dt">\</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">--name</span><span class="op">=</span>info3010 <span class="at">--display-name</span><span class="op">=</span><span class="st">"INFO 3010 (venv)"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>python -m pip</code> in the middle is on purpose. It <a href="https://pip.pypa.io/en/stable/user_guide/#running-pip">installs into whichever Python <code>python</code> is</a>, so with the venv active, ipykernel can’t land anywhere else. Plain <code>pip</code> is a separate command that can belong to a different Python, and that mismatch is how this whole problem starts.</p>
<p>Reload JupyterLab and “INFO 3010 (venv)” appears in the kernel list, which is much easier to pick out than a row of identical “Python 3 (ipykernel)” entries. <code>jupyter kernelspec list</code> shows every kernel you’ve registered, and IPython’s <a href="https://ipython.readthedocs.io/en/stable/install/kernel_install.html">kernel installation guide</a> covers the details. And if you just need one package in the kernel you’re already using, <code>%pip install pandas</code> in a cell installs it into exactly that environment.</p>
</section>
<section id="file-not-found" class="level3">
<h3 class="anchored" data-anchor-id="file-not-found">File not found</h3>
<p>The third pitfall is the <code>FileNotFoundError</code> that makes no sense, because the file is right there. You can see <code>data/raw/sales.csv</code> in the file browser, and still <code>pd.read_csv("data/raw/sales.csv")</code> fails:</p>
<pre class="text"><code>FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/sales.csv'</code></pre>
<p>The file browser shows paths from where you <em>started</em> Jupyter; your code looks for them from where the <em>notebook is saved</em>. A notebook in <code>notebooks/</code> is looking for <code>notebooks/data/raw/sales.csv</code>, which doesn’t exist. Three lines tell you exactly where it looked, using <a href="https://docs.python.org/3/library/pathlib.html"><code>pathlib</code></a>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cwd:    "</span>, os.getcwd())</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"exists: "</span>, Path(<span class="st">"data/raw/sales.csv"</span>).exists())</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"absolute:"</span>, Path(<span class="st">"data/raw/sales.csv"</span>).resolve())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>cwd:     /Users/you/Courses/INFO-3010/Project/notebooks
exists:  False
absolute: /Users/you/Courses/INFO-3010/Project/notebooks/data/raw/sales.csv</code></pre>
<p>Once you see the <code>absolute</code> path, the fix is clear: write the path from the notebook’s folder (<code>../data/raw/sales.csv</code>), or, better for a project you’ll keep, build it from a project-root anchor such as <code>DATA_RAW / "sales.csv"</code> (see <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a>). The same error appears after you move a notebook into another folder, since its working directory moves with it. <a href="file-system.html" class="quarto-xref"><span>Chapter 10</span></a> covers relative paths in general.</p>
</section>
<section id="long-running-or-stuck-cells" class="level3">
<h3 class="anchored" data-anchor-id="long-running-or-stuck-cells">Long-running or stuck cells</h3>
<p>Sooner or later a cell takes longer than you expected: a data load that should take ten seconds is still going after two minutes. The first question is whether it’s <em>slow</em> (doing the work, just taking a while) or <em>stuck</em> (waiting on something that will never finish, like a network call that hung or a loop that never ends). Interrupt it first; the kernel keeps your variables. Interrupting can take a moment if the kernel is in the middle of a long operation, since it responds between steps. If interrupting does nothing, restart the kernel, which loses everything in memory.</p>
<p>Better still, make a long cell show its progress. For a loop, <a href="https://tqdm.github.io/">tqdm</a> draws a progress bar, so you can see whether it’s moving and how long is left:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm <span class="im">import</span> tqdm</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> tqdm(df.itertuples(), total<span class="op">=</span><span class="bu">len</span>(df)):</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    process(row)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>For a single slow step, put <code>%%time</code> at the top of the cell:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>time</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> expensive_function(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>With a progress bar or a timer, “is it stuck?” becomes “how fast is it going?”, which is a much more useful question. And genuinely expensive work doesn’t belong in a notebook at all. A model that takes four hours to train should be a script that saves the model to disk, with a notebook that loads the result and looks at it; that way one wrong keystroke doesn’t cost you the whole run.</p>
</section>
</section>
<section id="finding-whats-slow-measure-then-profile" class="level2" data-number="16.8">
<h2 data-number="16.8" class="anchored" data-anchor-id="finding-whats-slow-measure-then-profile"><span class="header-section-number">16.8</span> Finding what’s slow: measure, then profile</h2>
<p>A slow notebook tempts you to start rewriting whatever looks inefficient. Resist it: the slow part is rarely where you’d guess. The three-step pipeline below takes a minute on 200,000 rows of sales data, and the step that looks most suspicious isn’t the one to blame. The method is the same one <a href="debugging.html" class="quarto-xref"><span>Chapter 6</span></a> teaches for bugs: measure first, change one thing, measure again.</p>
<section id="time-one-step-timeit" class="level3">
<h3 class="anchored" data-anchor-id="time-one-step-timeit">Time one step: <code>%timeit</code></h3>
<p><a href="https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit"><code>%timeit</code></a> runs a line many times and reports how long it takes on average, which makes it the tool for comparing two ways of doing the same step. Here are two ways to turn a <code>revenue</code> column of strings like <code>"$3.95"</code> into numbers:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>timeit df[<span class="st">"revenue"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> s: <span class="bu">float</span>(s.replace(<span class="st">"$"</span>, <span class="st">""</span>)))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>timeit df[<span class="st">"revenue"</span>].<span class="bu">str</span>.replace(<span class="st">"$"</span>, <span class="st">""</span>).astype(<span class="bu">float</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>87.7 ms ± 2.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
44.7 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)</code></pre>
<p>Read each line as “the average time for one run, plus or minus how much it varied”: <code>%timeit</code> ran the line in 7 batches of 10 and averaged them. The second version is twice as fast, and it saves 43 milliseconds, which is not worth an afternoon. Whether a speedup matters depends on how much of the whole run the step takes (the idea behind <a href="https://en.wikipedia.org/wiki/Amdahl%27s_law">Amdahl’s law</a>), and for that you need a profiler.</p>
</section>
<section id="find-where-the-time-goes-a-profiler" class="level3">
<h3 class="anchored" data-anchor-id="find-where-the-time-goes-a-profiler">Find where the time goes: a profiler</h3>
<p>A <a href="https://en.wikipedia.org/wiki/Profiling_(computer_programming)"><strong>profiler</strong></a> runs your program and records how long each function takes, including everything the function calls. Python comes with one, <a href="https://docs.python.org/3/library/profile.html"><code>cProfile</code></a>. Here is the whole pipeline as a script, <code>clean.py</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> parse_revenue(df):</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"revenue"</span>] <span class="op">=</span> df[<span class="st">"revenue"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> s: <span class="bu">float</span>(s.replace(<span class="st">"$"</span>, <span class="st">""</span>)))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_month(df):</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"month"</span>] <span class="op">=</span> df[<span class="st">"date"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> d: pd.to_datetime(d).strftime(<span class="st">"%Y-%m"</span>))</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> monthly_totals(df):</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df.groupby([<span class="st">"month"</span>, <span class="st">"store"</span>])[<span class="st">"revenue"</span>].<span class="bu">sum</span>()</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> main():</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.read_csv(<span class="st">"sales.csv"</span>)</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> parse_revenue(df)</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> add_month(df)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(monthly_totals(df).head(<span class="dv">3</span>))</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>    main()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Run it under the profiler, sorted by cumulative time, and look for the lines that name your own file:</p>
<pre class="text"><code>$ python -m cProfile -s cumulative clean.py
...
         151048296 function calls (151035047 primitive calls) in 123.508 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  122.930  122.930 clean.py:18(main)
        1    0.000    0.000  122.493  122.493 clean.py:9(add_month)
   200000    2.419    0.000  122.189    0.001 clean.py:10(&lt;lambda&gt;)
        1    0.000    0.000    0.217    0.217 readers.py:349(read_csv)
        1    0.000    0.000    0.190    0.190 clean.py:4(parse_revenue)
   200000    0.078    0.000    0.100    0.000 clean.py:5(&lt;lambda&gt;)
        1    0.000    0.000    0.027    0.027 clean.py:14(monthly_totals)</code></pre>
<p>(The full table lists hundreds of pandas’ own functions; these are the lines for <code>clean.py</code> and <code>read_csv</code>.) <code>cumtime</code> is the time spent in a function and everything it called, and <code>ncalls</code> is how many times it was called. The answer is plain: <code>add_month</code> takes 122 of the 123 seconds, and its <code>lambda</code> ran 200,000 times, once per row, each time calling <code>pd.to_datetime</code> on a single date. <code>parse_revenue</code>, which also uses <code>apply</code> on every row, takes 0.19 seconds. Rewriting it first, as the <code>%timeit</code> comparison tempted, would have saved almost nothing.</p>
<p>Profiling slows a program down (this run took 123 seconds under <code>cProfile</code> and 62 without it), but the proportions hold, and the proportions are what you need. In a notebook, <a href="https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-prun"><code>%prun -s cumulative main()</code></a> gives the same table without leaving the cell. When a profile points at one function and you want to know which <em>line</em> inside it is slow, the <a href="https://kernprof.readthedocs.io/en/latest/">line_profiler</a> package (installed separately) adds a <code>%lprun</code> magic: after <code>%load_ext line_profiler</code>, <code>%lprun -f main main()</code> times each line of <code>main</code> and shows the share of the total each one took. On this script, the <code>add_month(df)</code> line takes about 98% of it.</p>
</section>
<section id="fix-the-biggest-cost-then-measure-again" class="level3">
<h3 class="anchored" data-anchor-id="fix-the-biggest-cost-then-measure-again">Fix the biggest cost, then measure again</h3>
<p>The fix for <code>add_month</code> is to hand pandas the whole column at once, so it parses every date in one call instead of 200,000:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_month(df):</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"month"</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">"date"</span>]).dt.strftime(<span class="st">"%Y-%m"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>With that change (and the same kind of change to <code>parse_revenue</code>), the script runs in 1.6 seconds instead of 62. <code>%timeit</code> shows where the difference comes from: the per-row version takes 300 ms for just 1,000 rows, about a minute for all 200,000, while the whole-column version does all 200,000 in 0.9 seconds.</p>
<p>Then measure again, from the top. Once the biggest cost is gone, something else is the biggest; if the program is now fast enough for what you need, stop.</p>
</section>
<section id="the-usual-suspects-in-pandas" class="level3">
<h3 class="anchored" data-anchor-id="the-usual-suspects-in-pandas">The usual suspects in pandas</h3>
<p>When a profile points at pandas code, the cause is usually one of these (pandas’ guide to <a href="https://pandas.pydata.org/docs/user_guide/enhancingperf.html">enhancing performance</a> goes further):</p>
<ul>
<li><strong>Row-by-row work:</strong> <code>apply</code> with a Python function, <code>iterrows()</code>, or a <code>for</code> loop over rows. Look for a method that works on the whole column: <code>.str</code> for text, <code>.dt</code> for dates, arithmetic and comparisons, <code>np.where</code> for if-else.</li>
<li><strong>Growing a DataFrame inside a loop.</strong> Each <code>pd.concat</code> copies everything built so far, so the loop gets slower as it goes. Collect plain Python rows in a list and build the DataFrame once at the end: for 5,000 rows, growing took 1.8 seconds and collecting took 3.7 milliseconds.</li>
<li><strong>Reading more than you need, or the same file over and over.</strong> Read only the columns you use, and save an expensive intermediate result to Parquet so the next run starts from it (see “Data bigger than memory” in <a href="data-file-formats.html" class="quarto-xref"><span>Chapter 20</span></a>).</li>
</ul>
<p>The timings here are from one computer, with pandas 3.0 in September 2026. Yours will differ; the order of the costs is what carries over.</p>
</section>
</section>
<section id="when-to-move-from-notebooks-to-scripts-and-back" class="level2" data-number="16.9">
<h2 data-number="16.9" class="anchored" data-anchor-id="when-to-move-from-notebooks-to-scripts-and-back"><span class="header-section-number">16.9</span> When to move from notebooks to scripts (and back)</h2>
<p>Notebooks and scripts are good at different things, and most real projects use both. <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a> covers scripts in full; this section is about where the boundary goes.</p>
<p>A notebook shines when the goal is <strong>exploring, explaining, or sharing results</strong>. You’re still figuring out what the data looks like, the question is still changing, you’re bouncing between a line of code and a plot, or the finished product is a written analysis someone will read: a short report, a homework submission, a briefing with figures. The value is in the explanation, and nothing else puts code, output, and prose together as well.</p>
<p>A script shines when the goal is <strong>running the same thing again</strong>, reliably, without you watching. The analysis has settled down and needs rerunning on new data; it has to happen on a schedule; it needs parameters, like a date range or a file path, that change between runs; or you want Git diffs you can actually read. Scripts are what run in scheduled jobs, in automated checks, and on remote servers. The value is in the execution.</p>
<p>For most student work, the practical answer is three layers:</p>
<ol type="1">
<li><strong>Explore in notebooks.</strong> This is where you poke at the data, try plots, and figure out what the analysis should be. Early notebooks are messy, and that’s fine: they’re scratch paper.</li>
<li><strong>Move stable logic into <code>src/</code> as functions.</strong> Any block you’ve copied into a second notebook, or tweaked for the fourth time, should become a function. The notebook’s ten lines of cleaning become one line, <code>clean_sales(df)</code>, and the function can be reused and tested.</li>
<li><strong>Keep the notebook as the narrative.</strong> Once the logic lives in <code>src/</code>, the notebook tells the story: load the data, call the functions, show the results, explain what they mean.</li>
</ol>
<pre class="text"><code>notebooks/
└── 01-explore.ipynb   ← narrative + plots + interpretation
src/
├── cleaning.py        ← pure functions, imported by both the notebook
├── modeling.py           and the CLI script
└── plotting.py
scripts/
└── run_pipeline.py    ← batch entry point, imported by nothing,
                         runs the same src/ functions from the command line</code></pre>
<p>The notebook and the script import the <em>same</em> functions, so an improvement to a cleaning step reaches both at once. A small project can start as one notebook, grow a <code>src/</code> when it gets complicated, and add <code>scripts/</code> when it needs automating, without ever being rewritten from scratch.</p>
<p>When you do want a notebook’s code as a script, <a href="https://nbconvert.readthedocs.io/en/latest/">nbconvert</a> will write one: <code>jupyter nbconvert --to script analysis.ipynb</code> produces <code>analysis.py</code> (and <code>--to html</code> makes a web page to share). Expect to tidy the result. Each bang line becomes <code>get_ipython().system(...)</code>, which runs only inside IPython, and the cells come out in page order, which is one more reason to keep that order honest.</p>
</section>
<section id="notebooks-on-someone-elses-computer-colab-kaggle-and-codespaces" class="level2" data-number="16.10">
<h2 data-number="16.10" class="anchored" data-anchor-id="notebooks-on-someone-elses-computer-colab-kaggle-and-codespaces"><span class="header-section-number">16.10</span> Notebooks on someone else’s computer: Colab, Kaggle, and Codespaces</h2>
<p>Everything so far assumes Jupyter runs on your own computer. Often it doesn’t. A course hands out a Google Colab link, a dataset lives on Kaggle, or a project opens in a GitHub Codespace. The notebook looks the same, but the kernel runs on a machine you rent or borrow, and five things change: what survives when you leave, which packages are installed, where secrets go, what hardware you get, and who else can see your data.</p>
<p>The three platforms are built for different jobs. <strong>Google Colab</strong> is a Jupyter-style notebook running on a Google virtual machine, good for course notebooks and for trying a GPU. <strong>Kaggle Notebooks</strong> sit next to Kaggle’s datasets and competitions, which is what they’re best for. <strong>GitHub Codespaces</strong> gives you a full development environment for one repository, VS Code in the browser with notebooks, a terminal, and files, which helps when your own computer can’t run a project.</p>
<div id="tbl-hosted-notebooks" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hosted-notebooks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16.1: Three hosted notebook platforms, and what changes on each.
</figcaption>
<div aria-describedby="tbl-hosted-notebooks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Platform</th>
<th>Where your work is saved</th>
<th>What disappears</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Google Colab</strong></td>
<td>The notebook, in your Google Drive</td>
<td>Every file on the virtual machine, and anything you installed, when the runtime is recycled</td>
</tr>
<tr class="even">
<td><strong>Kaggle Notebooks</strong></td>
<td>Your Kaggle account, as saved versions and their output</td>
<td>Everything else, including anything you installed, when the session ends</td>
</tr>
<tr class="odd">
<td><strong>GitHub Codespaces</strong></td>
<td>The repository, once you commit and push</td>
<td>Nothing while the codespace exists; the codespace itself, after a period of disuse</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Each platform changes its limits and prices often, so check its own documentation for the numbers: <a href="https://research.google.com/colaboratory/faq.html">Colab’s FAQ</a>, <a href="https://www.kaggle.com/docs/notebooks">Kaggle’s notebook docs</a>, and <a href="https://docs.github.com/en/codespaces">GitHub’s Codespaces docs</a>. What follows is what holds even when the numbers change.</p>
<section id="what-survives-when-you-leave" class="level3">
<h3 class="anchored" data-anchor-id="what-survives-when-you-leave">What survives when you leave</h3>
<p>The biggest surprise on a hosted platform is that the notebook survives and its files don’t.</p>
<ul>
<li><p><strong>Colab</strong> saves the notebook to your Drive, but the code runs in a virtual machine that Google deletes when you have been idle for a while or when it reaches a maximum lifetime (as of September 2026, at most 12 hours on the free tier). Anything you downloaded or wrote there, such as <code>data.csv</code> or a trained model, goes with it. To keep files, <a href="https://colab.research.google.com/notebooks/io.ipynb">mount your Drive</a> and write there:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> google.colab <span class="im">import</span> drive</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>drive.mount(<span class="st">"/content/drive"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">"/content/drive/MyDrive/thesis/clean.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p><strong>Kaggle</strong> attaches datasets read-only under <code>/kaggle/input/</code>. Files you write to <code>/kaggle/working/</code> are kept as the notebook’s output when you save a version (<em>Save Version</em>, then <em>Save &amp; Run All</em>); everything else ends with the session.</p></li>
<li><p><strong>Codespaces</strong> behave more like a computer of your own. A codespace stops after 30 minutes of inactivity by default and keeps your saved changes while stopped, but GitHub deletes an unused codespace after 30 days by default. Rebuilding one keeps only what is inside <code>/workspaces</code>. Treat <code>git push</code> as the save button: work that is only in a codespace is one deletion away from gone.</p></li>
</ul>
<p>On all three, the habits from “Keep it reproducible” above matter more, not less: expect to start from a fresh machine, so make <em>Restart and Run All</em> work from the first cell.</p>
</section>
<section id="the-environment-isnt-yours" class="level3">
<h3 class="anchored" data-anchor-id="the-environment-isnt-yours">The environment isn’t yours</h3>
<p>Colab and Kaggle start every session from their own image, with hundreds of packages already installed, at versions the platform chose and changes without asking you. Two consequences. First, a package you install with <code>%pip install</code> lasts only until the session ends, so put the installs in the notebook’s first cell rather than typing them once. Second, a notebook that works today can break when the image updates. Pin the versions that matter (<code>%pip install pandas==2.2.3</code>) and record the rest by printing versions in the notebook, as in “Record the environment” above. A Codespace instead builds its environment from the repository’s own configuration, a <a href="https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers">dev container</a> file (<code>.devcontainer/devcontainer.json</code>) and usually a <code>requirements.txt</code>, plus anything you add, which makes it the closest of the three to the virtual environments in <a href="virtual-environments.html" class="quarto-xref"><span>Chapter 15</span></a>.</p>
</section>
<section id="secrets-go-in-the-platforms-secrets-store" class="level3">
<h3 class="anchored" data-anchor-id="secrets-go-in-the-platforms-secrets-store">Secrets go in the platform’s secrets store</h3>
<p>Never paste an API key into a cell. Notebooks are made to be shared, and a key in a cell is shared with them, along with the outputs, which can print it too. Each platform has a secrets store that keeps the key outside the notebook: Colab’s Secrets panel (the key icon in the left sidebar), Kaggle’s <em>Add-ons → Secrets</em> menu, and the <a href="https://docs.github.com/en/codespaces/managing-your-codespaces/managing-your-account-specific-secrets-for-github-codespaces">Codespaces secrets</a> in your GitHub settings, which arrive as environment variables:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Colab: add the key in the Secrets panel (key icon), then</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> google.colab <span class="im">import</span> userdata</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>api_key <span class="op">=</span> userdata.get(<span class="st">"WEATHER_API_KEY"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Kaggle: add it under Add-ons → Secrets, then</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> kaggle_secrets <span class="im">import</span> UserSecretsClient</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>api_key <span class="op">=</span> UserSecretsClient().get_secret(<span class="st">"WEATHER_API_KEY"</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Codespaces: add it in GitHub's Codespaces settings; it arrives as an environment variable</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>api_key <span class="op">=</span> os.environ[<span class="st">"WEATHER_API_KEY"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The code differs, but the idea is the one in <a href="secrets.html" class="quarto-xref"><span>Chapter 34</span></a>: the notebook names the secret and never contains it.</p>
</section>
<section id="gpus-available-not-promised" class="level3">
<h3 class="anchored" data-anchor-id="gpus-available-not-promised">GPUs: available, not promised</h3>
<p>A free GPU (graphics processor) is the main reason many people open Colab or Kaggle. On Colab you ask for one under <em>Runtime → Change runtime type</em>; on Kaggle, under the notebook’s <em>Accelerator</em> setting. Neither is guaranteed. Free GPU time is rationed, the hardware you get varies, and a busy day can mean none. Check what you actually got before starting a long job (<code>!nvidia-smi</code> prints the GPU, or an error if there is none), and save progress as you go, because a free session can end in the middle of a run. Codespaces is not a GPU platform for most students.</p>
</section>
<section id="before-you-upload-data" class="level3">
<h3 class="anchored" data-anchor-id="before-you-upload-data">Before you upload data</h3>
<p>Uploading a file to a hosted notebook copies it to a company’s servers. For public data, that’s fine. For interview transcripts, student records, health data, or anything under a data-use agreement or an ethics board’s approval (an <a href="https://en.wikipedia.org/wiki/Institutional_review_board">IRB</a>), check before you upload: many agreements name where the data may be stored, and “a free notebook service” is rarely on the list. Your university may run its own <a href="https://jupyterhub.readthedocs.io/en/stable/">JupyterHub</a> for exactly this reason; ask your instructor or IT office. And remember that a shared notebook carries its outputs: every <code>df.head()</code> shows real rows to whoever opens the link.</p>
</section>
</section>
<section id="stakes-and-politics" class="level2" data-number="16.11">
<h2 data-number="16.11" class="anchored" data-anchor-id="stakes-and-politics"><span class="header-section-number">16.11</span> Stakes and politics</h2>
<p>You’re stuck, so you push your notebook to a public GitHub repository and paste the link into a forum. The code is fine to share. But cell 4 ran <code>df.head()</code> on a survey export, and its output, saved inside the file, shows five respondents’ names, email addresses, and free-text answers. Anyone who opens the link sees them, and deleting the notebook in a later commit doesn’t remove it from the repository’s history (see <a href="version-control.html" class="quarto-xref"><span>Chapter 31</span></a>). Inline output is what makes notebooks so good for exploring, and the format never warns you that it’s also a copy of your data. That’s why this chapter keeps suggesting you clear outputs or strip them before you commit.</p>
<p>The same feature hides a second problem. A notebook with clean outputs looks like proof, code and answer side by side, but it could have come from any order of cell runs, any forgotten variable, any version of any package. When researchers tried to rerun about 864,000 notebooks from GitHub in 2019, <a href="https://leomurta.github.io/papers/pimentel2019a.pdf">only about 4% reproduced their saved results</a> (<a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a> tells that story). Making a notebook rerunnable takes work that doesn’t show on the page: a pinned environment, written provenance, and a restart-and-run-all before every save. Without it, a notebook is closer to a screenshot than a program, and the cost falls on whoever tries to build on it next.</p>
<p>See <a href="artifacts-have-politics.html" class="quarto-xref"><span>Chapter 8</span></a> for the broader framework. The concrete prompt to carry forward: before you share a notebook, ask whether someone could rerun it from scratch, and whether anything in its output should not have left your laptop.</p>
</section>
<section id="worked-examples" class="level2" data-number="16.12">
<h2 data-number="16.12" class="anchored" data-anchor-id="worked-examples"><span class="header-section-number">16.12</span> Worked examples</h2>
<section id="launching-jupyter-in-the-right-place" class="level3">
<h3 class="anchored" data-anchor-id="launching-jupyter-in-the-right-place">Launching Jupyter in the right place</h3>
<p>You have a project at <code>~/Courses/INFO-3010/Project</code>, and you want to start working in a notebook. Start the server from the project:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> cd ~/Courses/INFO-3010/Project</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> source .venv/bin/activate</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="ex">.venv</span><span class="kw">)</span> <span class="ex">$</span> jupyter lab</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="ex">[I</span> 2026-04-10 12:34:56.789 ServerApp] http://localhost:8888/lab<span class="pp">?</span>token=abc...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Your browser opens on JupyterLab (if it doesn’t, click the address Jupyter prints). Open the <code>notebooks/</code> folder in the file browser, create a new notebook there with the Python 3 kernel, and make its first cell a check:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os, sys</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"python:"</span>, sys.executable)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cwd:   "</span>, os.getcwd())</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"above: "</span>, <span class="bu">sorted</span>(os.listdir(<span class="st">".."</span>))[:<span class="dv">5</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>python: /Users/you/Courses/INFO-3010/Project/.venv/bin/python3
cwd:    /Users/you/Courses/INFO-3010/Project/notebooks
above:  ['.venv', 'README.md', 'data', 'notebooks', 'src']</code></pre>
<p>If all three lines look right, you’re ready to work: the Python comes from the project’s <code>.venv</code>, the notebook is working in <code>notebooks/</code> (so paths to your data start with <code>../</code>, unless you use the project’s paths module), and the folder above is the project you expect.</p>
</section>
<section id="debugging-no-files" class="level3">
<h3 class="anchored" data-anchor-id="debugging-no-files">Debugging “no files”</h3>
<p>You open JupyterLab, and the file browser shows your home folder instead of your project. Go back to the terminal, stop the server with <code>Ctrl+C</code> twice, and look at where you are:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> pwd</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="ex">/Users/you</span>                   <span class="co"># the wrong place</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> cd Courses/INFO-3010/Project</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> source .venv/bin/activate</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="ex">.venv</span><span class="kw">)</span> <span class="ex">$</span> jupyter lab</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Now the file browser shows the project, and the check cell from the previous example confirms it. The whole fix is “go to the right folder before starting the server,” which is why the previous example put <code>cd</code> first.</p>
</section>
<section id="making-a-notebook-reproducible" class="level3">
<h3 class="anchored" data-anchor-id="making-a-notebook-reproducible">Making a notebook reproducible</h3>
<p>You’ve finished an analysis of monthly sales, and before you submit it you run <em>Kernel → Restart Kernel and Run All Cells</em>. The third cell stops:</p>
<pre class="text"><code>AttributeError: Can only use .dt accessor with datetimelike values</code></pre>
<p>That cell worked all afternoon, so something it depends on must live only in the kernel’s memory. The execution counts from before the restart tell you what: the cell that converts <code>date</code> with <code>pd.to_datetime</code> sits <em>below</em> this one, and you had run it first. Move the conversion cell above the cell that uses it, restart and run all again, and every cell runs, with counts from <code>[1]</code> to <code>[5]</code> in order.</p>
<p>While you’re there, finish the job. Make sure the notebook opens with a title, a sentence of purpose, and a setup cell that prints versions. Move the cleaning steps you copied from last week’s notebook into a function in <code>src/</code> and import it. Clear the outputs, restart and run all one last time, and commit. Finding the hidden-state bug took two minutes this way, instead of arriving as an email from a grader.</p>
</section>
</section>
<section id="templates" class="level2" data-number="16.13">
<h2 data-number="16.13" class="anchored" data-anchor-id="templates"><span class="header-section-number">16.13</span> Templates</h2>
<section id="template-a-notebook-header-block" class="level3">
<h3 class="anchored" data-anchor-id="template-a-notebook-header-block">Template A: Notebook header block</h3>
<p>A first Markdown cell that answers a reader’s first questions:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># &lt;Title&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>**Author:** &lt;name&gt; · **Date:** <span class="dt">&lt;</span><span class="kw">YYYY-MM-DD</span><span class="dt">&gt;</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>**Purpose:** <span class="dt">&lt;</span><span class="kw">one</span><span class="ot"> or two sentences: what this notebook does and why</span><span class="dt">&gt;</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>**Data sources:** <span class="dt">&lt;</span><span class="kw">where</span><span class="ot"> each input came from</span><span class="er">,</span><span class="ot"> and when you got it</span><span class="dt">&gt;</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>**Environment:** Python <span class="dt">&lt;</span><span class="kw">version</span><span class="dt">&gt;</span>; key packages <span class="dt">&lt;</span><span class="kw">pandas</span><span class="ot"> x.y</span><span class="er">,</span><span class="ot"> </span><span class="er">...</span><span class="dt">&gt;</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>(recreate with <span class="in">`requirements.txt`</span>, see README)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>**How to run:** Kernel → Restart Kernel and Run All Cells</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>**Outputs:** <span class="dt">&lt;</span><span class="kw">where</span><span class="ot"> figures and tables are saved</span><span class="er">,</span><span class="ot"> e.g. </span><span class="er">`</span><span class="ot">figures</span><span class="er">/`,</span><span class="ot"> </span><span class="er">`</span><span class="ot">data</span><span class="er">/</span><span class="ot">processed</span><span class="er">/`</span><span class="dt">&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="template-b-reproducibility-check-cell" class="level3">
<h3 class="anchored" data-anchor-id="template-b-reproducibility-check-cell">Template B: Reproducibility check cell</h3>
<p>A first code cell that shows at a glance whether the environment and data are what the notebook expects. If your project has a paths module (<a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a>), import <code>DATA_RAW</code> from it instead of the <code>Path("..")</code> line:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibility check: run this cell first</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os, sys</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>DATA_RAW <span class="op">=</span> Path(<span class="st">".."</span>) <span class="op">/</span> <span class="st">"data"</span> <span class="op">/</span> <span class="st">"raw"</span>   <span class="co"># this notebook is saved in notebooks/</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cwd:   "</span>, os.getcwd())</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"python:"</span>, sys.executable)</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"pandas:"</span>, pd.__version__)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> [<span class="st">"sales.csv"</span>]:              <span class="co"># the files this notebook reads</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    path <span class="op">=</span> DATA_RAW <span class="op">/</span> name</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"OK     "</span> <span class="cf">if</span> path.exists() <span class="cf">else</span> <span class="st">"MISSING"</span>, path)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="exercises" class="level2" data-number="16.14">
<h2 data-number="16.14" class="anchored" data-anchor-id="exercises"><span class="header-section-number">16.14</span> Exercises</h2>
<ol type="1">
<li><p>Open a terminal in a project folder, launch JupyterLab from there, and confirm in the file browser that you can see the project’s files. Then launch it from your home folder and notice what changes.</p></li>
<li><p>In a new notebook, define a variable in cell 3, use it in cell 2, and run the cells out of order so the notebook “works.” Then run <em>Restart Kernel and Run All Cells</em> and fix what breaks.</p></li>
<li><p>Add a first cell to one of your notebooks that prints the Python executable, the versions of the packages you import, and the date, as in “Record the environment” above.</p></li>
<li><p>Take a notebook that does the same cleaning in two places, move that code into a function in <code>src/</code>, and import it in the notebook.</p></li>
<li><p>Open a notebook in Google Colab. Write a small file to the virtual machine and another to your mounted Drive, choose <em>Runtime → Disconnect and delete runtime</em>, reconnect, and check which file is still there.</p></li>
<li><p>Profile the slowest notebook or script you have with <code>%prun -s cumulative</code> (or <code>python -m cProfile -s cumulative</code>). Write down which of your functions takes the most time before you change anything, fix only that one, and measure again.</p></li>
</ol>
</section>
<section id="one-page-checklist" class="level2" data-number="16.15">
<h2 data-number="16.15" class="anchored" data-anchor-id="one-page-checklist"><span class="header-section-number">16.15</span> One-page checklist</h2>
<ul>
<li>Launch Jupyter from the project folder, with the project’s environment active.</li>
<li>Remember that a notebook’s code runs in the folder where the notebook is saved.</li>
<li>When files are missing, check which server you’re looking at and where it was started.</li>
<li>Check the kernel with <code>sys.executable</code> before installing anything.</li>
<li>Use Markdown headings and short paragraphs so the notebook reads as a document.</li>
<li>Keep imports and setup at the top, and run top to bottom.</li>
<li>Restart the kernel and run all after every chunk of work, and before you share.</li>
<li>Use shell commands and magics sparingly, with a note saying what each does, and never with a secret.</li>
<li>Record package versions and keep data provenance in the notebook.</li>
<li>Summarize outputs, save figures to files, and clear outputs before committing.</li>
<li>On a hosted notebook, save files somewhere that outlasts the session, keep keys in the platform’s secrets store, and check before uploading restricted data.</li>
<li>When code is slow, profile before rewriting, and replace row-by-row work with whole-column operations.</li>
</ul>
</section>
<section id="quick-reference-common-launch-and-debugging-moves" class="level2" data-number="16.16">
<h2 data-number="16.16" class="anchored" data-anchor-id="quick-reference-common-launch-and-debugging-moves"><span class="header-section-number">16.16</span> Quick reference: common launch and debugging moves</h2>
<ul>
<li>Wrong files in the browser: stop the server (<code>Ctrl+C</code> twice), <code>cd</code> to the project, and relaunch; <code>jupyter server list</code> finds stray servers.</li>
<li><code>FileNotFoundError</code>: print <code>os.getcwd()</code> and the path’s <code>.resolve()</code> to see where the kernel looked.</li>
<li>Imports fail: print <code>sys.executable</code>, switch kernels, or register the environment with <code>python -m ipykernel install --user --name=...</code>.</li>
<li>A cell hangs: interrupt (<code>I</code>, <code>I</code>), then restart (<code>0</code>, <code>0</code>) only if needed.</li>
</ul>
</section>
<section id="quick-reference-ipython-conveniences" class="level2" data-number="16.17">
<h2 data-number="16.17" class="anchored" data-anchor-id="quick-reference-ipython-conveniences"><span class="header-section-number">16.17</span> Quick reference: IPython conveniences</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Type this in a cell</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>len?</code></td>
<td>Show a function’s signature and docstring (<code>??</code> shows its source too)</td>
</tr>
<tr class="even">
<td><code>Tab</code> after a name</td>
<td>Complete it; <code>Shift + Tab</code> inside the parentheses shows the signature</td>
</tr>
<tr class="odd">
<td><code>%pwd</code>, <code>%ls</code>, <code>%cd path</code></td>
<td>Print, list, or change the kernel’s working directory</td>
</tr>
<tr class="even">
<td><code>!command</code></td>
<td>Run one shell command, such as <code>!ls data/raw/</code></td>
</tr>
<tr class="odd">
<td><code>%env VAR</code></td>
<td>Show an environment variable (<code>%env VAR=value</code> sets it)</td>
</tr>
<tr class="even">
<td><code>%pip install package</code></td>
<td>Install a package into the kernel’s own environment</td>
</tr>
<tr class="odd">
<td><code>%time expr</code>, <code>%%time</code></td>
<td>Time one line, or the whole cell</td>
</tr>
<tr class="even">
<td><code>%timeit expr</code>, <code>%%timeit</code></td>
<td>Run a small piece of code many times and report how long it takes</td>
</tr>
<tr class="odd">
<td><code>%prun -s cumulative f()</code></td>
<td>Profile a call: how long each function it runs takes, slowest first</td>
</tr>
<tr class="even">
<td><code>%load_ext autoreload</code> then <code>%autoreload 2</code></td>
<td>Reload your own modules (<code>src/</code>) when you edit them</td>
</tr>
<tr class="odd">
<td><code>%who</code></td>
<td>List the variables defined in the kernel</td>
</tr>
<tr class="even">
<td><code>%run script.py</code></td>
<td>Run a script in the kernel, keeping its variables afterwards</td>
</tr>
<tr class="odd">
<td><code>%lsmagic</code></td>
<td>List every magic command available</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📚 Further reading
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Project Jupyter</strong>, <a href="https://jupyterlab.readthedocs.io/en/latest/">JupyterLab documentation</a> — the official guide to the interface, extensions, and kernels; the user guide section is the place to start.</li>
<li><strong>Project Jupyter</strong>, <a href="https://jupyter-notebook.readthedocs.io/en/latest/">Jupyter Notebook documentation</a> — the classic single-document interface, still widely used in courses.</li>
<li><strong>IPython</strong>, <a href="https://ipython.readthedocs.io/en/stable/">IPython documentation</a> — the kernel underneath every Python notebook; learn its <code>?</code>, <code>??</code>, <code>%timeit</code>, and <code>%debug</code> and you’ll reach for separate tools less often.</li>
<li><strong>Joel Grus</strong>, <a href="https://docs.google.com/presentation/d/1n2RlMdmv1p25Xy5thJUhkKGvjtV-dkAIsUXP-AL4ffI/edit">I Don’t Like Notebooks (JupyterCon 2018)</a> — a sharp, well-known critique of notebook workflows; worth knowing the arguments even if you keep using notebooks.</li>
<li><strong>Florian Rathgeber</strong>, <a href="https://github.com/kynan/nbstripout"><code>nbstripout</code></a> — removes outputs from notebooks, and after <code>nbstripout --install</code> does it automatically whenever you commit; the simplest defense against leaking inline data into a Git history.</li>
<li><strong>nteract</strong>, <a href="https://papermill.readthedocs.io/en/latest/">Papermill</a> — runs notebooks from the command line with different parameters, which turns a notebook into something closer to a reproducible pipeline.</li>
<li><strong>Project Jupyter</strong>, <a href="https://jupyter.org/governance/">Jupyter Governance</a> — the project’s governance documents; useful context when you wonder who actually decides where the platform goes next.</li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/virtual-environments.html" class="pagination-link" aria-label="Virtual Environments">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Virtual Environments</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/scripting.html" class="pagination-link" aria-label="Scripting">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Scripting</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/edit/main/chapters/jupyter.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>