<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>36&nbsp; How Language Models Work – Missing Manual for Information Scientists</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ai-agents.html" rel="next">
<link href="../chapters/ai-llm.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a01bfd6df65136af83067365c1c6ba8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-eb8f170073725aebc42af3c4860b2e9c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9a01bfd6df65136af83067365c1c6ba8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../tools/chapter-meme/chapter-meme.css">
<link rel="stylesheet" href="../styles/layout.css">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ai-llm.html">Part VII — Algorithmic Systems</a></li><li class="breadcrumb-item"><a href="../chapters/llm-internals.html"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">How Language Models Work</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Missing Manual for Information Scientists</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/cuinfoscience/INFO-Missing-Manual" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=|url|" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Practice of Technical Work</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Asking Technical Questions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/documentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Technical Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/common-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Common Text Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-docs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reading Official Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Debugging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tracebacks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reading Python Tracebacks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/artifacts-have-politics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Artifacts Have Politics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Computing Environment</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/operating-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Operating System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/file-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Local File System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/terminal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Command Line</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/text-editors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Text Editors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/remote.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Remote Computing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Python Management</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/package-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Package Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/virtual-environments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Virtual Environments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Jupyter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/scripting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Scripting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/regex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regular Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Code Style</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Working with Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-file-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data File Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tabular-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Tabular Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/pandas-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">pandas Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sql-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/http-apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">HTTP and Web APIs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V — Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-scholarship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">How to Read Scholarly Articles and Books</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/writing-manuscripts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">How to Write Scholarly Manuscripts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/writing-thesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">How to Write a Thesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/presenting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">How to Present</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">How to Use LaTeX</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI — Project Management</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/project-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/version-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Version Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/collaboration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Collaboration Mechanics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/automation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Automation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/secrets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Environment Variables and Secrets</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VII — Algorithmic Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ai-llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Using AI Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/llm-internals.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">How Language Models Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ai-agents.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Working with AI Agent Frameworks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/evaluating-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Evaluating and Auditing AI Outputs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-ai-disclosure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Disclosure: Use of AI in Authoring</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="../graphics/memes/llm-internals.png" class="chapter-meme img-fluid" alt="Ten Guy Meme: What if every word is just a point in a 4096-dimensional space?"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#why-read-this-chapter" id="toc-why-read-this-chapter" class="nav-link" data-scroll-target="#why-read-this-chapter">Why read this chapter</a></li>
  <li><a href="#running-theme-the-model-sees-text-not-meaning" id="toc-running-theme-the-model-sees-text-not-meaning" class="nav-link" data-scroll-target="#running-theme-the-model-sees-text-not-meaning">Running theme: the model sees text, not meaning</a></li>
  <li><a href="#tokens-what-the-model-actually-reads" id="toc-tokens-what-the-model-actually-reads" class="nav-link" data-scroll-target="#tokens-what-the-model-actually-reads"><span class="header-section-number">36.1</span> Tokens: what the model actually reads</a></li>
  <li><a href="#predicting-the-next-token" id="toc-predicting-the-next-token" class="nav-link" data-scroll-target="#predicting-the-next-token"><span class="header-section-number">36.2</span> Predicting the next token</a></li>
  <li><a href="#context-windows-why-it-forgets" id="toc-context-windows-why-it-forgets" class="nav-link" data-scroll-target="#context-windows-why-it-forgets"><span class="header-section-number">36.3</span> Context windows: why it “forgets”</a></li>
  <li><a href="#sampling-and-temperature-why-the-same-prompt-gives-different-answers" id="toc-sampling-and-temperature-why-the-same-prompt-gives-different-answers" class="nav-link" data-scroll-target="#sampling-and-temperature-why-the-same-prompt-gives-different-answers"><span class="header-section-number">36.4</span> Sampling and temperature: why the same prompt gives different answers</a></li>
  <li><a href="#embeddings-text-as-points-in-space" id="toc-embeddings-text-as-points-in-space" class="nav-link" data-scroll-target="#embeddings-text-as-points-in-space"><span class="header-section-number">36.5</span> Embeddings: text as points in space</a></li>
  <li><a href="#writing-prompts-that-work" id="toc-writing-prompts-that-work" class="nav-link" data-scroll-target="#writing-prompts-that-work"><span class="header-section-number">36.6</span> Writing prompts that work</a></li>
  <li><a href="#chatbot-or-api" id="toc-chatbot-or-api" class="nav-link" data-scroll-target="#chatbot-or-api"><span class="header-section-number">36.7</span> Chatbot or API?</a></li>
  <li><a href="#tools-and-function-calling-who-runs-the-code" id="toc-tools-and-function-calling-who-runs-the-code" class="nav-link" data-scroll-target="#tools-and-function-calling-who-runs-the-code"><span class="header-section-number">36.8</span> Tools and function calling: who runs the code?</a></li>
  <li><a href="#why-models-state-false-things-fluently" id="toc-why-models-state-false-things-fluently" class="nav-link" data-scroll-target="#why-models-state-false-things-fluently"><span class="header-section-number">36.9</span> Why models state false things fluently</a></li>
  <li><a href="#stakes-and-politics" id="toc-stakes-and-politics" class="nav-link" data-scroll-target="#stakes-and-politics"><span class="header-section-number">36.10</span> Stakes and politics</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples"><span class="header-section-number">36.11</span> Worked examples</a>
  <ul class="collapse">
  <li><a href="#diagnosing-why-a-prompt-produces-inconsistent-output" id="toc-diagnosing-why-a-prompt-produces-inconsistent-output" class="nav-link" data-scroll-target="#diagnosing-why-a-prompt-produces-inconsistent-output">Diagnosing why a prompt produces inconsistent output</a></li>
  <li><a href="#converting-a-chatbot-workflow-to-an-api-call" id="toc-converting-a-chatbot-workflow-to-an-api-call" class="nav-link" data-scroll-target="#converting-a-chatbot-workflow-to-an-api-call">Converting a chatbot workflow to an API call</a></li>
  <li><a href="#building-a-simple-semantic-search-with-embeddings" id="toc-building-a-simple-semantic-search-with-embeddings" class="nav-link" data-scroll-target="#building-a-simple-semantic-search-with-embeddings">Building a simple semantic search with embeddings</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">36.12</span> Exercises</a></li>
  <li><a href="#one-page-checklist" id="toc-one-page-checklist" class="nav-link" data-scroll-target="#one-page-checklist"><span class="header-section-number">36.13</span> One-page checklist</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/edit/main/chapters/llm-internals.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ai-llm.html">Part VII — Algorithmic Systems</a></li><li class="breadcrumb-item"><a href="../chapters/llm-internals.html"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">How Language Models Work</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-llm-internals" class="quarto-section-identifier"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">How Language Models Work</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Prerequisites and see-also
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Prerequisites (read first if unfamiliar):</strong> <a href="ai-llm.html" class="quarto-xref"><span>Chapter 35</span></a>.</p>
<p><strong>See also:</strong> <a href="ai-agents.html" class="quarto-xref"><span>Chapter 37</span></a>, <a href="evaluating-ai.html" class="quarto-xref"><span>Chapter 38</span></a>.</p>
</div>
</div>
</div>
<section id="purpose" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="purpose">Purpose</h2>
<div class="chapter-meme-inline d-lg-none">
<p><img src="../graphics/memes/llm-internals.png" class="img-fluid" alt="Ten Guy Meme: What if every word is just a point in a 4096-dimensional space?"></p>
</div>
<p>You ask a chatbot to fix a bug, and it writes forty clean lines of Python in five seconds. Then you ask how many r’s are in “strawberry,” and it gets it wrong. You paste in a long reading with careful instructions, and ten replies later it’s ignoring them. You run the same prompt twice and get two different answers. And now and then it cites a paper or a function that doesn’t exist, in the same confident tone it uses for everything else.</p>
<p>If that has left you unsure when to trust these tools, you’re asking the right question. None of those behaviors is random, and none means the tool is broken. They follow from how a <a href="../chapters/appendix-glossary.html#term-llm">large language model</a> turns your text into numbers and predicts what comes next. Once you can picture those steps, you can tell a bad prompt from a limit of the model, and you stop being surprised by the same failure twice.</p>
<p>This chapter gives you that picture, with code you can run on a laptop, most of it without an API key: tokens, next-token prediction, context windows, temperature, embeddings, calling a model from code, tool use, and why models state false things fluently. It doesn’t teach the math of training. Everyday habits for using AI assistants are in <a href="ai-llm.html" class="quarto-xref"><span>Chapter 35</span></a>, models that take actions are in <a href="ai-agents.html" class="quarto-xref"><span>Chapter 37</span></a>, and testing whether an AI system works is in <a href="evaluating-ai.html" class="quarto-xref"><span>Chapter 38</span></a>.</p>
</section>
<section id="why-read-this-chapter" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="why-read-this-chapter">Why read this chapter</h2>
<ul>
<li>You asked a chatbot how many r’s are in “strawberry,” it got it wrong, and you’d like to know how something that writes fluent essays can’t count letters.</li>
<li>You ran the exact same prompt twice, maybe even with the temperature set to 0, and got two different answers.</li>
<li>You pasted a long document into a chat, and a few replies later the model was ignoring the instructions you gave at the start.</li>
<li>A model handed you a citation or a function name that sounded perfect and turned out not to exist.</li>
<li>You’re paying for an API by the token and want to know what a token is, and why the same sentence in Hindi or Amharic costs more than in English.</li>
<li>You keep hearing “embeddings,” “RAG,” and “vector database,” and you’d like to see what they mean in a few lines of code.</li>
<li>Someone said “the model called a tool,” and you want to know who actually ran the code.</li>
</ul>
</section>
<section id="running-theme-the-model-sees-text-not-meaning" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="running-theme-the-model-sees-text-not-meaning">Running theme: the model sees text, not meaning</h2>
<p>Almost everything a language model does, the impressive parts and the maddening ones, follows from one fact: it turns your text into tokens and predicts, one token at a time, what’s likely to come next.</p>
</section>
<section id="tokens-what-the-model-actually-reads" class="level2" data-number="36.1">
<h2 data-number="36.1" class="anchored" data-anchor-id="tokens-what-the-model-actually-reads"><span class="header-section-number">36.1</span> Tokens: what the model actually reads</h2>
<p>The first surprise is that the model never sees your letters. Your text is cut into chunks called <strong>tokens</strong>, each chunk is swapped for a number, and the numbers are what the model works with. You can watch this happen with <a href="https://pypi.org/project/tiktoken/">tiktoken</a>, OpenAI’s tokenizer library (<code>pip install tiktoken</code>):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tiktoken</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>enc <span class="op">=</span> tiktoken.get_encoding(<span class="st">"o200k_base"</span>)  <span class="co"># the tokenizer GPT-4o uses</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> text <span class="kw">in</span> [<span class="st">"the quick brown fox"</span>, <span class="st">"unbelievable"</span>, <span class="st">"strawberry"</span>, <span class="st">" strawberry"</span>, <span class="st">"Boulder"</span>]:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    ids <span class="op">=</span> enc.encode(text)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    pieces <span class="op">=</span> [enc.decode([i]) <span class="cf">for</span> i <span class="kw">in</span> ids]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>text<span class="sc">!r:22}</span><span class="ss"> </span><span class="sc">{</span>pieces<span class="sc">}</span><span class="ss">  </span><span class="sc">{</span>ids<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>'the quick brown fox'  ['the', ' quick', ' brown', ' fox']  [3086, 4853, 19705, 68347]
'unbelievable'         ['un', 'bel', 'ievable']  [373, 9880, 45794]
'strawberry'           ['st', 'raw', 'berry']  [302, 1618, 19772]
' strawberry'          [' strawberry']  [101830]
'Boulder'              ['B', 'oulder']  [33, 62664]</code></pre>
<p>Common words get a token of their own, leading space included, while rarer words are built from pieces. The pieces come from <a href="https://en.wikipedia.org/wiki/Byte-pair_encoding">byte-pair encoding</a>, which starts from single characters and keeps merging the pairs that appear together most often in a pile of training text, until it has a vocabulary of a set size (about 200,000 entries here). Hugging Face’s course has a <a href="https://huggingface.co/learn/llm-course/chapter6/5">clear walk-through</a> of how the merges are learned.</p>
<p>Now look at “strawberry” again. With a space in front, as it usually appears mid-sentence, it’s one token, number 101830. That’s why the letter-counting question is hard: the model isn’t looking at s-t-r-a-w-b-e-r-r-y, it’s looking at one number, and it has to have <em>learned</em> how many r’s that number contains. Python gets <code>"strawberry".count("r")</code> right because it works on characters. Newer models often get the strawberry question right too, but when a model stumbles on spelling, letter counts, or reversing a word, tokens are usually why.</p>
<p>Tokens are also the unit you <strong>pay in and hit limits in</strong>. For ordinary English a token averages about four characters, or three-quarters of a word, but tokenizers differ even within one company: Anthropic’s <a href="https://platform.claude.com/docs/en/about-claude/models/overview">models overview</a> says a million tokens holds about 555,000 words on its current tokenizer and 750,000 on the one before. To count exactly, use the provider’s own tool: tiktoken for OpenAI models, or Anthropic’s <a href="https://platform.claude.com/docs/en/build-with-claude/token-counting">token-counting endpoint</a> for Claude, whose tokenizer isn’t public. Code splits differently from prose (<code>df.groupby('state')['income'].median()</code> is nine tokens), and a technical term the tokenizer never learned whole reaches the model as fragments.</p>
<p>The biggest differences are between languages. Here is Article 1 of the <a href="https://en.wikipedia.org/wiki/Universal_Declaration_of_Human_Rights">Universal Declaration of Human Rights</a> in nine languages, counted with GPT-2’s tokenizer from 2019 and GPT-4o’s from 2024:</p>
<table class="caption-top table">
<caption>Tokens for Article 1 of the Universal Declaration of Human Rights, counted with tiktoken (<code>gpt2</code> and <code>o200k_base</code>) on the texts in Unicode’s UDHR collection, September 2026.</caption>
<thead>
<tr class="header">
<th>Language</th>
<th>GPT-2 tokens</th>
<th>GPT-4o tokens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>English</td>
<td>33</td>
<td>33</td>
</tr>
<tr class="even">
<td>Spanish</td>
<td>58</td>
<td>38</td>
</tr>
<tr class="odd">
<td>Swahili</td>
<td>49</td>
<td>36</td>
</tr>
<tr class="even">
<td>Chinese (simplified)</td>
<td>82</td>
<td>37</td>
</tr>
<tr class="odd">
<td>Arabic</td>
<td>120</td>
<td>44</td>
</tr>
<tr class="even">
<td>Hindi</td>
<td>296</td>
<td>54</td>
</tr>
<tr class="odd">
<td>Thai</td>
<td>260</td>
<td>63</td>
</tr>
<tr class="even">
<td>Yoruba</td>
<td>171</td>
<td>82</td>
</tr>
<tr class="odd">
<td>Amharic</td>
<td>309</td>
<td>206</td>
</tr>
</tbody>
</table>
<p>GPT-2’s tokenizer was learned mostly from English web pages, so everything else came out in tiny pieces. The newer one is far fairer, but Amharic still takes six times as many tokens as English to say the same thing, which means a bigger bill, a slower reply, and less room in the context window.</p>
</section>
<section id="predicting-the-next-token" class="level2" data-number="36.2">
<h2 data-number="36.2" class="anchored" data-anchor-id="predicting-the-next-token"><span class="header-section-number">36.2</span> Predicting the next token</h2>
<p>Once your text is a list of numbers, the model does one thing with it: for every token in its vocabulary, it computes how likely that token is to come next. One token is picked and added to the end, and the whole thing runs again; a 300-word answer is a few hundred trips around that loop. You can see one trip with <a href="https://en.wikipedia.org/wiki/GPT-2">GPT-2</a>, a small model OpenAI released in 2019 that runs fine on a laptop, using Hugging Face’s <a href="https://huggingface.co/docs/transformers/generation_strategies">Transformers</a> library (<code>pip install transformers torch</code>; the first run downloads about 550 MB):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> AutoModelForCausalLM, AutoTokenizer</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>tokenizer <span class="op">=</span> AutoTokenizer.from_pretrained(<span class="st">"gpt2"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> AutoModelForCausalLM.from_pretrained(<span class="st">"gpt2"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"My favorite thing to eat for breakfast is"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> tokenizer(prompt, return_tensors<span class="op">=</span><span class="st">"pt"</span>).input_ids</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> model(ids).logits[<span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>]      <span class="co"># one score per token in the vocabulary</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> torch.softmax(scores, dim<span class="op">=-</span><span class="dv">1</span>)      <span class="co"># scores -&gt; probabilities that sum to 1</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(probs), <span class="st">"possible next tokens"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> torch.topk(probs, <span class="dv">5</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p, i <span class="kw">in</span> <span class="bu">zip</span>(top.values, top.indices):</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>tokenizer<span class="sc">.</span>decode(<span class="bu">int</span>(i))<span class="sc">!r:12}</span><span class="ss"> </span><span class="sc">{</span>p<span class="sc">.</span>item()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>50257 possible next tokens
' a'         0.095
' the'       0.060
' bacon'     0.025
' spinach'   0.020
' chicken'   0.018</code></pre>
<p>That’s the whole output: a probability for each of 50,257 possible next tokens. There’s no lookup of facts and no plan for the rest of the sentence, just “given everything so far, what usually comes next?” The rest of this chapter is about what happens to that list.</p>
<p>Inside, each token ID becomes a vector, a long list of numbers (768 in GPT-2, 4,096 in a mid-sized model like <a href="https://huggingface.co/mistralai/Mistral-7B-v0.1">Mistral 7B</a>, which is where the meme’s number comes from). The vectors pass through a stack of layers built on the <a href="https://en.wikipedia.org/wiki/Transformer_(deep_learning_architecture)">transformer</a> design from the 2017 paper <a href="https://arxiv.org/abs/1706.03762">“Attention Is All You Need”</a>. Its key step, <em>attention</em>, updates each token’s vector by looking back at earlier tokens and weighing the ones that matter, which is how “it” gets connected to the noun it stands for. Training sets the millions or billions of numbers in those layers by nudging the model, over enormous amounts of text, toward predicting the real next token. Jay Alammar’s illustrated guide in Further reading is the gentlest way into the details.</p>
<p>A chat assistant is the same kind of model, trained further on example conversations and human ratings of its answers (<a href="../chapters/appendix-glossary.html#term-rlhf">RLHF</a>) so that the likeliest continuation of a question is a helpful answer. The chat app wraps your message in a template with roles and hidden instructions before the model sees it. It’s still predicting the next token; it has been shaped to predict an assistant’s.</p>
</section>
<section id="context-windows-why-it-forgets" class="level2" data-number="36.3">
<h2 data-number="36.3" class="anchored" data-anchor-id="context-windows-why-it-forgets"><span class="header-section-number">36.3</span> Context windows: why it “forgets”</h2>
<p>Here’s something that surprises almost everyone: the model has no memory between requests. Each time you send a message, the chat app sends the <em>entire</em> conversation so far, hidden instructions included, and the model reads it all from scratch. That bundle of tokens is the <strong>context window</strong>, and it’s everything the model knows about your task.</p>
<p>Every model limits how big that bundle can be. GPT-2’s limit was 1,024 tokens, about two pages. Anthropic’s <a href="https://platform.claude.com/docs/en/build-with-claude/context-windows">context windows guide</a> lists up to a million tokens for its current models. The limit counts everything: instructions, history, pasted documents, and the reply being written.</p>
<p>So why does a model “forget”? There are three different reasons. <strong>The window can fill up.</strong> An API request that’s too long comes back as an error (Anthropic’s says “prompt is too long”). Chat apps try to keep a long conversation going instead: depending on the app, they drop older turns, summarize them, or ask you to start over, and not all of them tell you. <strong>Long contexts get used unevenly.</strong> Even when everything fits, models use information in the middle of a long context worse than information at the start or end; a 2023 study called it getting <a href="https://arxiv.org/abs/2307.03172">“lost in the middle”</a>, and Anthropic’s guide calls the general decline as contexts grow <em>context rot</em>. <strong>A new conversation starts empty,</strong> unless the app has a memory feature that pastes notes back in.</p>
<p>The fixes follow from the causes. Restate the constraints that matter when a conversation runs long, or start fresh with a short summary. Paste the relevant part of a 10,000-line log, not the whole thing. Put the most important instructions at the beginning or end. And when you call an API, remember that sending the history is your code’s job.</p>
</section>
<section id="sampling-and-temperature-why-the-same-prompt-gives-different-answers" class="level2" data-number="36.4">
<h2 data-number="36.4" class="anchored" data-anchor-id="sampling-and-temperature-why-the-same-prompt-gives-different-answers"><span class="header-section-number">36.4</span> Sampling and temperature: why the same prompt gives different answers</h2>
<p>Something still has to choose one token from that list, and that choice is called <strong>sampling</strong>. Always taking the top token tends to produce flat, repetitive text, so usually the program draws at random, weighted by the probabilities. That’s why asking twice gets you two answers.</p>
<p><strong>Temperature</strong> controls how adventurous the draw is. Before the scores become probabilities (with the <a href="https://en.wikipedia.org/wiki/Softmax_function">softmax function</a>, the same step as in the GPT-2 code), they’re divided by the temperature. A low temperature stretches the gaps, so the favorite nearly always wins; a high one squashes them, so long shots get a chance. A few lines of <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">NumPy</a> show it:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>words <span class="op">=</span> [<span class="st">"pancakes"</span>, <span class="st">"eggs"</span>, <span class="st">"toast"</span>, <span class="st">"cereal"</span>, <span class="st">"broccoli"</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> np.array([<span class="fl">3.0</span>, <span class="fl">2.5</span>, <span class="fl">2.0</span>, <span class="fl">1.0</span>, <span class="op">-</span><span class="fl">1.0</span>])  <span class="co"># made-up scores for five candidates</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax(scores, temperature<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> scores <span class="op">/</span> temperature</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.exp(z <span class="op">-</span> z.<span class="bu">max</span>())  <span class="co"># subtracting the max avoids overflow; same result</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> e <span class="op">/</span> e.<span class="bu">sum</span>()</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> [<span class="fl">0.2</span>, <span class="fl">0.7</span>, <span class="fl">1.0</span>, <span class="fl">1.5</span>]:</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    probs <span class="op">=</span> softmax(scores, t)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"T=</span><span class="sc">{</span>t<span class="sc">}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">"  "</span>.join(<span class="ss">f"</span><span class="sc">{</span>w<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>p<span class="sc">:.2f}</span><span class="ss">"</span> <span class="cf">for</span> w, p <span class="kw">in</span> <span class="bu">zip</span>(words, probs)))</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> [<span class="fl">0.2</span>, <span class="fl">1.0</span>, <span class="fl">1.5</span>]:</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"8 draws at T=</span><span class="sc">{</span>t<span class="sc">}</span><span class="ss">:"</span>, <span class="st">" "</span>.join(rng.choice(words, size<span class="op">=</span><span class="dv">8</span>, p<span class="op">=</span>softmax(scores, t))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>T=0.2: pancakes 0.92  eggs 0.08  toast 0.01  cereal 0.00  broccoli 0.00
T=0.7: pancakes 0.56  eggs 0.27  toast 0.13  cereal 0.03  broccoli 0.00
T=1.0: pancakes 0.47  eggs 0.29  toast 0.17  cereal 0.06  broccoli 0.01
T=1.5: pancakes 0.39  eggs 0.28  toast 0.20  cereal 0.10  broccoli 0.03
8 draws at T=0.2: pancakes pancakes pancakes pancakes pancakes eggs pancakes pancakes
8 draws at T=1.0: pancakes pancakes pancakes toast eggs toast pancakes pancakes
8 draws at T=1.5: eggs pancakes toast eggs toast pancakes cereal cereal</code></pre>
<p>At 0.2, pancakes wins 92% of the time; at 1.5, even cereal gets picked. Temperature 0 is the limit: always take the top token, called greedy decoding. So keep it low for consistency (extraction, classification, code) and raise it for variety (brainstorming, alternative drafts). Where you can set it, OpenAI’s API takes 0 to 2 and Anthropic’s takes 0 to 1.</p>
<p>Two confusions come up constantly. First, <strong>temperature 0 still varies.</strong> In theory it’s deterministic; in practice hosted models give slightly different answers to identical requests, as Anthropic’s <a href="https://platform.claude.com/docs/en/api/messages">API reference</a> says outright. One reason is that computers round, so in <a href="https://en.wikipedia.org/wiki/Floating-point_arithmetic">floating-point arithmetic</a> the order you add numbers in changes the answer:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((<span class="fl">0.1</span> <span class="op">+</span> <span class="fl">0.2</span>) <span class="op">+</span> <span class="fl">0.3</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="fl">0.1</span> <span class="op">+</span> (<span class="fl">0.2</span> <span class="op">+</span> <span class="fl">0.3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>0.6000000000000001
0.6</code></pre>
<p>A server batching your request with other people’s may add things up in a different order depending on how busy it is, as a <a href="https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/">2025 write-up from Thinking Machines</a> explains. When two tokens are nearly tied, a difference in the last decimal place flips which one is “top,” and the rest of the answer follows a different path. Providers also update the model behind a name. So treat temperature 0 as “much less random,” never as “reproducible.”</p>
<p>Second, <strong>the newest models often won’t let you set it.</strong> Anthropic’s API reference says its newer models reject any temperature but the default, and other providers restrict it on some models too. If setting a temperature gets you a 400 error, check the model’s documentation.</p>
<p>Three related settings travel with temperature. <strong>Top-p</strong>, or <a href="https://en.wikipedia.org/wiki/Top-p_sampling">nucleus sampling</a>, draws only from the smallest set of tokens whose probabilities add up to p; providers suggest adjusting it or temperature, not both. <strong>Max tokens</strong> caps the reply’s length, and set too low it cuts the answer off mid-sentence. <strong>Stop sequences</strong> are strings, such as <code>END</code>, that end the reply as soon as the model writes one.</p>
</section>
<section id="embeddings-text-as-points-in-space" class="level2" data-number="36.5">
<h2 data-number="36.5" class="anchored" data-anchor-id="embeddings-text-as-points-in-space"><span class="header-section-number">36.5</span> Embeddings: text as points in space</h2>
<p>Embeddings are a different job: turning a piece of text into a fixed-length vector, arranged so that texts with similar meanings land close together. This is the meme at the top of the chapter taken literally, each text a point in a space of hundreds or thousands of dimensions. The idea started with single <a href="https://en.wikipedia.org/wiki/Word_embedding">word embeddings</a> and now covers whole documents. “Close” is usually measured with <a href="https://en.wikipedia.org/wiki/Cosine_similarity">cosine similarity</a>, which is 1 when two vectors point the same way and near 0 when they’re unrelated:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cosine(a, b):</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> a <span class="op">@</span> b <span class="op">/</span> (np.linalg.norm(a) <span class="op">*</span> np.linalg.norm(b))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>cat    <span class="op">=</span> np.array([<span class="fl">0.9</span>, <span class="fl">0.8</span>, <span class="fl">0.1</span>])   <span class="co"># made-up 3-number "embeddings"</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>kitten <span class="op">=</span> np.array([<span class="fl">0.8</span>, <span class="fl">0.9</span>, <span class="fl">0.2</span>])</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>tax    <span class="op">=</span> np.array([<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.9</span>])</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cat vs kitten: </span><span class="sc">{</span>cosine(cat, kitten)<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cat vs tax:    </span><span class="sc">{</span>cosine(cat, tax)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>cat vs kitten: 0.99
cat vs tax:    0.30</code></pre>
<p>Real embeddings have 384, 1,024, or 3,072 numbers that no one can interpret one by one, but the arithmetic is the same, and it powers a lot. <strong><a href="https://en.wikipedia.org/wiki/Semantic_search">Semantic search</a></strong> embeds a query and your documents and returns the closest, so “reduce memory usage” finds “optimize RAM consumption” with no words in common (the third worked example builds one). <strong><a href="https://en.wikipedia.org/wiki/Retrieval-augmented_generation">Retrieval-augmented generation</a></strong> (RAG) runs that search first and pastes the best passages into the model’s context, which is how “chat with your PDFs” tools handle collections bigger than any context window; the vectors usually live in a <a href="https://en.wikipedia.org/wiki/Vector_database">vector database</a>. Embeddings also let you cluster documents by topic without labels and find near-duplicate records.</p>
<p>They come from embedding models, which are separate from chat models and usually much cheaper. OpenAI has an <a href="https://developers.openai.com/api/docs/guides/embeddings">embeddings guide</a>; Anthropic doesn’t make an embedding model, and its <a href="https://platform.claude.com/docs/en/build-with-claude/embeddings">embeddings page</a> points to Voyage AI; and free models from <a href="https://sbert.net/">Sentence Transformers</a> run on a laptop. One rule catches people out: <strong>compare vectors only from the same model.</strong> Each model has its own space, and mixing them gives meaningless scores with no error to warn you.</p>
</section>
<section id="writing-prompts-that-work" class="level2" data-number="36.6">
<h2 data-number="36.6" class="anchored" data-anchor-id="writing-prompts-that-work"><span class="header-section-number">36.6</span> Writing prompts that work</h2>
<p>A prompt feels like a question, but to the model it’s the start of a document to continue, so everything in it shapes the answer. Keep that in mind and most prompting advice stops seeming like magic.</p>
<p>When you call a model from code, the input comes in <strong>roles</strong>. The <strong>system</strong> prompt holds standing instructions: who the model should be, what format to use, what to assume. <strong>User</strong> turns carry your requests and data, and <strong>assistant</strong> turns are the model’s earlier replies, sent back as history (you can also write some yourself, as examples). Some APIs once let you start the assistant’s reply for it (“The answer is:”) to steer the format; newer Claude models reject that, and structured-output features do the job instead. In a chat app the company writes the system prompt and mostly hides it; through an API it’s yours.</p>
<p>The habits that help follow from “it continues what you give it.” <strong>Be specific about the task and the reader:</strong> “Summarize this in three bullet points for someone with no statistics background,” not “Summarize this.” <strong>Name the format,</strong> and for machine-readable output use the providers’ structured-output features (<a href="https://platform.claude.com/docs/en/build-with-claude/structured-outputs">Anthropic</a>, <a href="https://developers.openai.com/api/docs/guides/structured-outputs">OpenAI</a>), which make the reply match a <a href="../chapters/appendix-glossary.html#term-json">JSON</a> schema. <strong>Show two or three examples</strong> of input and the output you want (few-shot prompting); for classifying, extracting, and rewriting, examples beat descriptions. <strong>Separate instructions from data</strong> with clear markers, such as XML-style tags or a line of <code>---</code>. <strong>Give it a role when that helps</strong> (“You are a careful code reviewer”), but one clear role beats a paragraph of competing ones.</p>
<p><strong>Let it reason before it answers</strong> on multi-step problems. Asking for the working first and the answer last, called <a href="https://arxiv.org/abs/2201.11903">chain-of-thought prompting</a>, helps because each token of reasoning becomes context for the next. Many current models have a built-in “thinking” or “reasoning” mode that does this on its own, so check the model’s documentation before adding the instruction. And <strong>change one thing at a time:</strong> keep a few test inputs, change one line, compare, and keep what helped. The prompt engineering guides in Further reading go further.</p>
</section>
<section id="chatbot-or-api" class="level2" data-number="36.7">
<h2 data-number="36.7" class="anchored" data-anchor-id="chatbot-or-api"><span class="header-section-number">36.7</span> Chatbot or API?</h2>
<p>A <strong>chat app</strong> like <a href="https://chatgpt.com/">ChatGPT</a>, <a href="https://claude.ai/">Claude</a>, or <a href="https://gemini.google.com/">Gemini</a> is a website or program you type into. An <strong>API</strong>, such as the <a href="https://platform.claude.com/docs/en/get-started">Claude API</a> or the <a href="https://developers.openai.com/api/docs/quickstart">OpenAI API</a>, lets your own code send a prompt and get the reply back as data. The model underneath is the same kind, but you get very different things:</p>
<table class="caption-top table">
<caption>What a chat app and an API give you.</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Chat app</th>
<th>API</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Getting started</td>
<td>Type and go</td>
<td>An account, a key, some code</td>
</tr>
<tr class="even">
<td>System prompt</td>
<td>Set by the company, mostly hidden</td>
<td>Yours to write</td>
</tr>
<tr class="odd">
<td>Memory</td>
<td>The app keeps the conversation</td>
<td>None: your code resends the history</td>
</tr>
<tr class="even">
<td>500 inputs</td>
<td>Paste 500 times</td>
<td>Write a loop</td>
</tr>
<tr class="odd">
<td>Extras (web search, files)</td>
<td>Usually included</td>
<td>Only what you turn on or build</td>
</tr>
<tr class="even">
<td>Cost</td>
<td>Free tier or a monthly plan</td>
<td>Per token, itemized on every call</td>
</tr>
</tbody>
</table>
<p>Use a chat app for one-off work: an explanation, a brainstorm, a first draft. Use the API when the same task has to run over many inputs, inside a script, with settings you control. A minimal call from Python (it needs <code>pip install anthropic</code> and an API key in the <code>ANTHROPIC_API_KEY</code> environment variable; see <a href="secrets.html" class="quarto-xref"><span>Chapter 34</span></a> for keeping keys out of code):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> anthropic  <span class="co"># reads your key from the ANTHROPIC_API_KEY environment variable</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> anthropic.Anthropic()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>message <span class="op">=</span> client.messages.create(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    model<span class="op">=</span><span class="st">"MODEL-NAME"</span>,  <span class="co"># copy a current model name from the provider's models page</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    max_tokens<span class="op">=</span><span class="dv">1024</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    system<span class="op">=</span><span class="st">"You are a patient statistics tutor. Answer in two sentences or fewer."</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    messages<span class="op">=</span>[</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        {<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: <span class="st">"What is the median of [3, 7, 2, 9, 5]?"</span>},</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">""</span>.join(block.text <span class="cf">for</span> block <span class="kw">in</span> message.content <span class="cf">if</span> block.<span class="bu">type</span> <span class="op">==</span> <span class="st">"text"</span>))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(message.usage.input_tokens, <span class="st">"tokens in,"</span>, message.usage.output_tokens, <span class="st">"tokens out"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The reply comes back as a list of <strong>content blocks</strong>, not a string, and on models with a thinking mode the first block may be the (usually hidden) reasoning, so the code keeps only the text blocks instead of grabbing <code>message.content[0]</code>. The <code>usage</code> numbers are what you’re billed for; printing them while you develop saves surprises.</p>
</section>
<section id="tools-and-function-calling-who-runs-the-code" class="level2" data-number="36.8">
<h2 data-number="36.8" class="anchored" data-anchor-id="tools-and-function-calling-who-runs-the-code"><span class="header-section-number">36.8</span> Tools and function calling: who runs the code?</h2>
<p>On its own, a model can only produce text; it can’t check the weather, run code, or query a database. <strong>Function calling</strong>, also called <strong>tool use</strong>, is how it gets those abilities, and the common misunderstanding is about who does the work: <em>the model never runs anything.</em> It writes a request, and your code decides whether to carry it out.</p>
<p><strong>First, you describe the tools</strong> you’re willing to run: a name, a plain-language description, and the arguments, written as a <a href="https://json-schema.org/learn/getting-started-step-by-step">JSON Schema</a>. Anthropic’s <a href="https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview">tool use guide</a> calls the schema <code>input_schema</code>; OpenAI’s <a href="https://developers.openai.com/api/docs/guides/function-calling">function calling guide</a> calls it <code>parameters</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"name"</span><span class="fu">:</span> <span class="st">"get_weather"</span><span class="fu">,</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"description"</span><span class="fu">:</span> <span class="st">"Returns the current weather for a city. Use it when the user asks about current conditions."</span><span class="fu">,</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"input_schema"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"object"</span><span class="fu">,</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"properties"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"city"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"string"</span><span class="fu">,</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"description"</span><span class="fu">:</span> <span class="st">"City name, e.g. Denver"</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">}</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">},</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"required"</span><span class="fu">:</span> <span class="ot">[</span><span class="st">"city"</span><span class="ot">]</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">}</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Next, the model decides.</strong> If a tool would help, it replies with a structured request instead of an answer, in effect “call <code>get_weather</code> with <code>city</code> set to <code>Boulder</code>.” It writes those arguments the way it writes anything, by predicting likely tokens, so they can be wrong. <strong>Then your code runs the function,</strong> if you decide it should, and sends back the result. <strong>Finally, the model writes its answer</strong> from that result.</p>
<p>Because every action passes through your code, you control what the model can touch. That’s also where the risk lives: a tool that deletes files or sends email will do exactly what the model asks, even when the model has misread the situation. Expose only what the task needs, and have a person approve anything hard to undo (see <a href="ai-llm.html" class="quarto-xref"><span>Chapter 35</span></a> for matching checks to risk). Running this round trip in a loop until the job is done is what makes an agent, the subject of <a href="ai-agents.html" class="quarto-xref"><span>Chapter 37</span></a>.</p>
</section>
<section id="why-models-state-false-things-fluently" class="level2" data-number="36.9">
<h2 data-number="36.9" class="anchored" data-anchor-id="why-models-state-false-things-fluently"><span class="header-section-number">36.9</span> Why models state false things fluently</h2>
<p>When a model confidently says something false, people call it a <a href="https://en.wikipedia.org/wiki/Hallucination_(artificial_intelligence)">hallucination</a>. The unsettling part is that it sounds exactly like the true answers, and once you remember what the model does, that stops being mysterious. Here’s GPT-2 asked about something that never happened, with sampling off so it always takes the likeliest token:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> AutoModelForCausalLM, AutoTokenizer</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>tokenizer <span class="op">=</span> AutoTokenizer.from_pretrained(<span class="st">"gpt2"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> AutoModelForCausalLM.from_pretrained(<span class="st">"gpt2"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> tokenizer(<span class="st">"The first person to walk on Mars was"</span>, return_tensors<span class="op">=</span><span class="st">"pt"</span>).input_ids</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> model.generate(ids, max_new_tokens<span class="op">=</span><span class="dv">12</span>, do_sample<span class="op">=</span><span class="va">False</span>,   <span class="co"># greedy: always the top token</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                     pad_token_id<span class="op">=</span>tokenizer.eos_token_id)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tokenizer.decode(out[<span class="dv">0</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>The first person to walk on Mars was a man named John Glenn.

The first person to</code></pre>
<p>No one has walked on Mars, and John Glenn orbited Earth. But “a man named” plus a famous astronaut is a likely way for that sentence to go on, and likely is all the model is built to produce. Modern assistants would almost certainly get this one right, but they fail the same way on questions where the mistake is harder to spot.</p>
<p>The causes stack up. <strong>The model predicts plausible text, not true text,</strong> so a false sentence and a true one come out in the same confident tone. <strong>Rare facts are learned poorly:</strong> a study of this <a href="https://arxiv.org/abs/2211.08411">“long tail”</a> found that models answer worse when the answer appears in few training documents, and in its place they produce something that fits the common pattern, like a plausible author for a paper. <strong>Training data stops at a date,</strong> the <a href="https://en.wikipedia.org/wiki/Knowledge_cutoff">knowledge cutoff</a>, so newer library versions and events are missing and the model fills in what used to be true. <strong>Guessing gets rewarded:</strong> a 2025 paper, <a href="https://arxiv.org/abs/2509.04664">“Why Language Models Hallucinate,”</a> argues that training and evaluation favor a confident guess over “I don’t know,” the way an exam with no penalty for wrong answers rewards guessing. And <strong>tokenization adds errors</strong> in spelling, counting, and arithmetic, as the strawberry example showed.</p>
<p>The practical responses follow:</p>
<ul>
<li>Check facts, citations, and numbers against a primary source before you use them.</li>
<li>Run code and test it; reading it isn’t enough.</li>
<li>Give the model the source material (paste the documentation, or use retrieval) instead of relying on its memory.</li>
<li>Ask what might be wrong; models often flag real uncertainty when asked directly, though not reliably.</li>
<li>Keep the temperature low for factual tasks, where you can set it.</li>
</ul>
</section>
<section id="stakes-and-politics" class="level2" data-number="36.10">
<h2 data-number="36.10" class="anchored" data-anchor-id="stakes-and-politics"><span class="header-section-number">36.10</span> Stakes and politics</h2>
<p>Article 1 of the Universal Declaration of Human Rights says that all human beings are born free and equal in dignity and rights. In the token table earlier in this chapter, that sentence costs 33 tokens in English and 206 in Amharic. Anyone paying by the token pays about six times as much to send it in Amharic, waits longer for the reply, and fits a sixth as much into the context window. <a href="https://arxiv.org/abs/2305.15425">Petrov and colleagues</a> found gaps of up to 15 times between languages. Nobody set out to charge Amharic speakers more; the tokenizer’s vocabulary was learned from text dominated by English and a few other widely published languages. It can change, too: Hindi went from 182 tokens with GPT-4’s tokenizer to 54 with GPT-4o’s, which shows these were design choices all along.</p>
<p>The same thing happens at every layer. The training text over-represents formal, published, English-language writing by people who write a lot online, so the model’s default voice is that corpus’s average. Embeddings carry the corpus’s associations: in 2016, <a href="https://arxiv.org/abs/1607.06520">Bolukbasi and colleagues</a> found that word embeddings trained on Google News completed “man is to computer programmer as woman is to ___” with “homemaker.” And only a few very well-funded companies can train frontier models, so a small group decides what those models read, how they’re tuned, and what they refuse; open-weights models like the GPT-2 you ran here spread the using, not the deciding. <a href="evaluating-ai.html" class="quarto-xref"><span>Chapter 38</span></a> covers how to test for gaps like these.</p>
<p>See <a href="artifacts-have-politics.html" class="quarto-xref"><span>Chapter 8</span></a> for the broader framework. The concrete prompt to carry forward: when a model “knows” something, or charges you more to say something, ask whose text it learned from.</p>
</section>
<section id="worked-examples" class="level2" data-number="36.11">
<h2 data-number="36.11" class="anchored" data-anchor-id="worked-examples"><span class="header-section-number">36.11</span> Worked examples</h2>
<section id="diagnosing-why-a-prompt-produces-inconsistent-output" class="level3">
<h3 class="anchored" data-anchor-id="diagnosing-why-a-prompt-produces-inconsistent-output">Diagnosing why a prompt produces inconsistent output</h3>
<p>A prompt “usually works” but sometimes returns garbage, and you want to know why before piling on more wording. <strong>Start by collecting evidence:</strong> save the prompt and a few bad outputs side by side, and count the prompt’s tokens; if you’re near the context window, that alone could be the cause. <strong>Next, take sampling out of the picture</strong> by setting the temperature to 0, if your model allows it, and running the prompt several times. If the outputs now agree, the inconsistency was sampling; if they still vary a lot, look elsewhere, such as a retrieval step that returns different documents each time. <strong>Then name the format</strong> (“Reply with JSON only, with the keys <code>summary</code> and <code>tags</code>”); format failures often vanish once the format is spelled out. <strong>If it still wanders, add one or two examples</strong> of exactly the output you want. After each step, write down which change fixed it; that note is the lesson worth keeping.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> anthropic</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> anthropic.Anthropic()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> call(prompt, temperature<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    settings <span class="op">=</span> {}</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> temperature <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Recent SDKs have no temperature= argument, and some models don't accept one,</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># so pass it through extra_body, to a model whose documentation says it does.</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>        settings[<span class="st">"extra_body"</span>] <span class="op">=</span> {<span class="st">"temperature"</span>: temperature}</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    message <span class="op">=</span> client.messages.create(</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        model<span class="op">=</span><span class="st">"MODEL-NAME"</span>,  <span class="co"># a model that accepts temperature</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>        max_tokens<span class="op">=</span><span class="dv">512</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>        messages<span class="op">=</span>[{<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: prompt}],</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>        <span class="op">**</span>settings,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">""</span>.join(block.text <span class="cf">for</span> block <span class="kw">in</span> message.content <span class="cf">if</span> block.<span class="bu">type</span> <span class="op">==</span> <span class="st">"text"</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"Summarize this abstract in one sentence: ..."</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(call(prompt, temperature<span class="op">=</span><span class="dv">0</span>))   <span class="co"># take sampling out of the picture</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(call(prompt <span class="op">+</span> <span class="st">"</span><span class="ch">\n\n</span><span class="st">Reply with JSON only, with the keys summary and tags."</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The comment in <code>call</code> is a lesson of its own: version 1 of Anthropic’s Python SDK has no <code>temperature</code> argument, and not every model accepts one. Settings that were standard a year ago can disappear, so when a call fails with an unexpected-argument error or a 400, check the current documentation before assuming your code is wrong.</p>
</section>
<section id="converting-a-chatbot-workflow-to-an-api-call" class="level3">
<h3 class="anchored" data-anchor-id="converting-a-chatbot-workflow-to-an-api-call">Converting a chatbot workflow to an API call</h3>
<p>For weeks you’ve pasted a document into a chat window, asked the same question, and copied the answer into a spreadsheet. Time to hand it to a script. <strong>Pull apart what you do by hand:</strong> the question you retype is standing instructions, and the pasted document is the part that changes. <strong>Move the standing part into a system prompt</strong> and send the document as the user turn. <strong>Make one call and compare it</strong> with an answer from the chat window, adjusting the system prompt until they agree, with <code>max_tokens</code> set so long answers aren’t cut off. <strong>Then make the input a parameter,</strong> a file path from the command line (see <a href="scripting.html" class="quarto-xref"><span>Chapter 17</span></a>), and loop over a folder. <strong>Log every input, output, and token count</strong> to a CSV so you can audit the results and the bill. Keep the API key in an environment variable, never in the script.</p>
</section>
<section id="building-a-simple-semantic-search-with-embeddings" class="level3">
<h3 class="anchored" data-anchor-id="building-a-simple-semantic-search-with-embeddings">Building a simple semantic search with embeddings</h3>
<p>You want to search documents by <em>meaning</em>, and see it work before paying for anything. A small free model from <a href="https://sbert.net/docs/quickstart.html">Sentence Transformers</a> runs on a laptop (<code>pip install sentence-transformers</code>; the model is a 90 MB download on first use):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sentence_transformers <span class="im">import</span> SentenceTransformer</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> SentenceTransformer(<span class="st">"all-MiniLM-L6-v2"</span>)  <span class="co"># small, free, runs on a laptop</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>docs <span class="op">=</span> [</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"How to reduce memory usage in pandas"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Optimizing RAM consumption for large DataFrames"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Baking sourdough bread at home"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"My notebook crashes when I load a big CSV file"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Choosing colors for a bar chart"</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>doc_vecs <span class="op">=</span> model.encode(docs)  <span class="co"># one row of numbers per document</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(doc_vecs.shape)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> search(query, k<span class="op">=</span><span class="dv">3</span>):</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> model.encode(query)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    sims <span class="op">=</span> doc_vecs <span class="op">@</span> q <span class="op">/</span> (np.linalg.norm(doc_vecs, axis<span class="op">=</span><span class="dv">1</span>) <span class="op">*</span> np.linalg.norm(q))</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    best <span class="op">=</span> np.argsort(sims)[::<span class="op">-</span><span class="dv">1</span>][:k]  <span class="co"># indexes of the k highest scores</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [(<span class="bu">float</span>(sims[i]), docs[i]) <span class="cf">for</span> i <span class="kw">in</span> best]</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> score, doc <span class="kw">in</span> search(<span class="st">"my laptop runs out of memory reading a huge spreadsheet"</span>):</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>score<span class="sc">:.2f}</span><span class="ss">  </span><span class="sc">{</span>doc<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>(5, 384)
0.60  My notebook crashes when I load a big CSV file
0.47  How to reduce memory usage in pandas
0.46  Optimizing RAM consumption for large DataFrames</code></pre>
<p>The top result shares none of the query’s key words (“laptop,” “memory,” “huge,” “spreadsheet”), so a keyword search would have missed it. To grow this into something real, embed your documents once and save the matrix (<code>np.save</code>), embed only the query at search time, use the same model for both, and test a few queries where you know the right answer against a plain keyword search to see where each wins.</p>
</section>
</section>
<section id="exercises" class="level2" data-number="36.12">
<h2 data-number="36.12" class="anchored" data-anchor-id="exercises"><span class="header-section-number">36.12</span> Exercises</h2>
<ol type="1">
<li>Tokenize a paragraph you wrote with tiktoken, then the same paragraph in another language. How do the counts compare, and what would the difference mean for cost and context space?</li>
<li>Tokenize “strawberry”, ” strawberry”, “Strawberry”, and a long word from your field. Then ask a chatbot to spell each one backwards. Does it do worse on words that split into more pieces?</li>
<li>Run the softmax code with your own made-up scores. At what temperature does the second-best option win at least one draw in ten? Then give the GPT-2 code a prompt from your field and look at the top five next tokens.</li>
<li>Write the same request (“Explain what a p-value is”) vaguely, then with a role, an audience, and a format. Compare the answers and describe what changed.</li>
<li>Write a system prompt and user prompt that produce JSON with the fields <code>summary</code>, <code>key_terms</code>, and <code>confidence</code>. Test it on three documents. Did the format hold every time? Before you put that <code>confidence</code> number in a table, know what it is: text the model wrote, by predicting likely tokens like everything else, not a probability it measured. It isn’t <a href="https://en.wikipedia.org/wiki/Calibration_(statistics)#In_probability_prediction_and_forecasting">calibrated</a>, so “0.9” doesn’t mean it’s right nine times in ten, and a <a href="https://arxiv.org/abs/2306.13063">2023 study</a> found that models stating their confidence this way tend to be overconfident. If you want to check, run the prompt on ten or so items where you already know the right answer and compare the stated confidence with how often the model was actually right.</li>
<li>Get a model to state something false with confidence, for example about an event after its knowledge cutoff or an obscure paper in your field. Which cause from this chapter explains it, and how would you check the right answer?</li>
<li>If you have API access, write a script that takes a question from the command line, sends it with your own system prompt, and prints the reply and token counts. Change the system prompt and confirm the answers change.</li>
</ol>
</section>
<section id="one-page-checklist" class="level2" data-number="36.13">
<h2 data-number="36.13" class="anchored" data-anchor-id="one-page-checklist"><span class="header-section-number">36.13</span> One-page checklist</h2>
<ul>
<li>The model reads tokens, not letters: check its spelling, letter counts, and arithmetic.</li>
<li>Count tokens with the provider’s own tool before sending anything long.</li>
<li>Put key instructions at the start or end, and restate them in long conversations.</li>
<li>Paste targeted excerpts, not whole files.</li>
<li>Keep the temperature low for consistency where you can set it, and never count on identical outputs.</li>
<li>Use a system prompt for standing instructions, name the format, and show examples.</li>
<li>Separate instructions from data with clear markers.</li>
<li>Compare embeddings only from the same model.</li>
<li>Use the API, not a chat window, when you need to loop, log, or control settings; keep keys in environment variables.</li>
<li>Expose only the tools a task needs, and have a person approve anything hard to undo.</li>
<li>Verify facts, citations, and code from a model against primary sources.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📚 Further reading
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Anthropic</strong>, <a href="https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview">Prompt engineering overview</a> — practical patterns for structuring prompts, with advice on testing them.</li>
<li><strong>OpenAI</strong>, <a href="https://developers.openai.com/api/docs/guides/prompt-engineering">Prompt engineering</a> — OpenAI’s parallel guide, including how to use system messages and examples.</li>
<li><strong>Jay Alammar</strong>, <a href="https://jalammar.github.io/illustrated-transformer/">The Illustrated Transformer</a> — the classic picture-by-picture explanation of attention; about half an hour that demystifies most of what happens inside the model.</li>
<li><strong>Andrej Karpathy</strong>, <a href="https://www.youtube.com/watch?v=kCc8FmEb1nY">Let’s build GPT: from scratch, in code, spelled out</a> — a two-hour video that builds a small transformer line by line; the deepest practical understanding most non-specialists will get.</li>
<li><strong>Hugging Face</strong>, <a href="https://huggingface.co/docs/transformers/index">Transformers documentation</a> — the library behind the GPT-2 examples in this chapter, with tutorials for running open models yourself.</li>
<li><strong>Anthropic</strong>, <a href="https://www.anthropic.com/news/mapping-mind-language-model">Mapping the Mind of a Large Language Model</a> — a readable summary of interpretability research on what the numbers inside a model represent.</li>
<li><strong>Emily M. Bender, Timnit Gebru, Angelina McMillan-Major, and Shmargaret Shmitchell</strong>, <a href="https://dl.acm.org/doi/10.1145/3442188.3445922">On the Dangers of Stochastic Parrots</a> (FAccT, 2021) — the widely cited critique of ever-larger language models, covering training data, cost, and who bears the risks; pairs with the Stakes section above.</li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ai-llm.html" class="pagination-link" aria-label="Using AI Tools">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Using AI Tools</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ai-agents.html" class="pagination-link" aria-label="Working with AI Agent Frameworks">
        <span class="nav-page-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Working with AI Agent Frameworks</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/edit/main/chapters/llm-internals.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>