<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>23&nbsp; SQL Basics – Missing Manual for Information Scientists</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/http-apis.html" rel="next">
<link href="../chapters/pandas-basics.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9a01bfd6df65136af83067365c1c6ba8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-eb8f170073725aebc42af3c4860b2e9c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9a01bfd6df65136af83067365c1c6ba8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../tools/chapter-meme/chapter-meme.css">
<link rel="stylesheet" href="../styles/layout.css">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/data-file-formats.html">Part IV — Working with Data</a></li><li class="breadcrumb-item"><a href="../chapters/sql-basics.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">SQL Basics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Missing Manual for Information Scientists</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/cuinfoscience/INFO-Missing-Manual" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/sharing/share-offsite/?url=|url|" title="LinkedIn" class="quarto-navigation-tool px-1" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Practice of Technical Work</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Asking Technical Questions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/documentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Technical Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/common-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Common Text Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-docs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reading Official Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Debugging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tracebacks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reading Python Tracebacks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/artifacts-have-politics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Artifacts Have Politics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Computing Environment</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/operating-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Operating System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/file-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Local File System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/terminal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Command Line</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/text-editors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Text Editors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/remote.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Remote Computing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Python Management</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/package-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Package Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/virtual-environments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Virtual Environments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Jupyter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/scripting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Scripting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/regex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regular Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/linting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Code Style</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Working with Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data-file-formats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data File Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/tabular-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Tabular Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/pandas-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">pandas Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/sql-basics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/http-apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">HTTP and Web APIs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V — Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/reading-scholarship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">How to Read Scholarly Articles and Books</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/writing-manuscripts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">How to Write Scholarly Manuscripts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/writing-thesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">How to Write a Thesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/presenting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">How to Present</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">How to Use LaTeX</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI — Project Management</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/project-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/version-control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Version Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/collaboration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Collaboration Mechanics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/automation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Automation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/secrets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Environment Variables and Secrets</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VII — Algorithmic Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ai-llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Using AI Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/llm-internals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">How Language Models Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ai-agents.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Working with AI Agent Frameworks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/evaluating-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Evaluating and Auditing AI Outputs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix-ai-disclosure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Disclosure: Use of AI in Authoring</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="../graphics/memes/sql-basics.png" class="chapter-meme img-fluid" alt="Boat cate Meme: I should build a database."></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#why-read-this-chapter" id="toc-why-read-this-chapter" class="nav-link" data-scroll-target="#why-read-this-chapter">Why read this chapter</a></li>
  <li><a href="#running-theme-sql-is-a-declarative-language-so-describe-what-you-want-not-how" id="toc-running-theme-sql-is-a-declarative-language-so-describe-what-you-want-not-how" class="nav-link" data-scroll-target="#running-theme-sql-is-a-declarative-language-so-describe-what-you-want-not-how">Running theme: SQL is a declarative language, so describe what you want, not how</a></li>
  <li><a href="#what-a-relational-database-is" id="toc-what-a-relational-database-is" class="nav-link" data-scroll-target="#what-a-relational-database-is"><span class="header-section-number">23.1</span> What a relational database is</a>
  <ul class="collapse">
  <li><a href="#build-the-practice-database" id="toc-build-the-practice-database" class="nav-link" data-scroll-target="#build-the-practice-database">Build the practice database</a></li>
  </ul></li>
  <li><a href="#select-...-from-the-basic-query" id="toc-select-...-from-the-basic-query" class="nav-link" data-scroll-target="#select-...-from-the-basic-query"><span class="header-section-number">23.2</span> <code>SELECT ... FROM</code>: the basic query</a></li>
  <li><a href="#where-filtering-rows" id="toc-where-filtering-rows" class="nav-link" data-scroll-target="#where-filtering-rows"><span class="header-section-number">23.3</span> <code>WHERE</code>: filtering rows</a>
  <ul class="collapse">
  <li><a href="#the-null-gotcha" id="toc-the-null-gotcha" class="nav-link" data-scroll-target="#the-null-gotcha">The <code>NULL</code> gotcha</a></li>
  </ul></li>
  <li><a href="#order-by-and-limit" id="toc-order-by-and-limit" class="nav-link" data-scroll-target="#order-by-and-limit"><span class="header-section-number">23.4</span> <code>ORDER BY</code> and <code>LIMIT</code></a></li>
  <li><a href="#aggregates-and-group-by" id="toc-aggregates-and-group-by" class="nav-link" data-scroll-target="#aggregates-and-group-by"><span class="header-section-number">23.5</span> Aggregates and <code>GROUP BY</code></a>
  <ul class="collapse">
  <li><a href="#count-and-countcolumn-arent-the-same" id="toc-count-and-countcolumn-arent-the-same" class="nav-link" data-scroll-target="#count-and-countcolumn-arent-the-same"><code>COUNT(*)</code> and <code>COUNT(column)</code> aren’t the same</a></li>
  <li><a href="#grouping" id="toc-grouping" class="nav-link" data-scroll-target="#grouping">Grouping</a></li>
  <li><a href="#the-group-by-error" id="toc-the-group-by-error" class="nav-link" data-scroll-target="#the-group-by-error">The <code>GROUP BY</code> error</a></li>
  </ul></li>
  <li><a href="#having-filtering-groups" id="toc-having-filtering-groups" class="nav-link" data-scroll-target="#having-filtering-groups"><span class="header-section-number">23.6</span> <code>HAVING</code>: filtering groups</a></li>
  <li><a href="#join-combining-tables" id="toc-join-combining-tables" class="nav-link" data-scroll-target="#join-combining-tables"><span class="header-section-number">23.7</span> <code>JOIN</code>: combining tables</a>
  <ul class="collapse">
  <li><a href="#when-a-join-multiplies-rows" id="toc-when-a-join-multiplies-rows" class="nav-link" data-scroll-target="#when-a-join-multiplies-rows">When a join multiplies rows</a></li>
  </ul></li>
  <li><a href="#running-sql-from-python" id="toc-running-sql-from-python" class="nav-link" data-scroll-target="#running-sql-from-python"><span class="header-section-number">23.8</span> Running SQL from Python</a>
  <ul class="collapse">
  <li><a href="#sqlite3-a-database-in-the-standard-library" id="toc-sqlite3-a-database-in-the-standard-library" class="nav-link" data-scroll-target="#sqlite3-a-database-in-the-standard-library"><code>sqlite3</code>: a database in the standard library</a></li>
  <li><a href="#from-sql-to-a-pandas-dataframe" id="toc-from-sql-to-a-pandas-dataframe" class="nav-link" data-scroll-target="#from-sql-to-a-pandas-dataframe">From SQL to a pandas DataFrame</a></li>
  <li><a href="#never-build-a-query-with-an-f-string" id="toc-never-build-a-query-with-an-f-string" class="nav-link" data-scroll-target="#never-build-a-query-with-an-f-string">Never build a query with an f-string</a></li>
  <li><a href="#duckdb-sql-on-files-and-dataframes" id="toc-duckdb-sql-on-files-and-dataframes" class="nav-link" data-scroll-target="#duckdb-sql-on-files-and-dataframes">DuckDB: SQL on files and DataFrames</a></li>
  </ul></li>
  <li><a href="#sql-or-pandas" id="toc-sql-or-pandas" class="nav-link" data-scroll-target="#sql-or-pandas"><span class="header-section-number">23.9</span> SQL or pandas?</a></li>
  <li><a href="#sql-pandas-translation-table" id="toc-sql-pandas-translation-table" class="nav-link" data-scroll-target="#sql-pandas-translation-table"><span class="header-section-number">23.10</span> SQL ↔︎ pandas translation table</a></li>
  <li><a href="#stakes-and-politics" id="toc-stakes-and-politics" class="nav-link" data-scroll-target="#stakes-and-politics"><span class="header-section-number">23.11</span> Stakes and politics</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples"><span class="header-section-number">23.12</span> Worked examples</a>
  <ul class="collapse">
  <li><a href="#top-customers-by-revenue" id="toc-top-customers-by-revenue" class="nav-link" data-scroll-target="#top-customers-by-revenue">Top customers by revenue</a></li>
  <li><a href="#customers-with-no-orders" id="toc-customers-with-no-orders" class="nav-link" data-scroll-target="#customers-with-no-orders">Customers with no orders</a></li>
  <li><a href="#counting-orders-per-customer-including-zero" id="toc-counting-orders-per-customer-including-zero" class="nav-link" data-scroll-target="#counting-orders-per-customer-including-zero">Counting orders per customer, including zero</a></li>
  <li><a href="#a-join-that-counted-alice-twice" id="toc-a-join-that-counted-alice-twice" class="nav-link" data-scroll-target="#a-join-that-counted-alice-twice">A join that counted Alice twice</a></li>
  <li><a href="#run-a-sql-query-and-chart-the-result" id="toc-run-a-sql-query-and-chart-the-result" class="nav-link" data-scroll-target="#run-a-sql-query-and-chart-the-result">Run a SQL query and chart the result</a></li>
  </ul></li>
  <li><a href="#templates" id="toc-templates" class="nav-link" data-scroll-target="#templates"><span class="header-section-number">23.13</span> Templates</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">23.14</span> Exercises</a></li>
  <li><a href="#one-page-checklist" id="toc-one-page-checklist" class="nav-link" data-scroll-target="#one-page-checklist"><span class="header-section-number">23.15</span> One-page checklist</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/edit/main/chapters/sql-basics.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/data-file-formats.html">Part IV — Working with Data</a></li><li class="breadcrumb-item"><a href="../chapters/sql-basics.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">SQL Basics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-sql-basics" class="quarto-section-identifier"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">SQL Basics</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Prerequisites and see-also
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Prerequisites (read first if unfamiliar):</strong> <a href="tabular-data.html" class="quarto-xref"><span>Chapter 21</span></a>.</p>
<p><strong>See also:</strong> <a href="pandas-basics.html" class="quarto-xref"><span>Chapter 22</span></a>, <a href="data-file-formats.html" class="quarto-xref"><span>Chapter 20</span></a>, <a href="http-apis.html" class="quarto-xref"><span>Chapter 24</span></a>.</p>
</div>
</div>
</div>
<section id="purpose" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="purpose">Purpose</h2>
<div class="chapter-meme-inline d-lg-none">
<p><img src="../graphics/memes/sql-basics.png" class="img-fluid" alt="Boat cate Meme: I should build a database."></p>
</div>
<p>Sooner or later, the data you need won’t come as a CSV. Your internship gives you a database login, or your lab keeps its survey responses in a <code>.db</code> file, and someone says “just pull what you need with SQL,” as if that were one step.</p>
<p>The good news: <a href="https://en.wikipedia.org/wiki/SQL">SQL</a> is a small language for how much it does. A handful of keywords cover most of what an analyst writes, and if you know pandas, you know the ideas under other names. The hard part is a few rules that, when you break them, give you a wrong answer instead of an error: how missing values compare, what <code>COUNT</code> counts, and what a join does when a key repeats.</p>
<p>This chapter builds a tiny practice database and runs every query against it, surprises included. You’ll filter, sort, summarize, and join; run SQL from Python with <a href="https://www.sqlite.org/docs.html">SQLite</a> and DuckDB; move results into pandas; and keep your code safe from SQL injection. Designing databases, tuning slow ones, and running a server such as <a href="https://www.postgresql.org/docs/current/tutorial.html">PostgreSQL</a> come later.</p>
</section>
<section id="why-read-this-chapter" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="why-read-this-chapter">Why read this chapter</h2>
<ul>
<li>Someone handed you a <code>.db</code> file or a database login, and “just write a query” was the whole instruction.</li>
<li>You wrote <code>WHERE city = NULL</code>, got zero rows back, and you know for a fact that some cities are missing.</li>
<li>Your query stopped with <code>column "name" must appear in the GROUP BY clause</code>, and you can’t tell what it wants.</li>
<li>You joined two tables, your revenue total went up, and you’d like to know which rows got counted twice.</li>
<li>Your code builds queries with f-strings, and it fell over the first time it met a customer named O’Brien.</li>
<li>You mix up <code>WHERE</code> and <code>HAVING</code>, or <code>COUNT(*)</code> and <code>COUNT(city)</code>, and get believable wrong numbers instead of errors.</li>
<li>You know pandas and want to know when SQL is the better tool, and how to move results between the two.</li>
</ul>
</section>
<section id="running-theme-sql-is-a-declarative-language-so-describe-what-you-want-not-how" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="running-theme-sql-is-a-declarative-language-so-describe-what-you-want-not-how">Running theme: SQL is a declarative language, so describe what you want, not how</h2>
<p>In Python you tell the computer <em>how</em>: loop over the rows, check each one, append the keepers. In SQL you describe the answer (“orders over $20, biggest first”), and the database’s <a href="https://en.wikipedia.org/wiki/Query_optimization">query planner</a> works out how to get it. Letting go of the “how” is most of what makes a <a href="https://en.wikipedia.org/wiki/Declarative_programming">declarative language</a> feel different.</p>
</section>
<section id="what-a-relational-database-is" class="level2" data-number="23.1">
<h2 data-number="23.1" class="anchored" data-anchor-id="what-a-relational-database-is"><span class="header-section-number">23.1</span> What a relational database is</h2>
<p>A <a href="https://en.wikipedia.org/wiki/Relational_database">relational database</a> is a set of tables, much like a set of DataFrames, that are linked to each other. Instead of one sheet where every order repeats the customer’s name and city, customers and orders get tables of their own, connected by a shared column. The idea comes from <a href="https://en.wikipedia.org/wiki/Edgar_F._Codd">Edgar F. Codd</a>’s 1970 paper on the <a href="https://en.wikipedia.org/wiki/Relational_model">relational model</a>, written at IBM, where SQL was developed a few years later. Here’s this chapter’s database, made up and tiny so you can check every answer by eye:</p>
<pre class="text"><code>customers
+-------------+-------+---------+
| customer_id | name  |  city   |
+-------------+-------+---------+
| 1           | Alice | Boulder |
| 2           | Bob   | Denver  |
| 3           | Carol | Boulder |
| 4           | Dana  | NULL    |
+-------------+-------+---------+

orders
+----------+-------------+--------+------------+
| order_id | customer_id | amount |    date    |
+----------+-------------+--------+------------+
| 101      | 1           | 29.99  | 2024-03-01 |
| 102      | 2           | 15.5   | 2024-03-02 |
| 103      | 1           | 42.0   | 2024-03-03 |
| 104      | 3           | 8.25   | 2024-03-03 |
| 105      | 1           | 61.0   | 2024-03-05 |
| 106      | NULL        | 12.0   | 2024-03-06 |
+----------+-------------+--------+------------+</code></pre>
<p><code>customer_id</code> is the <a href="https://en.wikipedia.org/wiki/Primary_key">primary key</a> of <code>customers</code>: no two customers share one. In <code>orders</code> it’s a <a href="https://en.wikipedia.org/wiki/Foreign_key">foreign key</a> pointing at whoever placed the order, so one customer can have many orders. Two rows make trouble on purpose, because real data does: Dana has no city, and order 106 (a guest checkout) has no customer. Both gaps are <code>NULL</code>, and they’re behind most of this chapter’s surprises.</p>
<p>Splitting data this way is called <a href="https://en.wikipedia.org/wiki/Database_normalization">normalization</a>: when Alice moves, you change one row, not every order she placed. The price is that most questions need the tables put back together, which is what <code>JOIN</code> is for.</p>
<section id="build-the-practice-database" class="level3">
<h3 class="anchored" data-anchor-id="build-the-practice-database">Build the practice database</h3>
<p>Save this script as <code>make_shop_db.py</code> and run it with <code>python make_shop_db.py</code>. It builds <code>shop.db</code> from scratch, so rerun it whenever you’ve made a mess.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> contextlib <span class="im">import</span> closing</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Path(<span class="st">"shop.db"</span>).unlink(missing_ok<span class="op">=</span><span class="va">True</span>)  <span class="co"># start fresh every time</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>customers <span class="op">=</span> [</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span>, <span class="st">"Alice"</span>, <span class="st">"Boulder"</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">2</span>, <span class="st">"Bob"</span>, <span class="st">"Denver"</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">3</span>, <span class="st">"Carol"</span>, <span class="st">"Boulder"</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">4</span>, <span class="st">"Dana"</span>, <span class="va">None</span>),  <span class="co"># None in Python becomes NULL in SQL</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>orders <span class="op">=</span> [</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">101</span>, <span class="dv">1</span>, <span class="fl">29.99</span>, <span class="st">"2024-03-01"</span>),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">102</span>, <span class="dv">2</span>, <span class="fl">15.50</span>, <span class="st">"2024-03-02"</span>),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">103</span>, <span class="dv">1</span>, <span class="fl">42.00</span>, <span class="st">"2024-03-03"</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">104</span>, <span class="dv">3</span>, <span class="fl">8.25</span>, <span class="st">"2024-03-03"</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">105</span>, <span class="dv">1</span>, <span class="fl">61.00</span>, <span class="st">"2024-03-05"</span>),</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">106</span>, <span class="va">None</span>, <span class="fl">12.00</span>, <span class="st">"2024-03-06"</span>),  <span class="co"># a guest checkout: no customer</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> closing(sqlite3.<span class="ex">connect</span>(<span class="st">"shop.db"</span>)) <span class="im">as</span> conn:</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    conn.executescript(<span class="st">"""</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="st">        CREATE TABLE customers (</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="st">            customer_id INTEGER PRIMARY KEY,</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="st">            name        TEXT NOT NULL,</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="st">            city        TEXT</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="st">        );</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="st">        CREATE TABLE orders (</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="st">            order_id    INTEGER PRIMARY KEY,</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="st">            customer_id INTEGER REFERENCES customers (customer_id),</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="st">            amount      REAL,</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="st">            date        TEXT</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="st">        );</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="st">    """</span>)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    conn.executemany(<span class="st">"INSERT INTO customers VALUES (?, ?, ?)"</span>, customers)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    conn.executemany(<span class="st">"INSERT INTO orders VALUES (?, ?, ?, ?)"</span>, orders)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    conn.commit()  <span class="co"># without this, the inserts vanish when the connection closes</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>?</code> marks are placeholders, filled in from the lists; they matter again when we get to SQL injection. And don’t skip <code>conn.commit()</code>: <code>sqlite3</code> holds your changes in a pending transaction and throws them away if the connection closes first, leaving two empty tables and no error.</p>
<p>To type queries, open the <a href="https://www.sqlite.org/cli.html">SQLite shell</a> with <code>sqlite3 shop.db</code> (many Macs and Linux machines have it; sqlite.org has downloads for the rest), or run them from Python, as shown later. The results here are what the shell prints after these two settings; the second shows missing values as <code>NULL</code> rather than a blank you could miss:</p>
<pre class="text"><code>$ sqlite3 shop.db
sqlite&gt; .mode table
sqlite&gt; .nullvalue NULL</code></pre>
<p>If you press Enter and get a <code>...&gt;</code> prompt instead of results, the shell is waiting for the semicolon that ends every statement. Type <code>;</code> and press Enter.</p>
</section>
</section>
<section id="select-...-from-the-basic-query" class="level2" data-number="23.2">
<h2 data-number="23.2" class="anchored" data-anchor-id="select-...-from-the-basic-query"><span class="header-section-number">23.2</span> <code>SELECT ... FROM</code>: the basic query</h2>
<p>Every query starts by naming the columns you want and the table they’re in:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> name, city</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> customers;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+-------+---------+
| name  |  city   |
+-------+---------+
| Alice | Boulder |
| Bob   | Denver  |
| Carol | Boulder |
| Dana  | NULL    |
+-------+---------+</code></pre>
<p><code>SELECT *</code> returns every column. It’s handy for a quick look, but in a script name the columns you need, because <code>*</code> changes what your query returns whenever the table’s <a href="../chapters/appendix-glossary.html#term-schema">schema</a> changes. Keywords aren’t case-sensitive (capitals are just a habit that makes queries easier to scan), and line breaks are up to you.</p>
<p>One rule trips up nearly everyone who comes from Python: <strong>text values go in single quotes.</strong> <code>'Boulder'</code> is text; <code>"Boulder"</code>, in double quotes, is the <em>name</em> of a column or table. SQLite hides the mistake by treating a double-quoted name that matches no column as text, a behavior it lists among its <a href="https://www.sqlite.org/quirks.html#dblquote">quirks</a>, so the habit works right up until it doesn’t. DuckDB stops with <code>Binder Error: Referenced column "Boulder" not found in FROM clause!</code>, PostgreSQL says <code>column "Boulder" does not exist</code>, and even SQLite gets <code>WHERE name = "name"</code> wrong: it compares each customer’s name with itself and returns all four.</p>
</section>
<section id="where-filtering-rows" class="level2" data-number="23.3">
<h2 data-number="23.3" class="anchored" data-anchor-id="where-filtering-rows"><span class="header-section-number">23.3</span> <code>WHERE</code>: filtering rows</h2>
<p><code>WHERE</code> keeps the rows that match a condition. Combine conditions with <code>AND</code>, <code>OR</code>, and <code>NOT</code>, and add parentheses when you mix <code>AND</code> with <code>OR</code>, since <code>AND</code> binds more tightly. Here are the orders over $20 from March 2 on:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> amount <span class="op">&gt;</span> <span class="dv">20</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> <span class="dt">date</span> <span class="op">&gt;=</span> <span class="st">'2024-03-02'</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+----------+-------------+--------+------------+
| order_id | customer_id | amount |    date    |
+----------+-------------+--------+------------+
| 103      | 1           | 42.0   | 2024-03-03 |
| 105      | 1           | 61.0   | 2024-03-05 |
+----------+-------------+--------+------------+</code></pre>
<p>That date comparison works only because of how the dates are written. SQLite has <a href="https://www.sqlite.org/datatype3.html#date_and_time_datatype">no date type</a>, so they’re plain text, and text written year-first (<a href="https://en.wikipedia.org/wiki/ISO_8601">ISO 8601</a>) sorts in date order. Written US-style, the comparison quietly fails: <code>'03/02/2024' &gt;= '2024-01-01'</code> is false, because <code>0</code> sorts before <code>2</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Operator</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>=</code>, <code>&lt;&gt;</code> or <code>!=</code></td>
<td>equals, not equals</td>
</tr>
<tr class="even">
<td><code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code></td>
<td>comparison (numbers, ISO dates, text)</td>
</tr>
<tr class="odd">
<td><code>BETWEEN x AND y</code></td>
<td>inclusive range</td>
</tr>
<tr class="even">
<td><code>IN ('a', 'b', 'c')</code></td>
<td>matches any value in the list</td>
</tr>
<tr class="odd">
<td><code>LIKE 'B%'</code></td>
<td>text pattern: <code>%</code> is any run of characters, <code>_</code> is one character</td>
</tr>
<tr class="even">
<td><code>IS NULL</code>, <code>IS NOT NULL</code></td>
<td>missing, not missing</td>
</tr>
</tbody>
</table>
<p>Details differ between databases: SQLite’s <a href="https://www.sqlite.org/lang_expr.html#like"><code>LIKE</code></a> ignores case for plain English letters, so <code>name LIKE 'c%'</code> finds Carol, while PostgreSQL’s finds nobody.</p>
<section id="the-null-gotcha" class="level3">
<h3 class="anchored" data-anchor-id="the-null-gotcha">The <code>NULL</code> gotcha</h3>
<p>This one catches everyone. You want the customers with no city, so you write the obvious thing:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> customers <span class="kw">WHERE</span> city <span class="op">=</span> <span class="kw">NULL</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>You get nothing back: no rows, no error, and Dana is sitting right there without a city. The reason is that <a href="https://en.wikipedia.org/wiki/Null_(SQL)"><code>NULL</code></a> isn’t a value. It means <em>unknown</em>, and any comparison with an unknown is itself unknown, even <code>NULL = NULL</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">NULL</span> <span class="op">=</span> <span class="kw">NULL</span>, <span class="kw">NULL</span> <span class="op">&lt;&gt;</span> <span class="st">'Boulder'</span>, <span class="dv">1</span> <span class="op">+</span> <span class="kw">NULL</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+-------------+-------------------+----------+
| NULL = NULL | NULL &lt;&gt; 'Boulder' | 1 + NULL |
+-------------+-------------------+----------+
| NULL        | NULL              | NULL     |
+-------------+-------------------+----------+</code></pre>
<p>SQL has three truth values, true, false, and unknown (<a href="https://en.wikipedia.org/wiki/Three-valued_logic">three-valued logic</a>), and <code>WHERE</code> keeps a row only when its condition is true. To ask about missing values, use the operators made for it: <code>WHERE city IS NULL</code> finds Dana, and <code>IS NOT NULL</code> finds everyone else.</p>
<p>The sneakier version gives you a plausible answer instead of an empty one. <code>WHERE city &lt;&gt; 'Boulder'</code> returns Bob alone, because whether Dana’s unknown city is “not Boulder” is also unknown. If you want the unknowns too, say so: <code>WHERE city &lt;&gt; 'Boulder' OR city IS NULL</code>. Whenever a column can be NULL, decide which side of the line the unknowns belong on.</p>
</section>
</section>
<section id="order-by-and-limit" class="level2" data-number="23.4">
<h2 data-number="23.4" class="anchored" data-anchor-id="order-by-and-limit"><span class="header-section-number">23.4</span> <code>ORDER BY</code> and <code>LIMIT</code></h2>
<p>A table has no built-in order: without <code>ORDER BY</code>, rows come back in whatever order suits the database, which can change as the table grows. Sorting is ascending unless you add <code>DESC</code>, <code>LIMIT</code> caps the rows returned, and <code>OFFSET</code> skips some first, for paging through results:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> orders</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> amount <span class="kw">DESC</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">3</span>;                 <span class="co">-- the three biggest: 105, 103, 101</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> orders</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dt">date</span>, order_id</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">2</span> OFFSET <span class="dv">2</span>;        <span class="co">-- skip two rows, return the next two: 103, 104</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Why sort by <code>order_id</code> too? Orders 103 and 104 share a date, so <code>ORDER BY date</code> alone doesn’t settle their order, and a row can land on two pages or none. Give any sort you page through a unique tiebreaker.</p>
</section>
<section id="aggregates-and-group-by" class="level2" data-number="23.5">
<h2 data-number="23.5" class="anchored" data-anchor-id="aggregates-and-group-by"><span class="header-section-number">23.5</span> Aggregates and <code>GROUP BY</code></h2>
<p>Most questions worth asking are summaries: how many, how much, on average. An <a href="https://en.wikipedia.org/wiki/Aggregate_function">aggregate function</a> collapses many rows into one value:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Function</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>COUNT(*)</code></td>
<td>number of rows</td>
</tr>
<tr class="even">
<td><code>COUNT(col)</code></td>
<td>number of non-NULL values in <code>col</code></td>
</tr>
<tr class="odd">
<td><code>SUM(col)</code></td>
<td>total</td>
</tr>
<tr class="even">
<td><code>AVG(col)</code></td>
<td>mean</td>
</tr>
<tr class="odd">
<td><code>MIN(col)</code>, <code>MAX(col)</code></td>
<td>smallest, largest</td>
</tr>
</tbody>
</table>
<p>Without <code>GROUP BY</code>, an aggregate covers the whole table, so <code>SELECT COUNT(*) AS n, SUM(amount) AS total FROM orders;</code> returns a single row: 6 orders, 168.74 in total. <code>AS</code> names the output column.</p>
<section id="count-and-countcolumn-arent-the-same" class="level3">
<h3 class="anchored" data-anchor-id="count-and-countcolumn-arent-the-same"><code>COUNT(*)</code> and <code>COUNT(column)</code> aren’t the same</h3>
<p>They look interchangeable, and on most tables they agree, which is why the difference bites late. <code>COUNT(*)</code> counts rows, <code>COUNT(city)</code> counts rows where <code>city</code> isn’t NULL, and <code>COUNT(DISTINCT city)</code> counts the different non-NULL values:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_rows,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">COUNT</span>(city) <span class="kw">AS</span> with_city,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">COUNT</span>(<span class="kw">DISTINCT</span> city) <span class="kw">AS</span> cities</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> customers;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+--------+-----------+--------+
| n_rows | with_city | cities |
+--------+-----------+--------+
| 4      | 3         | 2      |
+--------+-----------+--------+</code></pre>
<p>Three right answers to three different questions. <code>SUM</code> and <code>AVG</code> skip NULLs too, so <code>AVG</code> is the average of the values you have. The worked example “Counting orders per customer, including zero” shows the wrong count giving a wrong answer without a word of complaint.</p>
</section>
<section id="grouping" class="level3">
<h3 class="anchored" data-anchor-id="grouping">Grouping</h3>
<p>With <code>GROUP BY</code>, the aggregates run once per group. Here are orders and revenue per customer:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> customer_id, <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_orders, <span class="fu">SUM</span>(amount) <span class="kw">AS</span> total</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> customer_id;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+-------------+----------+--------+
| customer_id | n_orders | total  |
+-------------+----------+--------+
| NULL        | 1        | 12.0   |
| 1           | 3        | 132.99 |
| 2           | 1        | 15.5   |
| 3           | 1        | 8.25   |
+-------------+----------+--------+</code></pre>
<p>Look at the first row: SQL gathered the NULL keys into a group of their own. pandas’ <code>groupby</code> leaves them out unless you pass <code>dropna=False</code>, one of the silent row losses <a href="tabular-data.html" class="quarto-xref"><span>Chapter 21</span></a> warns about.</p>
</section>
<section id="the-group-by-error" class="level3">
<h3 class="anchored" data-anchor-id="the-group-by-error">The <code>GROUP BY</code> error</h3>
<p>Here’s the error from the top of the chapter. You’re counting customers per city, and you decide to show their names too:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- BAD: name is neither grouped nor aggregated</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> city, name, <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> customers</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> city;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>DuckDB refuses with <code>Binder Error: column "name" must appear in the GROUP BY clause or must be part of an aggregate function.</code>, and PostgreSQL’s message is nearly the same. It sounds like bureaucracy until you think about what you asked for. Grouping makes each city one row, and Boulder has two customers, so whose name goes in Boulder’s row? SQLite doesn’t ask; it picks one, a documented behavior it calls <a href="https://www.sqlite.org/lang_select.html#bareagg">bare columns</a>:</p>
<pre class="text"><code>+---------+-------+---+
|  city   | name  | n |
+---------+-------+---+
| NULL    | Dana  | 1 |
| Boulder | Alice | 2 |
| Denver  | Bob   | 1 |
+---------+-------+---+</code></pre>
<p>Now Alice seems to be two customers. The rule, in every database: <strong>each column in <code>SELECT</code> is either in <code>GROUP BY</code> or inside an aggregate.</strong> Group by it too (<code>GROUP BY city, name</code>), or aggregate it: <code>GROUP_CONCAT(name)</code> in SQLite or <code>string_agg(name, ',')</code> in DuckDB and PostgreSQL lists the names as <code>Alice,Carol</code>, and <code>MIN(name)</code> works when every row in the group has the same value.</p>
</section>
</section>
<section id="having-filtering-groups" class="level2" data-number="23.6">
<h2 data-number="23.6" class="anchored" data-anchor-id="having-filtering-groups"><span class="header-section-number">23.6</span> <code>HAVING</code>: filtering groups</h2>
<p>To find customers with more than one order, you’d naturally try <code>WHERE COUNT(*) &gt; 1</code>, and SQLite stops with <code>misuse of aggregate: COUNT()</code> (PostgreSQL: <code>aggregate functions are not allowed in WHERE</code>). The reason is the order SQL works in. You write <code>SELECT</code> first, but conceptually the database takes <code>FROM</code>, then <code>WHERE</code>, <code>GROUP BY</code>, <code>HAVING</code>, <code>SELECT</code>, and last <code>ORDER BY</code> and <code>LIMIT</code>. <code>WHERE</code> sees single rows before any groups exist; <a href="https://en.wikipedia.org/wiki/Having_(SQL)"><code>HAVING</code></a> filters whole groups afterwards. You’ll often use both. “Among orders of $30 or more, which customers placed more than one?”:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> customer_id, <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_orders</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> amount <span class="op">&gt;=</span> <span class="dv">30</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> customer_id</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="kw">HAVING</span> <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="op">&gt;</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>It returns customer 1, with 2 orders. <code>WHERE</code> dropped small orders one by one, <code>GROUP BY</code> gathered the rest, and <code>HAVING</code> kept groups with more than one row. Rows go through <code>WHERE</code>; groups go through <code>HAVING</code>.</p>
</section>
<section id="join-combining-tables" class="level2" data-number="23.7">
<h2 data-number="23.7" class="anchored" data-anchor-id="join-combining-tables"><span class="header-section-number">23.7</span> <code>JOIN</code>: combining tables</h2>
<p>Normalization split customers and orders apart; a <a href="https://en.wikipedia.org/wiki/Join_(SQL)">join</a> puts them back together. Here is each order with the name and city of whoever placed it:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> o.order_id, o.amount, c.name, c.city</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders o</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="kw">JOIN</span> customers c <span class="kw">ON</span> o.customer_id <span class="op">=</span> c.customer_id;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+----------+--------+-------+---------+
| order_id | amount | name  |  city   |
+----------+--------+-------+---------+
| 101      | 29.99  | Alice | Boulder |
| 102      | 15.5   | Bob   | Denver  |
| 103      | 42.0   | Alice | Boulder |
| 104      | 8.25   | Carol | Boulder |
| 105      | 61.0   | Alice | Boulder |
+----------+--------+-------+---------+</code></pre>
<p><code>orders o</code> and <code>customers c</code> are short aliases, so <code>o.amount</code> means <code>orders.amount</code>, and the prefix says which table’s <code>customer_id</code> you mean. <code>ON</code> says how to pair rows.</p>
<p>Now count: six orders went in and five came out. A plain <code>JOIN</code> is an <strong>inner join</strong>, keeping only rows that find a partner, and order 106 has none. (Dana, with no orders, is missing too.) For “every order, with customer details where they exist,” use a <code>LEFT JOIN</code>, which keeps every row of the first table and fills gaps with NULL; this returns all six orders, with a <code>NULL</code> name for 106:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> o.order_id, o.amount, c.name</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders o</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> customers c <span class="kw">ON</span> o.customer_id <span class="op">=</span> c.customer_id;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Keeps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>JOIN</code> or <code>INNER JOIN</code></td>
<td>only rows that match in both tables</td>
</tr>
<tr class="even">
<td><code>LEFT JOIN</code></td>
<td>every row of the left table, NULL where the right has no match</td>
</tr>
<tr class="odd">
<td><code>RIGHT JOIN</code></td>
<td>every row of the right table</td>
</tr>
<tr class="even">
<td><code>FULL OUTER JOIN</code></td>
<td>every row of both</td>
</tr>
</tbody>
</table>
<p>Inner and left joins cover nearly everything (SQLite only added <code>RIGHT</code> and <code>FULL OUTER</code> in version 3.39, in 2022). When the key has the same name in both tables, <code>USING (customer_id)</code> can replace the <code>ON</code> clause, as later examples do, and you get one <code>customer_id</code> column instead of two.</p>
<section id="when-a-join-multiplies-rows" class="level3">
<h3 class="anchored" data-anchor-id="when-a-join-multiplies-rows">When a join multiplies rows</h3>
<p>A join pairs each left row with <em>every</em> matching right row, so a key that appears twice on the right doubles its rows, and every sum over them. It’s the pandas merge trap from <a href="tabular-data.html" class="quarto-xref"><span>Chapter 21</span></a>, with the same defense: count rows before and after, and check that the key is unique where you assume it is.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> customer_id, <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> customers</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> customer_id</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="kw">HAVING</span> <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="op">&gt;</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>An empty result is what you want. A declared primary key guarantees it, but tables you’re handed often declare none. pandas’ <code>validate="many_to_one"</code> runs this check for you; in SQL you run it yourself. The worked example “A join that counted Alice twice” shows what skipping it costs.</p>
</section>
</section>
<section id="running-sql-from-python" class="level2" data-number="23.8">
<h2 data-number="23.8" class="anchored" data-anchor-id="running-sql-from-python"><span class="header-section-number">23.8</span> Running SQL from Python</h2>
<section id="sqlite3-a-database-in-the-standard-library" class="level3">
<h3 class="anchored" data-anchor-id="sqlite3-a-database-in-the-standard-library"><code>sqlite3</code>: a database in the standard library</h3>
<p>SQLite is a whole database in one file, with no server to run, and Python comes with the <code>sqlite3</code> module for talking to it (see the official <a href="https://docs.python.org/3/library/sqlite3.html#tutorial"><code>sqlite3</code> tutorial</a>). Every script has this shape:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> contextlib <span class="im">import</span> closing</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> closing(sqlite3.<span class="ex">connect</span>(<span class="st">"shop.db"</span>)) <span class="im">as</span> conn:</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> conn.execute(<span class="st">"""</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="st">        SELECT customer_id, COUNT(*) AS n_orders</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="st">        FROM orders</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="st">        GROUP BY customer_id</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">        ORDER BY n_orders DESC</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="st">    """</span>).fetchall()</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> rows:</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(row)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>(1, 3)
(3, 1)
(2, 1)
(None, 1)</code></pre>
<p>Rows come back as tuples, with <code>None</code> for NULL. (The three groups with one order each tie, so their order isn’t fixed.)</p>
<p>Two snags catch people here. Many tutorials write <code>with sqlite3.connect("shop.db") as conn:</code> and assume the connection closes at the end of the block. It doesn’t: that block commits or rolls back your changes, and in the Python docs’ words it “neither implicitly opens a new transaction nor closes the connection.” <a href="https://docs.python.org/3/library/contextlib.html#contextlib.closing"><code>contextlib.closing</code></a>, as above, is what closes it. The other snag is a typo: <code>sqlite3.connect("shpo.db")</code> quietly creates a new, empty database, and your query fails with <code>no such table: orders</code> while you stare at a table you know exists. To read an existing file, open it read-only, and a wrong name fails at once with <code>unable to open database file</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>conn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">"file:shop.db?mode=ro"</span>, uri<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="from-sql-to-a-pandas-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="from-sql-to-a-pandas-dataframe">From SQL to a pandas DataFrame</h3>
<p>For analysis you usually want a DataFrame, and <a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html"><code>pd.read_sql_query</code></a> gives you one. Let the database do the filtering and joining, and bring back only the slice you need:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> contextlib <span class="im">import</span> closing</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> closing(sqlite3.<span class="ex">connect</span>(<span class="st">"shop.db"</span>)) <span class="im">as</span> conn:</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="st">        SELECT o.order_id, o.amount, c.name, c.city</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="st">        FROM orders o</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="st">        JOIN customers c USING (customer_id)</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="st">        WHERE o.date &gt;= '2024-03-02'</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>        conn,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>   order_id  amount   name     city
0       102   15.50    Bob   Denver
1       103   42.00  Alice  Boulder
2       104    8.25  Carol  Boulder
3       105   61.00  Alice  Boulder</code></pre>
<p>From here it’s ordinary pandas (see <a href="pandas-basics.html" class="quarto-xref"><span>Chapter 22</span></a>). pandas accepts a <code>sqlite3</code> connection directly; other databases, such as PostgreSQL, usually go through SQLAlchemy. One surprise: an integer column that contains NULLs, like <code>orders.customer_id</code>, arrives as floats (<code>1.0</code>, <code>NaN</code>), because a NumPy integer column can’t hold a missing value.</p>
</section>
<section id="never-build-a-query-with-an-f-string" class="level3">
<h3 class="anchored" data-anchor-id="never-build-a-query-with-an-f-string">Never build a query with an f-string</h3>
<p>When a query depends on a variable, such as a city someone typed, an f-string seems to work:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>city <span class="op">=</span> <span class="st">"Boulder"</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>conn.execute(<span class="ss">f"SELECT * FROM customers WHERE city = '</span><span class="sc">{</span>city<span class="sc">}</span><span class="ss">'"</span>).fetchall()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># [(1, 'Alice', 'Boulder'), (3, 'Carol', 'Boulder')]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Then a value contains a quote mark. Look up the name <code>O'Brien</code> this way and Python builds <code>WHERE name = 'O'Brien'</code>, which SQLite rejects with <code>sqlite3.OperationalError: near "Brien": syntax error</code>. That’s the friendly failure. The unfriendly one is someone typing this as their city:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>city <span class="op">=</span> <span class="st">"x' OR '1'='1"</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>conn.execute(<span class="ss">f"SELECT * FROM customers WHERE city = '</span><span class="sc">{</span>city<span class="sc">}</span><span class="ss">'"</span>).fetchall()</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># [(1, 'Alice', 'Boulder'), (2, 'Bob', 'Denver'), (3, 'Carol', 'Boulder'), (4, 'Dana', None)]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The input rewrote your query into “city is <code>x</code>, or one equals one,” true for every row. That’s <a href="https://en.wikipedia.org/wiki/SQL_injection">SQL injection</a>, the joke in xkcd’s <a href="https://xkcd.com/327/">Bobby Tables comic</a> and the cause of real data breaches. The fix is a <strong>placeholder</strong>: put <code>?</code> where the value goes and pass the values separately, as a tuple:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>conn.execute(<span class="st">"SELECT * FROM customers WHERE city = ?"</span>, (city,)).fetchall()</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># []</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The value never becomes part of the SQL, so the attack string is just a city nobody lives in, and <code>O'Brien</code> is just a name. See the Python docs on <a href="https://docs.python.org/3/library/sqlite3.html#sqlite3-placeholders">placeholders</a> and OWASP’s <a href="https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html">prevention cheat sheet</a>, and use placeholders for every value, even ones you “know” are safe.</p>
<p>Two snags. Leave the comma off <code>(city,)</code> and Python passes a plain string, which counts as one value per character: <code>Incorrect number of bindings supplied. The current statement uses 1, and there are 7 supplied.</code> And placeholders stand for values only, never table or column names (<code>SELECT * FROM ?</code> is a syntax error); if a script must choose a table, check the name against a list you wrote.</p>
</section>
<section id="duckdb-sql-on-files-and-dataframes" class="level3">
<h3 class="anchored" data-anchor-id="duckdb-sql-on-files-and-dataframes">DuckDB: SQL on files and DataFrames</h3>
<p><a href="https://duckdb.org/docs/stable/clients/python/overview">DuckDB</a> also runs inside Python with no server (<code>python -m pip install duckdb</code>), but it’s built for analysis, and it runs SQL directly on CSV and Parquet files and pandas DataFrames, just by naming them (<a href="data-file-formats.html" class="quarto-xref"><span>Chapter 20</span></a> uses it on a file too big to load). Export the orders with <code>sqlite3 -header -csv shop.db "SELECT * FROM orders" &gt; orders.csv</code>, and join that file to a DataFrame:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> duckdb</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>customers <span class="op">=</span> pd.DataFrame({</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"customer_id"</span>: [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>],</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"name"</span>: [<span class="st">"Alice"</span>, <span class="st">"Bob"</span>, <span class="st">"Carol"</span>, <span class="st">"Dana"</span>],</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"city"</span>: [<span class="st">"Boulder"</span>, <span class="st">"Denver"</span>, <span class="st">"Boulder"</span>, <span class="va">None</span>],</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT c.name, COUNT(*) AS n_orders, SUM(o.amount) AS total</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM 'orders.csv' o</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="st">    JOIN customers c USING (customer_id)</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY c.name</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY total DESC</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>).show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>┌─────────┬──────────┬────────┐
│  name   │ n_orders │ total  │
│ varchar │  int64   │ double │
├─────────┼──────────┼────────┤
│ Alice   │        3 │ 132.99 │
│ Bob     │        1 │   15.5 │
│ Carol   │        1 │   8.25 │
└─────────┴──────────┴────────┘</code></pre>
<p>Swap <code>.show()</code> for <code>.df()</code> to get a DataFrame back (see DuckDB’s guide to <a href="https://duckdb.org/docs/stable/guides/python/sql_on_pandas">SQL on pandas</a>). DuckDB is also stricter than SQLite, a kindness while you learn: it caught the double quotes and the ungrouped column earlier.</p>
</section>
</section>
<section id="sql-or-pandas" class="level2" data-number="23.9">
<h2 data-number="23.9" class="anchored" data-anchor-id="sql-or-pandas"><span class="header-section-number">23.9</span> SQL or pandas?</h2>
<p>You don’t have to pick a side. SQL earns its place when the data lives in a database: it can discard most rows and do the joins before anything reaches your laptop, which matters when full tables won’t fit in memory, and a teammate who doesn’t read Python can still review a query. pandas is better once the data is in memory and modest in size: reshaping with <code>pivot</code> and <code>melt</code>, plotting, cleaning messy strings, building features, exploring in a notebook. The usual pattern uses both: SQL selects and joins, <code>read_sql_query</code> hands over the result, and pandas does the rest.</p>
<p>Check your numbers when you cross over, because the two treat missing values differently. SQL groups NULL keys together; pandas’ <code>groupby</code> drops them. SQL never matches NULL to NULL in a join; pandas’ <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html"><code>merge</code></a> does, which its docs warn “is different from usual SQL join behaviour.” And <code>WHERE city &lt;&gt; 'Boulder'</code> leaves Dana out, while <code>customers[customers["city"] != "Boulder"]</code> keeps her.</p>
</section>
<section id="sql-pandas-translation-table" class="level2" data-number="23.10">
<h2 data-number="23.10" class="anchored" data-anchor-id="sql-pandas-translation-table"><span class="header-section-number">23.10</span> SQL ↔︎ pandas translation table</h2>
<p>Here <code>t</code> is a table and <code>df</code> holds the same data as a DataFrame; each SQL piece goes in its usual place in a full query. pandas’ own <a href="https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html">comparison with SQL</a> has many more examples.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>SQL</th>
<th>pandas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>SELECT * FROM t</code></td>
<td><code>df</code></td>
</tr>
<tr class="even">
<td><code>SELECT a, b</code></td>
<td><code>df[["a", "b"]]</code></td>
</tr>
<tr class="odd">
<td><code>WHERE a &gt; 5</code></td>
<td><code>df[df["a"] &gt; 5]</code></td>
</tr>
<tr class="even">
<td><code>WHERE a IS NULL</code></td>
<td><code>df[df["a"].isna()]</code></td>
</tr>
<tr class="odd">
<td><code>ORDER BY a DESC</code></td>
<td><code>df.sort_values("a", ascending=False)</code></td>
</tr>
<tr class="even">
<td><code>LIMIT 10</code></td>
<td><code>df.head(10)</code></td>
</tr>
<tr class="odd">
<td><code>COUNT(*)</code></td>
<td><code>len(df)</code></td>
</tr>
<tr class="even">
<td><code>COUNT(x)</code></td>
<td><code>df["x"].count()</code></td>
</tr>
<tr class="odd">
<td><code>AVG(x)</code></td>
<td><code>df["x"].mean()</code></td>
</tr>
<tr class="even">
<td><code>GROUP BY k</code> with <code>COUNT(*)</code></td>
<td><code>df.groupby("k").size()</code></td>
</tr>
<tr class="odd">
<td><code>GROUP BY k</code> with <code>SUM(x)</code></td>
<td><code>df.groupby("k")["x"].sum()</code></td>
</tr>
<tr class="even">
<td><code>JOIN t2 USING (k)</code></td>
<td><code>df.merge(df2, on="k")</code></td>
</tr>
<tr class="odd">
<td><code>LEFT JOIN t2 USING (k)</code></td>
<td><code>df.merge(df2, on="k", how="left")</code></td>
</tr>
<tr class="even">
<td><code>SELECT DISTINCT k</code></td>
<td><code>df["k"].unique()</code></td>
</tr>
</tbody>
</table>
</section>
<section id="stakes-and-politics" class="level2" data-number="23.11">
<h2 data-number="23.11" class="anchored" data-anchor-id="stakes-and-politics"><span class="header-section-number">23.11</span> Stakes and politics</h2>
<p>For decades, U.S. federal forms had no box for people with roots in the Middle East or North Africa: under the government’s race and ethnicity standards, someone whose family came from Lebanon, Egypt, or Iran was counted as White, whether or not they saw themselves that way. In March 2024, the Office of Management and Budget <a href="https://en.wikipedia.org/wiki/Race_and_ethnicity_in_the_United_States_census">revised those standards</a> to add a Middle Eastern or North African category. That’s a schema change, one new allowed value in a column, and it took years because agencies, surveys, and funding formulas were built on the old list.</p>
<p>The tables you design or query make the same kind of choice on a smaller scale. A required <code>first_name</code> and <code>last_name</code> pair fits some <a href="https://www.w3.org/International/questions/qa-personal-names">naming traditions</a> and not others. A <code>gender</code> column that allows two values records everyone else as missing or wrong. A <code>country</code> column limited to a fixed list of <a href="https://en.wikipedia.org/wiki/ISO_3166-1">ISO 3166</a> codes has taken a position on disputed places before anyone asks a question.</p>
<p>Once a schema is in use it tends to stay, because every dashboard and pipeline downstream builds in its assumptions; changing a column costs far more than choosing one did. A schema also makes the questions it was designed for cheap and the rest expensive, and expensive questions often go unasked. The politics sit in choices that look like data types (which columns are <code>NOT NULL</code>, which values are allowed, what counts as one person), and the cost of not fitting falls on whoever doesn’t fit, not on whoever designed the table.</p>
<p>See <a href="artifacts-have-politics.html" class="quarto-xref"><span>Chapter 8</span></a> for the broader framework. The concrete prompt to carry forward: when you read a schema, ask whose categories it embeds and what kinds of people, places, or events would not fit its columns cleanly.</p>
</section>
<section id="worked-examples" class="level2" data-number="23.12">
<h2 data-number="23.12" class="anchored" data-anchor-id="worked-examples"><span class="header-section-number">23.12</span> Worked examples</h2>
<section id="top-customers-by-revenue" class="level3">
<h3 class="anchored" data-anchor-id="top-customers-by-revenue">Top customers by revenue</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> c.name, <span class="fu">SUM</span>(o.amount) <span class="kw">AS</span> total</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders o</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="kw">JOIN</span> customers c <span class="kw">USING</span> (customer_id)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> o.<span class="dt">date</span> <span class="op">&gt;=</span> <span class="st">'2024-03-01'</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> c.name</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="kw">HAVING</span> <span class="fu">SUM</span>(o.amount) <span class="op">&gt;</span> <span class="dv">10</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> total <span class="kw">DESC</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+-------+--------+
| name  | total  |
+-------+--------+
| Alice | 132.99 |
| Bob   | 15.5   |
+-------+--------+</code></pre>
<p>Read it in the order the database works: from orders joined to customers, keep rows dated March 1 or later, group by name, keep groups whose total is over 10, sort biggest first, return at most ten. Carol’s $8.25 fell below the <code>HAVING</code> line, and the guest order never survived the inner join. On a real table, group by <code>c.customer_id, c.name</code>, since two customers can share a name.</p>
</section>
<section id="customers-with-no-orders" class="level3">
<h3 class="anchored" data-anchor-id="customers-with-no-orders">Customers with no orders</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> c.customer_id, c.name</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> customers c</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> orders o <span class="kw">ON</span> c.customer_id <span class="op">=</span> o.customer_id</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> o.order_id <span class="kw">IS</span> <span class="kw">NULL</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This returns Dana alone. The <code>LEFT JOIN</code> keeps every customer, with NULL in every <code>o.</code> column for those who never ordered, and <code>WHERE o.order_id IS NULL</code> keeps only those. Finding rows with <em>no</em> match this way is called an anti-join; it’s how you find students who never submitted or sensors that never reported.</p>
</section>
<section id="counting-orders-per-customer-including-zero" class="level3">
<h3 class="anchored" data-anchor-id="counting-orders-per-customer-including-zero">Counting orders per customer, including zero</h3>
<p>You want a count for every customer, Dana’s zero included, so you use a <code>LEFT JOIN</code> and reach for <code>COUNT(*)</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> c.name,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> count_star,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">COUNT</span>(o.order_id) <span class="kw">AS</span> n_orders</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> customers c</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> orders o <span class="kw">USING</span> (customer_id)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> c.customer_id, c.name;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+-------+------------+----------+
| name  | count_star | n_orders |
+-------+------------+----------+
| Alice | 3          | 3        |
| Bob   | 1          | 1        |
| Carol | 1          | 1        |
| Dana  | 1          | 0        |
+-------+------------+----------+</code></pre>
<p><code>COUNT(*)</code> says Dana placed one order. She didn’t: the left join gave her one row full of NULLs, and <code>COUNT(*)</code> counts rows. <code>COUNT(o.order_id)</code> counts actual orders. After a left join, count a column from the right-hand table.</p>
</section>
<section id="a-join-that-counted-alice-twice" class="level3">
<h3 class="anchored" data-anchor-id="a-join-that-counted-alice-twice">A join that counted Alice twice</h3>
<p>Someone hands you a <code>contacts</code> table, and Alice has two email addresses in it:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> contacts (customer_id <span class="dt">INTEGER</span>, email TEXT);</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> contacts <span class="kw">VALUES</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span>, <span class="st">'alice@example.com'</span>),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span>, <span class="st">'alice.w@example.org'</span>),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">2</span>, <span class="st">'bob@example.com'</span>),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">3</span>, <span class="st">'carol@example.com'</span>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>You join orders to contacts to send receipts, checking revenue before and after:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_rows, <span class="fu">SUM</span>(amount) <span class="kw">AS</span> revenue</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders;</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_rows, <span class="fu">SUM</span>(o.amount) <span class="kw">AS</span> revenue</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders o</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="kw">JOIN</span> contacts k <span class="kw">USING</span> (customer_id);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>+--------+---------+
| n_rows | revenue |
+--------+---------+
| 6      | 168.74  |
+--------+---------+
+--------+---------+
| n_rows | revenue |
+--------+---------+
| 8      | 289.73  |
+--------+---------+</code></pre>
<p>Two things happened. Each of Alice’s three orders matched both her addresses, so her $132.99 counted twice, and the guest order, with no contact, fell out of the inner join and took $12 with it. Eight rows and $289.73 look like a busy week, not a bug; checking <code>contacts</code> for repeated keys first would have caught it. Join only the tables a question needs (revenue doesn’t need emails), or cut the many side to one row per key first, for instance with <code>SELECT customer_id, MIN(email) AS email FROM contacts GROUP BY customer_id</code>.</p>
</section>
<section id="run-a-sql-query-and-chart-the-result" class="level3">
<h3 class="anchored" data-anchor-id="run-a-sql-query-and-chart-the-result">Run a SQL query and chart the result</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> contextlib <span class="im">import</span> closing</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> closing(sqlite3.<span class="ex">connect</span>(<span class="st">"shop.db"</span>)) <span class="im">as</span> conn:</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>    daily <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"""</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="st">        SELECT DATE(date) AS day, SUM(amount) AS revenue</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="st">        FROM orders</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="st">        WHERE date &gt;= '2024-01-01'</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="st">        GROUP BY day</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="st">        ORDER BY day</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="st">        """</span>,</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>        conn,</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>        parse_dates<span class="op">=</span>[<span class="st">"day"</span>],</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daily)</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>daily.plot(x<span class="op">=</span><span class="st">"day"</span>, y<span class="op">=</span><span class="st">"revenue"</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>         day  revenue
0 2024-03-01    29.99
1 2024-03-02    15.50
2 2024-03-03    50.25
3 2024-03-05    61.00
4 2024-03-06    12.00</code></pre>
<p>The database adds up each day’s orders, which on a real table might mean millions of rows; pandas turns <code>day</code> into real dates with <code>parse_dates</code> and draws the chart. Each tool does the part it’s best at.</p>
</section>
</section>
<section id="templates" class="level2" data-number="23.13">
<h2 data-number="23.13" class="anchored" data-anchor-id="templates"><span class="header-section-number">23.13</span> Templates</h2>
<p><strong>A query function with placeholders:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> contextlib <span class="im">import</span> closing</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> query(sql, params<span class="op">=</span><span class="va">None</span>, db<span class="op">=</span><span class="st">"shop.db"</span>):</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Run one query and return the result as a DataFrame."""</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> closing(sqlite3.<span class="ex">connect</span>(db)) <span class="im">as</span> conn:</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> pd.read_sql_query(sql, conn, params<span class="op">=</span>params)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> query(</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SELECT * FROM orders WHERE amount &gt; ? ORDER BY amount DESC LIMIT ?"</span>,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>    params<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">2</span>),</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>A first look at an unfamiliar SQLite database:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- 1. What tables are here? (sqlite_schema is a newer name for sqlite_master)</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> name <span class="kw">FROM</span> sqlite_master <span class="kw">WHERE</span> <span class="kw">type</span> <span class="op">=</span> <span class="st">'table'</span>;</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">-- 2. What columns does a table have?</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>PRAGMA table_info(orders);</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co">-- 3. How big is it?</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">FROM</span> orders;</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co">-- 4. What do the first 5 rows look like?</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> orders <span class="kw">LIMIT</span> <span class="dv">5</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Every database has its own version of the first two. In DuckDB they’re <code>SHOW TABLES;</code> and <code>DESCRIBE orders;</code>, and in the <code>sqlite3</code> shell <code>.tables</code> and <code>.schema orders</code> do the same job. <a href="https://www.sqlite.org/pragma.html#pragma_table_info"><code>PRAGMA table_info</code></a> also shows which column is the primary key and which can’t be NULL.</p>
</section>
<section id="exercises" class="level2" data-number="23.14">
<h2 data-number="23.14" class="anchored" data-anchor-id="exercises"><span class="header-section-number">23.14</span> Exercises</h2>
<ol type="1">
<li>Download the sample <a href="https://github.com/lerocha/chinook-database">Chinook SQLite database</a> (or any other small public dataset). Write a <code>SELECT</code> that lists the ten longest tracks.</li>
<li>Using the same database, count the tracks in each genre and sort the genres from most tracks to fewest.</li>
<li>Join two tables on a shared key. Before running it, write down how many rows it should return; then check with <code>COUNT(*)</code>.</li>
<li>Write a <code>LEFT JOIN</code> plus <code>IS NULL</code> query that finds customers with no purchases (or whatever the equivalent is in your dataset).</li>
<li>Write a function <code>customers_in(city)</code> that returns a DataFrame of customers in that city, using a <code>?</code> placeholder. Call it with <code>"O'Brien"</code> and <code>"x' OR '1'='1"</code>; neither should break it.</li>
<li>Find a column with NULLs and compare <code>COUNT(*)</code>, <code>COUNT(col)</code>, and <code>COUNT(DISTINCT col)</code>. What does each number mean?</li>
<li>Translate a pandas pipeline you’ve already written into SQL (or compare <code>.describe()</code> with SQL’s <code>COUNT</code>, <code>AVG</code>, <code>MIN</code>, and <code>MAX</code>). Confirm the numbers agree; if they don’t, look first at how each handles missing values.</li>
</ol>
</section>
<section id="one-page-checklist" class="level2" data-number="23.15">
<h2 data-number="23.15" class="anchored" data-anchor-id="one-page-checklist"><span class="header-section-number">23.15</span> One-page checklist</h2>
<ul>
<li>Text values in single quotes; double quotes only for table and column names.</li>
<li><code>IS NULL</code> and <code>IS NOT NULL</code>, never <code>= NULL</code>; decide which side of <code>&lt;&gt;</code> the NULLs belong on.</li>
<li><code>COUNT(*)</code> counts rows; <code>COUNT(col)</code> counts non-NULL values.</li>
<li>Every column in <code>SELECT</code> is in <code>GROUP BY</code> or inside an aggregate.</li>
<li><code>WHERE</code> filters rows; <code>HAVING</code> filters groups.</li>
<li>Give <code>ORDER BY</code> a unique tiebreaker before paging with <code>LIMIT</code> and <code>OFFSET</code>.</li>
<li><code>INNER JOIN</code> keeps matches only; <code>LEFT JOIN</code> keeps every row of the left table.</li>
<li>Count rows before and after every join, and check the join key for repeats.</li>
<li>From Python, pass values with <code>?</code> placeholders, never f-strings.</li>
<li>Call <code>conn.commit()</code> after changing data, and close connections with <code>contextlib.closing</code>.</li>
<li>Load results into pandas with <code>pd.read_sql_query</code> for plotting and reshaping.</li>
<li>For anything beyond this chapter, your database’s own documentation is the authority (see <a href="reading-docs.html" class="quarto-xref"><span>Chapter 5</span></a>).</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📚 Further reading
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>SQLite</strong>, <a href="https://www.sqlite.org/lang.html">SQL language reference</a> — the grammar SQLite actually implements, small enough to read end to end.</li>
<li><strong>PostgreSQL Global Development Group</strong>, <a href="https://www.postgresql.org/docs/current/">PostgreSQL documentation</a> — the manual for a widely used open-source database server, for when you outgrow a single file.</li>
<li><strong>ThoughtSpot (formerly Mode)</strong>, <a href="https://www.thoughtspot.com/sql-tutorial">SQL Tutorial for Data Analysis</a> — a free, beginner-friendly tutorial with practice exercises you run in the browser against real data.</li>
<li><strong>Python docs</strong>, <a href="https://docs.python.org/3/library/sqlite3.html"><code>sqlite3</code> module</a> — the standard library’s SQLite interface, with how-to guides on placeholders, transactions, and type conversion.</li>
<li><strong>Markus Winand</strong>, <a href="https://use-the-index-luke.com/">Use The Index, Luke!</a> — a free book on indexes and query performance, for the day your queries get slow.</li>
<li><strong>Patrick McKenzie</strong>, <a href="https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/">Falsehoods Programmers Believe About Names</a> — the classic list of assumptions that “first name, last name” schemas get wrong; read it before you design a table of people.</li>
<li><strong>DuckDB</strong>, <a href="https://duckdb.org/docs/">Documentation</a> — the analysis-focused engine that queries Parquet, CSV, and DataFrames from inside Python; the natural next step after <code>sqlite3</code>.</li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/pandas-basics.html" class="pagination-link" aria-label="pandas Basics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">pandas Basics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/http-apis.html" class="pagination-link" aria-label="HTTP and Web APIs">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">HTTP and Web APIs</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/edit/main/chapters/sql-basics.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/cuinfoscience/INFO-Missing-Manual/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>